### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by simonh1000** [jspm/jspm-cli#1000]
Hi, I've been using jspm to look into Aurelia + Typescript and I regularly bump into this stacktrace. In this instance it was after running `jspm install -y` on [this repository](https://github.com/paulvanbladel/aurelia-typescript-lean-dev). I'm using jspm@beta so I hope this bug report is useful

```
     Looking up npm:is-array
     Looking up npm:ieee754
     Looking up npm:base64-js
ok   Up to date - bootstrap as github:twbs/bootstrap@^3.3.4 (3.3.5)
ok   Up to date - typescript as npm:typescript@^1.5.3 (1.5.3)
ok   Install tree has no forks.

err  TypeError: Cannot read property 'forEach' of undefined
         at /Users/simon/.nvm/versions/node/v0.12.7/lib/node_modules/jspm/lib/core.js:212:10
         at tryCatchReject (/Users/simon/.nvm/versions/node/v0.12.7/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/Users/simon/.nvm/versions/node/v0.12.7/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/Users/simon/.nvm/versions/node/v0.12.7/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at ContinuationTask.run (/Users/simon/.nvm/versions/node/v0.12.7/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1040:24)
         at Scheduler._drain (/Users/simon/.nvm/versions/node/v0.12.7/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
         at Scheduler.drain (/Users/simon/.nvm/versions/node/v0.12.7/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:62:9)
         at process._tickCallback (node.js:355:11)

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
@simonh1000 which version of jspm are you running here? It could be worth upgrading to the 0.16 beta.

**Comment by simonh1000** [comment]
Yes, i thought I had installed beta, but had not. I'm going to assume that that is the cause and close
