### ISSUE TITLE
Broken bundle

### ISSUE THREAD

**Issue by panicbit** [jspm/jspm-cli#1047]
Using a bundle results in the following error:

```
Error: Module undefined not declared as a dependency.
	Error loading http://localhost:8000/index.coffee!http://localhost:8000/jspm_packages/github/forresto/system-coffee@0.1.2.js
    at http://localhost:8000/jspm_packages/system.js:4:21254
    at http://localhost:8000/build.js:31880:14
    at u (http://localhost:8000/jspm_packages/system.js:4:21145)
    at a (http://localhost:8000/jspm_packages/system.js:4:19710)
    at Object.Promise.all.then.execute (http://localhost:8000/jspm_packages/system.js:4:24206)
    at b (http://localhost:8000/jspm_packages/system.js:4:8159)
    at x (http://localhost:8000/jspm_packages/system.js:4:8538)
    at p (http://localhost:8000/jspm_packages/system.js:4:6416)
    at h (http://localhost:8000/jspm_packages/system.js:4:6801)
    at http://localhost:8000/jspm_packages/system.js:4:5107
```

**Comment by guybedford** [comment]
Can you share a bit more info about how you got this? If I have an `index.coffee` containing:

```javascript
module.exports = 'asdf';
```

It certainly works fine for me with `jspm bundle index.coffee! -i` and a `System.import('index.coffee!')`.

**Comment by panicbit** [comment]
I could narrow it down to `jade`.
Try requiring a jade template.

**Comment by guybedford** [comment]
I'd suggest posting an issue to the jade plugin page, as it is outputting this code here.

**Comment by panicbit** [comment]
@guybedford Alright, thanks
