### ISSUE TITLE
jspm install package  from github got timeout error 

### ISSUE THREAD

**Issue by wanghao8080** [jspm/jspm-cli#1115]
```
 → jspm install semantic-ui
     Updating registry cache...
     Looking up github:Semantic-Org/Semantic-UI
     Downloading github:Semantic-Org/Semantic-UI@2.1.3

warn Error on getPackageConfig for github:Semantic-Org/Semantic-UI
     Error: connect ETIMEDOUT 204.13.250.16:443
         at Object.exports._errnoException (util.js:837:11)
         at exports._exceptionWithHostPort (util.js:860:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)

err  Error: Error getting package config for github:Semantic-Org/Semantic-UI.
         at /Users/xiaoxue/Desktop/blog/ninghao-workflow/node_modules/systemjs-builder/lib/builder.js:23:9
         at Object.lib$rsvp$events$$default.trigger (/Users/xiaoxue/Desktop/blog/ninghao-workflow/node_modules/rsvp/dist/rsvp.js:245:13)
         at null._onTimeout (/Users/xiaoxue/Desktop/blog/ninghao-workflow/node_modules/rsvp/dist/rsvp.js:779:47)
         at Timer.listOnTimeout (timers.js:89:15)

warn Error on download for github:Semantic-Org/Semantic-UI
     Error: connect ETIMEDOUT 204.13.250.16:443
         at Object.exports._errnoException (util.js:837:11)
         at exports._exceptionWithHostPort (util.js:860:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)

err  Error downloading github:Semantic-Org/Semantic-UI.

warn Installation changes not saved.
```

my jspm config file is this ：

```
{
  "defaultTranspiler": "babel",
  "defaultRegistry": "jspm",
  "registries": {
    "github": {
      "remote": "https://github.jspm.io",
      "timeouts": {
        "lookup": "600",
        "download": "600",
        "build": "600"
      },
      "maxRepoSize": 0,
      "auth": "d2FuZ2hhbzgwODA6V2gxMlw",
      "handler": "jspm-github"
    },
    "npm": {
      "handler": "jspm-npm",
      "remote": "https://npm.jspm.io",
      "timeouts": {
        "lookup": "600",
        "download": "600",
        "build": "600"
      }
    },
    "jspm": {
      "handler": "jspm-registry",
      "remote": "https://registry.jspm.io"
    }
  },
  "strictSSL": true
```

**Comment by guybedford** [comment]
@wanghao8080 are you able to download any dependencies from GitHub here at all (eg say `jspm install jquery`)? Also are you running behind a proxy?

I'd suggest you change your GitHub password as it is contained unencrypted in your `auth` string above.

**Comment by guybedford** [comment]
@wanghao8080 did you manage to make progress here?
