### ISSUE TITLE
jspm install "has no registry property provided"

### ISSUE THREAD

**Issue by dazinator** [jspm/jspm-cli#1117]
I have commited to my repo without the `jspm_packages` folder (`jspm_packages added to .gitignore file)

When I clone the repo, and then do a `jspm install` I get the following error:

```
C:\Users\Darrell\Repo\ws\dazinatewebsite\src\DazinateWebsite>jspm install

err  TypeError: Install of jspm to ^0.16.2 has no registry property provided.
         at C:\Users\Darrell\Repo\ws\dazinatewebsite\src\DazinateWebsite\node_mo
dules\jspm\lib\package.js:312:13
         at Array.forEach (native)
         at processDeps (C:\Users\Darrell\Repo\ws\dazinatewebsite\src\DazinateWe
bsite\node_modules\jspm\lib\package.js:295:21)
         at setDefaults (C:\Users\Darrell\Repo\ws\dazinatewebsite\src\DazinateWe
bsite\node_modules\jspm\lib\config\package.js:129:28)
         at PackageJSON.read (C:\Users\Darrell\Repo\ws\dazinatewebsite\src\Dazin
ateWebsite\node_modules\jspm\lib\config\package.js:116:3)
         at C:\Users\Darrell\Repo\ws\dazinatewebsite\src\DazinateWebsite\node_mo
dules\jspm\lib\config.js:78:25
         at runMicrotasksCallback (node.js:337:7)
         at process._tickCallback (node.js:355:11)
         at Function.Module.runMain (module.js:503:11)
         at startup (node.js:129:16)

warn Installation changes not saved.
```

Here is my `package.json`
```json
{
  "jspm": {
    "directories": {
      "baseURL": "wwwroot",
      "packages": "jspm_packages"
    }
  },
  "devDependencies": {
    "jspm": "^0.16.2",
    "gulp": "^3.9.0",
    "gulp-tslint": "^3.2.0",
    "browser-sync": "^2.9.3"
  }
 
}
```

Any ideas?

**Comment by dazinator** [comment]
I managed to fix this by:

1. Adding in the `"registry": "npm"` line to Package.json (even though the documentation says by default this registry should be used?)

```json
{
  "jspm": {
    "registry": "npm",
    "directories": {
      "baseURL": "wwwroot",
      "packages": "jspm_packages"
    },
    "devDependencies": {
      "babel": "babel-core@^5.8.22",
      "babel-runtime": "^5.8.20",
      "browser-sync": "^2.9.3",
      "core-js": "^1.1.0",
      "gulp": "^3.9.0",
      "gulp-tslint": "^3.2.0",
      "jspm": "^0.16.2"
    }
  },
  "devDependencies": {
    "jspm": "^0.16.2",
    "gulp": "^3.9.0",
    "gulp-tslint": "^3.2.0",
    "browser-sync": "^2.9.3"
  }
}

```

Doing a `jspm install` then produced a different error saying it could not find a registry called "dist"..

Upon checking `config.js` I had a path configured called "dist".. Removing the path fixed this second error.. I didn't realise paths had anything to do with registries - probably my ignorance
