### ISSUE TITLE
jspm bundle-sfx fails with --format cjs

### ISSUE THREAD

**Issue by lyschoening** [jspm/jspm-cli#1126]
I get the following error when running `jspm bundle-sfx test test-bundle.js --format cjs`. It works with other formats. The contents of the `test.js` here do not matter.

```
$ jspm bundle-sfx test test-bundle.js --format cjs
     Building the single-file sfx bundle for test...

err  TypeError: Unable to compile expression:
        args: "deps, sfxGlobals, sfxGlobalName"
        body: "return (deps.map(function(dep) {\n    return 'require(\"' + dep + '\")';\n  )"
        error: SyntaxError: Unexpected token )
         at Function (native)
         at /Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/resolve.js:28:10
         at Array.forEach (native)
         at module.exports (/Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/resolve.js:23:9)
         at module.exports (/Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/resolve-to-string.js:7:30)
         at module.exports (/Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/index.js:7:9)
         at /Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:265:18
         at lib$rsvp$$internal$$tryCatch (/Users/lyschoening/test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/lyschoening/test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
         at lib$rsvp$$internal$$publish (/Users/lyschoening/test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:476:11)
         at /Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/resolve.js:30:11
         at Array.forEach (native)
         at module.exports (/Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/resolve.js:23:9)
         at module.exports (/Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/resolve-to-string.js:7:30)
         at module.exports (/Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/node_modules/es6-template-strings/index.js:7:9)
         at /Users/lyschoening/test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:265:18
         at lib$rsvp$$internal$$tryCatch (/Users/lyschoening/test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/lyschoening/test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
         at lib$rsvp$$internal$$publish (/Users/lyschoening/test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:476:11)
         at lib$rsvp$asap$$flush (/Users/lyschoening/test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
$ jspm --version
0.16.2
Running against local jspm install.
```

**Comment by guybedford** [comment]
Thanks for posting, fixed in https://github.com/systemjs/builder/commit/c9bd5c1210a24938312aefb1aa0e9709360308a7.
