### ISSUE TITLE
Cannot find module 'process'

### ISSUE THREAD

**Issue by jclif** [jspm/jspm-cli#1129]
I am trying to install and run nightwatch, but am encountering an error when I try to run the nightwatch script. Has anyone else run into the error?

```
$ ./jspm_packages/npm/nightwatch@0.8.3/bin/nightwatch

module.js:338
    throw err;
          ^
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/path/to/jspm_packages/npm/nightwatch@0.8.3/bin/runner.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

Here is the offending file within nightwatch:
```
/* */ 
(function(process) {
  var Logger = require("../lib/util/logger");
  var Nightwatch = require("../lib/index");
  try {
    Nightwatch.cli(function(argv) {
      Nightwatch.runner(argv);
    });
  } catch (ex) {
    Logger.error('There was an error while starting the test runner:\n\n');
    process.stderr.write(ex.stack + '\n');
    process.exit(2);
  }
})(require("process"));
```

**Comment by douglasduteil** [comment]
Did you simply try a  `jspm i process` ?

**Comment by guybedford** [comment]
jspm isn't designed to provide server executable support just yet. Rather use npm for these use cases. See https://github.com/jspm/jspm-cli/blob/master/docs/nodejs-usage.md for more info here.
