### ISSUE TITLE
Normalize paths in system config?

### ISSUE THREAD

**Issue by doctyper** [jspm/jspm-cli#1146]
Note: this might be a SystemJS issue.

I'm trying to workaround the jspm 0.16 issue where `defaultJSExtensions` must be true. I'm trying to define my own normalize function as described [here](https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/loader-extensions.md) to remove `.js` extensions from files that don't need the extension:

```js
// FIXME: Possibly not needed in jspm 0.17
// store the old normalization function
var systemNormalize = loader.normalize;

// override the normalization function
loader.normalize = function (name, parentName, parentAddress) {
    return systemNormalize.call(this, name, parentName, parentAddress).then(function (url) {
        if ((/\.(?:eot|gif|jpe?g|otf|png|svg|ttf|woff)\.js$/).test(url)) {
            return url.replace(/\.js$/, "");
        }

        return url;
    });
};
```

This works fine on the browser. However, I need this defined in the SystemJS config so that the `jspm` cli can apply the custom normalize function. I get the following error when I attempt to add it to my `config.js`:

Sample config.js:

```js
System.config({
  defaultJSExtensions: true
  // other things
});

// FIXME: Possibly not needed in jspm 0.17
// store the old normalization function
var systemNormalize = System.normalize;

// override the normalization function
System.normalize = function (name, parentName, parentAddress) {
    return systemNormalize.call(this, name, parentName, parentAddress).then(function (url) {
        if ((/\.(?:eot|gif|jpe?g|otf|png|svg|ttf|woff)\.js$/).test(url)) {
            return url.replace(/\.js$/, "");
        }

        return url;
    });
};
```

However, running `jspm depCache` throws the following:

```bash
err  TypeError: Cannot read property 'call' of undefined
         at SystemJSNodeLoader.System.normalize (eval at <anonymous> (/usr/local/lib/node_modules/jspm/lib/config/loader.js:94:15), <anonymous>:470:27)
         at expandGlobAndCanonicalize (/usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:82:19)
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:120:30
         at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
         at /usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1001:13
         at lib$rsvp$asap$$flush (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
         at doNTCallback0 (node.js:407:9)
         at process._tickCallback (node.js:336:13)
         at Function.Module.runMain (module.js:477:11)
```

It appears `System.normalize` is not defined when jspm finds the config, and so the custom method fails. Is there an alternate approach I can take?

Thanks for your time.

**Comment by doctyper** [comment]
Update: I worked around my workaround by adding the following to `System.config`:

```js
  meta: {
    "*.jpg.js": {
      "build": false
    }
  }
```
