### ISSUE TITLE
jspm i fails when system has NPM 3.3.3

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#1156]
I have just installed jspm 
```
jspm@0.16.10 /usr/lib/node_modules/jspm
├── rimraf@2.4.3
├── graceful-fs@3.0.8
├── ncp@2.0.0
├── semver@5.0.3
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── jspm-registry@0.4.0 (semver@4.3.6)
├── rsvp@3.1.0
├── glob@5.0.14 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@2.0.10 (brace-expansion@1.1.0)
├── liftoff@2.2.0 (findup-sync@0.3.0, extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6)
├── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
├── request@2.63.0 (aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, caseless@0.11.0, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, combined-stream@1.0.5, qs@5.1.0, form-data@1.0.0-rc3, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, tough-cookie@2.0.0, har-validator@1.8.0, hawk@3.1.0)
├── jspm-npm@0.25.0 (which@1.1.2, resolve@1.1.6, tar@1.0.3, rmdir@1.1.0, request@2.58.0)
├── jspm-github@0.13.5 (netrc@0.1.4, which@1.1.2, yauzl@2.3.1, rimraf@2.3.4, tar@2.2.1, request@2.53.0)
├── traceur@0.0.91 (commander@2.6.0, semver@2.3.2, glob@4.3.5, source-map-support@0.2.10)
├── systemjs@0.19.3 (when@3.7.3, es6-module-loader@0.17.8)
├── core-js@0.9.18
└── systemjs-builder@0.14.6 (source-map@0.4.4, algorithms@0.9.1, es6-template-strings@2.0.0)

```
and when i try to run jspm i, I get:
```
 jspm i
module.js:338
    throw err;
    ^

Error: Cannot find module '../modules/es6.string.from-code-point'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/capaj/WebstormProjects/postuj-hovna/node_modules/jspm/node_modules/core-js/es6/string.js:1:63)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```

**Comment by matthewbauer** [comment]
I was having this issue earlier. Something to try would be removing your jspm_packages and node_modules directories. Also make sure that the local jspm and the global one have the same version.

**Comment by guybedford** [comment]
I guess you can check if the file at `/home/capaj/WebstormProjects/postuj-hovna/node_modules/jspm/node_modules/core-js/modules/es6.string.from-code-point` exists?
