### ISSUE TITLE
Improve error messages for missing imports

### ISSUE THREAD

**Issue by pietschy** [jspm/jspm-cli#1217]
Howdy, 

As per request in #1203.

Here's what I'm currently getting when I reference a non existent file from an import (it only references the missing file, langs.js, and not the file that tried to import it).
```
jspm bundle pectin ./public/js/build.js --inline-source-maps
     Building the bundle tree for pectin...

err  Error: ENOENT, open '/Users/andrew/projects/pectin/src/pectin/langs.js'
         at Error (native)
[09:15:30] 'build-jspm-bundle' errored after 3.17 s
[09:15:30] Error: Command `jspm bundle pectin ./public/js/build.js --inline-source-maps` exited with code 1
    at ChildProcess.<anonymous> (/Users/andrew/projects/pectin/node_modules/gulp-run/lib/command.js:145:15)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
[09:15:30] 'build-src' errored after 3.21 s
[09:15:30] Error: Command `jspm bundle pectin ./public/js/build.js --inline-source-maps` exited with code 1
    at ChildProcess.<anonymous> (/Users/andrew/projects/pectin/node_modules/gulp-run/lib/command.js:145:15)
    at ChildProcess.g (events.js:199:16)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

Thanks!

**Comment by guybedford** [comment]
@pietschy thanks for posting, error messages are really important to get right. Can you confirm you're running the latest release of jspm / SystemJS here?

**Comment by pietschy** [comment]
Hi @guybedford, I was running jspm 0.16.2 and SystemJS 0.18.17 but I just upgraded to jspm 0.16.13 and SystemJS 0.19.5 and tested again.

The error message is more detailed, but still doesn't seem to include the file with the missing import. e.g.
```
err  Error on fetch for src/pectin/models/baseValueModels.js at file:///Users/andrew/projects/pectin/src/pectin/models/baseValueModels.js
	Error: ENOENT, open '/Users/andrew/projects/pectin/src/pectin/models/baseValueModels.js'
         at Error (native)
```

**Comment by pietschy** [comment]
As a side note, I've had 2 other side effects of the upgrade to 0.16.13/0.19.5.
- My inline source maps no longer work in chrome inspector.  I checked and they are present in the bundle file but haven't got much further.
- Previously I was importing traceur-runtime using systemjs, e.g. 
```
System.import('traceur-runtime).then(function() {  
   System.import('app'); 
});
```
This now gives me an error about not being able to find `path.js`.  I'm using traceur 0.0.92 and importing it manually using the full jspm_packages path works ok.  Again I haven't had a chance to investigate further but will update if I find anything of use.

If these look like bugs with jspm/systemjs let me know and I'll raise some issues.

**Comment by guybedford** [comment]
Thanks, the `traceur-runtime` loading should be working again now.

For the inline source maps, that was unfortunately a regression in Babel being tracked in https://github.com/jspm/jspm-cli/issues/1205.

I've created an issue for the builder debugging trace in https://github.com/systemjs/builder/issues/370.
