### ISSUE TITLE
jspm link throws error

### ISSUE THREAD

**Issue by lyptt** [jspm/jspm-cli#1279]
I'm trying to use jspm link so that I can target local versions of my dependencies in development, with the following command:

```
jspm link path/to/local/module/ module@1
```

This results in the following error:

```
err  Error: TypeError: undefined is not a function
         at moduleMsg (/path/to/container/module/node_modules/jspm/lib/ui.js:104:6)
         at Object.exports.format.err (/path/to/container/module/node_modules/jspm/lib/ui.js:67:45)
         at Object.exports.log (/path/to/container/module/node_modules/jspm/lib/ui.js:92:23)
         at /path/to/container/module/node_modules/jspm/lib/link.js:112:8
         at lib$rsvp$$internal$$tryCatch (/path/to/container/module/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/path/to/container/module/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
         at lib$rsvp$$internal$$publish (/path/to/container/module/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:476:11)
         at lib$rsvp$$internal$$publishRejection (/path/to/container/module/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:419:7)
         at lib$rsvp$asap$$flush (/path/to/container/module/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
         at process._tickCallback (node.js:355:11)
         at /path/to/container/module/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:23:9
         at Object.lib$rsvp$events$$default.trigger (/path/to/container/module/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:245:13)
         at null._onTimeout (/path/to/container/module/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:779:47)
         at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by guybedford** [comment]
Thanks that's a bug in the error system - I've added a fix in https://github.com/jspm/jspm-cli/commit/bc55277aace349ff2e3c2ca731437caf64dbb8a6. That should then clarify the underlying issue.

**Comment by lyptt** [comment]
Thanks to that commit I can see that this seems to just be a misunderstanding of the link functionality. I had another look through the link documentation and it seems that instead of working similarly to `npm link`, instead it's a bit more of an involved workflow.

Thanks for helping me out on this one!
