### ISSUE TITLE
jspm update error with custom map config

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm-cli#1283]
Apparently the following error shows when running `jspm update` with custom map entries:

```
err  TypeError: Path must be a string. Received undefined
         at assertPath (path.js:8:11)
         at Object.posix.resolve (path.js:426:5)
         at Package.getPath (/Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/lib/config/package-name.js:82:15)
         at Object.exports.download (/Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/lib/package.js:430:25)
         at /Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/lib/install.js:697:15
         at lib$rsvp$$internal$$initializePromise (/Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:541:9)
         at new lib$rsvp$promise$$Promise (/Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:757:9)
         at /Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/lib/install.js:690:49
         at lib$rsvp$$internal$$tryCatch (/Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/Jesse/NetBeansProjects/roambee/wc2/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
```

//cc @jbgarr

**Comment by guybedford** [comment]
Duplicate of https://github.com/jspm/jspm-cli/issues/1351.
