### ISSUE TITLE
err  TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by Xample** [jspm/jspm-cli#1300]
I am facing this error, starting a project from scratch:
```bash
mkdir testJSPM && cd testJSPM
#all default
npm init
npm install --save jspm
#all default but typescript as the transpiler
jspm init
```
Here below is the log:

```log
mbp:testJSPM xample$ jspm init
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use a transpiler? [yes]:
Which ES6 transpiler would you like to use, Babel, TypeScript or Traceur? [babel]:     TypeScript
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...

err  TypeError: must start with number, buffer, array or string
         at fromObject (buffer.js:167:9)
         at new Buffer (buffer.js:58:10)
         at decodeCredentials (/Users/xample/Documents/Icflix/testJSPM/node_modules/jspm-github/github.js:54:14)
         at Object.GithubLocation (/Users/xample/Documents/Icflix/testJSPM/node_modules/jspm-github/github.js:100:17)
         at Object.exports.load (/Users/xample/Documents/Icflix/testJSPM/node_modules/jspm/lib/registry.js:73:56)
         at dl (/Users/xample/Documents/Icflix/testJSPM/node_modules/jspm/lib/core.js:260:27)
         at /Users/xample/Documents/Icflix/testJSPM/node_modules/jspm/lib/core.js:333:12
         at process._tickCallback (node.js:377:9)

```

```log
mbp:test xample$ node -v
v5.0.0
```
[EDIT] actually "jspm init" is not working, whatever the transpiler used, am I alone in this case ?
```bash
jspm init

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.

Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use a transpiler? [yes]:
Which ES6 transpiler would you like to use, Babel, TypeScript or Traceur? [babel]:
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...

err  TypeError: must start with number, buffer, array or string
         at fromObject (buffer.js:167:9)
         at new Buffer (buffer.js:58:10)
         at decodeCredentials (/usr/local/lib/node_modules/jspm/node_modules/jspm-github/github.js:54:14)
         at Object.GithubLocation (/usr/local/lib/node_modules/jspm/node_modules/jspm-github/github.js:100:17)
         at Object.exports.load (/usr/local/lib/node_modules/jspm/lib/registry.js:73:56)
         at dl (/usr/local/lib/node_modules/jspm/lib/core.js:260:27)
         at /usr/local/lib/node_modules/jspm/lib/core.js:333:12
         at process._tickCallback (node.js:377:9)

err  Unable to load registry github

err  Error downloading loader files.

err  Unable to load registry github
mbp:EssaisJSPM xample$ jspm init
```

**Comment by Xample** [comment]
Ok I found the issue, here is how to fix it:
```bash
jspm registry config github
```
Full log:
```bash
jspm registry config github
Would you like to set up your GitHub credentials? [yes]:
     If using two-factor authentication or to avoid using your password you can generate an access token at https://github.com/settings/tokens. Ensure it has public_repo scope access.

Enter your GitHub username:username@adomain.com
Enter your GitHub password or access token:
Would you like to test these credentials? [yes]:
ok   GitHub authentication is working successfully.
ok   Registry github configured successfully.
```

Note:
The problem came at the line 53 in Github.js
```js
function decodeCredentials(str) {
```
Where the "str" credentials were empty (an empty object), without this I could have searched for a long time…
