### ISSUE TITLE
Error when defining a defaultProps

### ISSUE THREAD

**Issue by jadedevin13** [jspm/jspm-cli#1301]
# jspm throws error on translate.

```javascript
import React from 'react';

export default class BrandLogo extends React.Component{
    static propTypes = {
        brandLogo : React.PropTypes.string
    };

    static defaultProps = {
        brandLogo : "brandLogo"
    };

    render(){
        return <a className="brand-logo">{this.props.brandLogo}</a>;
    }
}
```

## When I delete the propTypes and defaultProps it runs well.

Here is the error warning

`Error: Parse Error: Line 4: Unexpected token =
         at throwError (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:2322:17)
         at throwUnexpected (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:2371:7)
         at expect (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:2376:9)
         at parseParams (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:4653:7)
         at parsePropertyMethodFunction (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:2543:13)
         at parseMethodDefinition (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:4877:65)
         at parseClassElement (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:4919:34)
         at parseClassBody (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:4935:24)
         at parseClassDeclaration (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:5042:82)
         at parseStatement (file:///home/jadedevin13/Documents/websites/AppLERT/public/jspm_packages/npm/esprima-fb@13001.1001.0-dev-harmony-fb/esprima.js:4458:20)`

## Here is my json dependencies

```javascript
    "dependencies": {
      "font-awesome": "github:FortAwesome/Font-Awesome@^4.4.0",
      "foundation-sites": "npm:foundation-sites@^6.0.1",
      "jquery": "github:components/jquery@^2.1.4",
      "jsx": "github:floatdrop/plugin-jsx@^1.1.0",
      "materialize-css": "github:dogfalo/materialize@^0.97.3",
      "react": "npm:react@^0.14.3",
      "react-dom": "npm:react-dom@^0.14.3"
    }
```

**Comment by stoiet** [comment]
Did you enabled "stage": 1 in your babelOptions?

**Comment by jadedevin13** [comment]
Thank you I've seen the solution. My mistake I didn't know fields are not available in plain es6. https://facebook.github.io/react/docs/reusable-components.html#es6-classes

```javascript
export class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};
  }
  tick() {
    this.setState({count: this.state.count + 1});
  }
  render() {
    return (
      <div onClick={this.tick.bind(this)}>
        Clicks: {this.state.count}
      </div>
    );
  }
}
Counter.propTypes = { initialCount: React.PropTypes.number };
Counter.defaultProps = { initialCount: 0 };
```
I was searching for a documentation for babelOptions but failed. I wish there is one.

**Comment by stoiet** [comment]
You can set babelOptions in your systemjs config.js file:
https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#babeloptions
