### ISSUE TITLE
jspm bundle-sfx throws error cannot read 'processedValue' of undefined using 0.16.17

### ISSUE THREAD

**Issue by joeycadle** [jspm/jspm-cli#1366]
Getting this error in 0.16.17 when running jspm bundle-sfx:

```
err  TypeError: Cannot read property 'processedValue' of undefined
         at ParseTreeTransformer.CJSRequireTransformer.transformCallExpression (/home/jenkins-slave/workspace/fooreplace/node_modules/systemjs-builder/compilers/cjs.js:42:55)
         at CallExpression.$__super.transform (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:7241:28)
         at ParseTreeTransformer.transformAny (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15224:44)
         at ParseTreeTransformer.transformExpressionStatement (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15535:31)
         at ExpressionStatement.$__super.transform (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:7712:28)
         at ParseTreeTransformer.transformAny (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15224:44)
         at ParseTreeTransformer.transformList (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15231:34)
         at ParseTreeTransformer.transformBlock (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15348:31)
         at Block.$__super.transform (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:7204:28)
         at ParseTreeTransformer.transformAny (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15224:44)
         at ParseTreeTransformer.transformTryStatement (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:16001:25)
         at TryStatement.$__super.transform (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:8991:28)
         at ParseTreeTransformer.transformAny (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15224:44)
         at ParseTreeTransformer.transformList (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15231:34)
         at ParseTreeTransformer.transformBlock (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:15348:31)
         at Block.$__super.transform (/home/jenkins-slave/workspace/fooreplace/node_modules/traceur/bin/traceur.js:7204:28)
```

**Comment by guybedford** [comment]
Thanks, fixed in 0.16.18.
