### ISSUE TITLE
jspm update: Timeouts for some npm dependencies

### ISSUE THREAD

**Issue by reppners** [jspm/jspm-cli#1373]
When I do `jspm update` in a project I get timeouts for some npm packages:

```
warn Timed out on lookup for npm:buffer, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:isarray, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120
     Looking up npm:base64-js
     Looking up npm:ieee754
ok   Up to date - clean-css as npm:clean-css@^3.4.4 (3.4.8)

warn Timed out on lookup for npm:create-hmac, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:array-reduce, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:deep-is, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120
```

Second run
```
warn Timed out on lookup for npm:metawriter, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:has, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:string_decoder, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:vm-browserify, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120
     Looking up npm:reflect-metadata
     Looking up npm:function-bind

warn Timed out on lookup for npm:jsonparse, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120
ok   Up to date - angular-decorators as npm:angular-decorators@^1.1.0 (1.2.0)

warn Timed out on lookup for npm:pbkdf2, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:lexical-scope, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120

warn Timed out on lookup for npm:stream-combiner2, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120
     Looking up npm:astw

warn Timed out on lookup for npm:querystring, retrying (1).
     To increase the timeout run jspm config registries.npm.timeouts.lookup 120
```

So the timeouts are not consistent for some package but change everytime running `jspm update`.

When I set a higher timeout like `npm.timeouts.lookup 240` I get
```
warn Error on lookup for npm:jwt-decode
     Error: connect ETIMEDOUT 185.31.17.162:80
         at Object.exports._errnoException (util.js:874:11)
         at exports._exceptionWithHostPort (util.js:897:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

err  Error looking up npm:jwt-decode.
```

So somehow a manual setting of a timeout leads to aborting behavior. 

Doing a manual update of package(or parent package) that ran in a timeout seems to work.

**Comment by davelane** [comment]
Yes I get this too. When I downgrade to 0.16.15 it works again

**Comment by reppners** [comment]
I'm running v0.16.15

**Comment by guybedford** [comment]
It sounds like the timeout is just being shifted down to the network layer itself then?

This sounds like npm registry instability to me?

**Comment by mayerwin** [comment]
You can try to throttle the number of simultaneous connections with the following command (for example 3 maximum simultanous connections):

    npm set maxsockets 3

The CLI has been allowing this option since npm@3.8.0. The default is 50 simultaneous connections max. See [this link][1] for further reference.


  [1]: https://github.com/npm/npm/blob/5b4e3f3caff1f7ed30281b0b450de056a817bbc5/CHANGELOG.md#limit-concurrent-requests
