### ISSUE TITLE
Arithmetic bundle fails with "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by nestabur** [jspm/jspm-cli#1404]
When running the jspm bundle command
```
jspm bundle app/index.js - [npm:**/*] - [github:**/*]
```
I get the error
```
err  RangeError: Maximum call stack size exceeded
         at Promise._settlePromiseFromHandler (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:499:17)
         at Promise._settlePromise (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:546:18)
         at Promise._settlePromise0 (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:591:10)
         at Promise._settlePromises (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:674:18)
         at Promise._fulfill (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:615:18)
         at Promise._resolveCallback (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:416:57)
         at Promise._settlePromiseFromHandler (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:502:17)
         at Promise._settlePromise (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:546:18)
         at Promise._settlePromise0 (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:591:10)
         at Promise._settlePromises (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:674:18)
         at Promise._fulfill (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:615:18)
         at Promise._resolveCallback (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:416:57)
         at Promise._settlePromiseFromHandler (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:502:17)
         at Promise._settlePromise (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:546:18)
         at Promise._settlePromise0 (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:591:10)
         at Promise._settlePromises (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:674:18)
         at Promise._fulfill (C:\Users\neb\dev\channelsuite\modules\test\test-bug\static\node_modules\jspm\node_modules\bluebird\js\release\promise.js:615:18)
```

However these command works
```
jspm bundle app/index.js - [npm:**/*]
jspm bundle app/index.js - [github:**/*]
```

This happens since version 0.16.16 (version 0.16.15 works). Any ideas why? 

My package.json is:
```
{
  "jspm": {
    "dependencies": {
      "angular": "github:angular/bower-angular@1.4.7",
      "angular-material": "github:angular/bower-material@1.0.1",
      "angular-ui-router": "github:angular-ui/ui-router@0.2.15",
      "css": "github:systemjs/plugin-css@0.1.19",
      "json": "github:systemjs/plugin-json@0.1.0",
      "text": "github:systemjs/plugin-text@0.0.3"
    },
    "devDependencies": {
      "babel": "npm:babel-core@5.8.34",
      "babel-runtime": "npm:babel-runtime@5.8.34",
      "clean-css": "npm:clean-css@3.4.8",
      "core-js": "npm:core-js@1.1.4"
    }
  },
  "name": "jspm-bug",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "jspm": "^0.16.14"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}
```

**Comment by guybedford** [comment]
This isn't at all advisable as it effectively attempts to trace every single file, it could even be a valid stack limit, and not due to anything circular!

I've reopened https://github.com/systemjs/builder/issues/188 which previously traced optimization of this case to avoid touching the file system, I think that would be what you're after here (unless you'd expect `jspm bundle jspm_packages/**/*` to work!).

**Comment by nestabur** [comment]
Great thx! Keep in mind, this happens after upgrading to versions:
- SystemJS 0.19.7 
- SystemJS Builder 0.14.12
- Jspm CLI 0.16.16

**Comment by omnibrain** [comment]
For the record: I had the same error on node v8.7.0. Then I switched to node v6.5.0 and was able to bundle the application again.
