### ISSUE TITLE
Error: Unable to import "babel/external-helpers".

### ISSUE THREAD

**Issue by lookfirst** [jspm/jspm-cli#1420]
jspm 0.16.20

I manually include a copy of babel 5.x external-helpers.js at js/util/external-helpers.js

I'm now getting this error when trying to builder.buildStatic(). This worked fine with 0.16.19. =)

Any ideas? Do I no longer need this file? Is there a workaround?

```
[13:41:34] 'bundle-checkout' errored after 194 ms
[13:41:34] Error on translate for js/util/external-helpers.js at file:///Users/jon/checkout/hub/target/js/util/external-helpers.js
	Loading js/checkout/app.js
	Error: Unable to import "babel/external-helpers".
SystemJS Builder uses a System loader variant for tracing.
When writing plugins, use System.pluginLoader.import in place of System.import to load utility code.
  at SystemJSNodeLoader.loader.import (/Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:123:27)
  at /Users/jon/checkout/hub/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3439:36
  at run (/Users/jon/checkout/hub/node_modules/core-js/modules/es6.promise.js:104:47)
  at /Users/jon/checkout/hub/node_modules/core-js/modules/es6.promise.js:115:28
  at flush (/Users/jon/checkout/hub/node_modules/core-js/modules/$.microtask.js:19:5)
  at nextTickCallbackWith0Args (node.js:433:9)
  at process._tickCallback (node.js:362:13)
```

**Comment by guybedford** [comment]
Can you share the contents of `js/checkout/app.js`? Is this a custom plugin?

**Comment by guybedford** [comment]
@lookfirst I don't mean to rush you but I'm about to post a release. Any details to look into this now would be very much appreciated, otherwise can get this into the next one when it comes.

**Comment by lookfirst** [comment]
@guybedford `js/checkout/app.js` is my main app entry point. =( Is there something in there that you're looking for specifically?

The very first line of it is:

```
import 'js/util/external-helpers';
```

A long time ago, you told me that was the best way to get the external-helpers in there. =)

**Comment by lookfirst** [comment]
I'm here. =)

**Comment by guybedford** [comment]
Can you share the contents of `js/util/external-helpers.js`? What module format is that file? Is it loaded with a plugin?

**Comment by lookfirst** [comment]
It is a straight copy/paste from babel 5.x external-helpers.js...

```
/* */
"format global";
(function (global) {
	var babelHelpers = global.babelHelpers = {};

	babelHelpers.inherits = function (subClass, superClass) {
		if (typeof superClass !== "function" && superClass !== null) {
			throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);
		}

		subClass.prototype = Object.create(superClass && superClass.prototype, {
			constructor: {
				value: subClass,
				enumerable: false,
				writable: true,
				configurable: true
			}
		});
		if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;
	};

	babelHelpers.defaults = function (obj, defaults) {
		var keys = Object.getOwnPropertyNames(defaults);

		for (var i = 0; i < keys.length; i++) {
			var key = keys[i];
			var value = Object.getOwnPropertyDescriptor(defaults, key);

			if (value && value.configurable && obj[key] === undefined) {
				Object.defineProperty(obj, key, value);
			}
		}

		return obj;
	};

	babelHelpers.createClass = (function () {
		function defineProperties(target, props) {
			for (var i = 0; i < props.length; i++) {
				var descriptor = props[i];
				descriptor.enumerable = descriptor.enumerable || false;
				descriptor.configurable = true;
				if ("value" in descriptor) descriptor.writable = true;
				Object.defineProperty(target, descriptor.key, descriptor);
			}
		}

		return function (Constructor, protoProps, staticProps) {
			if (protoProps) defineProperties(Constructor.prototype, protoProps);
			if (staticProps) defineProperties(Constructor, staticProps);
			return Constructor;
		};
	})();

	babelHelpers.createDecoratedClass = (function () {
		function defineProperties(target, descriptors, initializers) {
			for (var i = 0; i < descriptors.length; i++) {
				var descriptor = descriptors[i];
				var decorators = descriptor.decorators;
				var key = descriptor.key;
				delete descriptor.key;
				delete descriptor.decorators;
				descriptor.enumerable = descriptor.enumerable || false;
				descriptor.configurable = true;
				if ("value" in descriptor || descriptor.initializer) descriptor.writable = true;

				if (decorators) {
					for (var f = 0; f < decorators.length; f++) {
						var decorator = decorators[f];

						if (typeof decorator === "function") {
							descriptor = decorator(target, key, descriptor) || descriptor;
						} else {
							throw new TypeError("The decorator for method " + descriptor.key + " is of the invalid type " + typeof decorator);
						}
					}

					if (descriptor.initializer !== undefined) {
						initializers[key] = descriptor;
						continue;
					}
				}

				Object.defineProperty(target, key, descriptor);
			}
		}

		return function (Constructor, protoProps, staticProps, protoInitializers, staticInitializers) {
			if (protoProps) defineProperties(Constructor.prototype, protoProps, protoInitializers);
			if (staticProps) defineProperties(Constructor, staticProps, staticInitializers);
			return Constructor;
		};
	})();

	babelHelpers.createDecoratedObject = function (descriptors) {
		var target = {};

		for (var i = 0; i < descriptors.length; i++) {
			var descriptor = descriptors[i];
			var decorators = descriptor.decorators;
			var key = descriptor.key;
			delete descriptor.key;
			delete descriptor.decorators;
			descriptor.enumerable = true;
			descriptor.configurable = true;
			if ("value" in descriptor || descriptor.initializer) descriptor.writable = true;

			if (decorators) {
				for (var f = 0; f < decorators.length; f++) {
					var decorator = decorators[f];

					if (typeof decorator === "function") {
						descriptor = decorator(target, key, descriptor) || descriptor;
					} else {
						throw new TypeError("The decorator for method " + descriptor.key + " is of the invalid type " + typeof decorator);
					}
				}
			}

			if (descriptor.initializer) {
				descriptor.value = descriptor.initializer.call(target);
			}

			Object.defineProperty(target, key, descriptor);
		}

		return target;
	};

	babelHelpers.defineDecoratedPropertyDescriptor = function (target, key, descriptors) {
		var _descriptor = descriptors[key];
		if (!_descriptor) return;
		var descriptor = {};

		for (var _key in _descriptor) descriptor[_key] = _descriptor[_key];

		descriptor.value = descriptor.initializer ? descriptor.initializer.call(target) : undefined;
		Object.defineProperty(target, key, descriptor);
	};

	babelHelpers.taggedTemplateLiteral = function (strings, raw) {
		return Object.freeze(Object.defineProperties(strings, {
			raw: {
				value: Object.freeze(raw)
			}
		}));
	};

	babelHelpers.taggedTemplateLiteralLoose = function (strings, raw) {
		strings.raw = raw;
		return strings;
	};

	babelHelpers.toArray = function (arr) {
		return Array.isArray(arr) ? arr : Array.from(arr);
	};

	babelHelpers.toConsumableArray = function (arr) {
		if (Array.isArray(arr)) {
			for (var i = 0, arr2 = Array(arr.length); i < arr.length; i++) arr2[i] = arr[i];

			return arr2;
		} else {
			return Array.from(arr);
		}
	};

	babelHelpers.slicedToArray = (function () {
		function sliceIterator(arr, i) {
			var _arr = [];
			var _n = true;
			var _d = false;
			var _e = undefined;

			try {
				for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) {
					_arr.push(_s.value);

					if (i && _arr.length === i) break;
				}
			} catch (err) {
				_d = true;
				_e = err;
			} finally {
				try {
					if (!_n && _i["return"]) _i["return"]();
				} finally {
					if (_d) throw _e;
				}
			}

			return _arr;
		}

		return function (arr, i) {
			if (Array.isArray(arr)) {
				return arr;
			} else if (Symbol.iterator in Object(arr)) {
				return sliceIterator(arr, i);
			} else {
				throw new TypeError("Invalid attempt to destructure non-iterable instance");
			}
		};
	})();

	babelHelpers.slicedToArrayLoose = function (arr, i) {
		if (Array.isArray(arr)) {
			return arr;
		} else if (Symbol.iterator in Object(arr)) {
			var _arr = [];

			for (var _iterator = arr[Symbol.iterator](), _step; !(_step = _iterator.next()).done;) {
				_arr.push(_step.value);

				if (i && _arr.length === i) break;
			}

			return _arr;
		} else {
			throw new TypeError("Invalid attempt to destructure non-iterable instance");
		}
	};

	babelHelpers.objectWithoutProperties = function (obj, keys) {
		var target = {};

		for (var i in obj) {
			if (keys.indexOf(i) >= 0) continue;
			if (!Object.prototype.hasOwnProperty.call(obj, i)) continue;
			target[i] = obj[i];
		}

		return target;
	};

	babelHelpers.hasOwn = Object.prototype.hasOwnProperty;
	babelHelpers.slice = Array.prototype.slice;
	babelHelpers.bind = Function.prototype.bind;

	babelHelpers.defineProperty = function (obj, key, value) {
		if (key in obj) {
			Object.defineProperty(obj, key, {
				value: value,
				enumerable: true,
				configurable: true,
				writable: true
			});
		} else {
			obj[key] = value;
		}

		return obj;
	};

	babelHelpers.asyncToGenerator = function (fn) {
		return function () {
			var gen = fn.apply(this, arguments);
			return new Promise(function (resolve, reject) {
				var callNext = step.bind(null, "next");
				var callThrow = step.bind(null, "throw");

				function step(key, arg) {
					try {
						var info = gen[key](arg);
						var value = info.value;
					} catch (error) {
						reject(error);
						return;
					}

					if (info.done) {
						resolve(value);
					} else {
						Promise.resolve(value).then(callNext, callThrow);
					}
				}

				callNext();
			});
		};
	};

	babelHelpers.interopExportWildcard = function (obj, defaults) {
		var newObj = defaults({}, obj);
		delete newObj["default"];
		return newObj;
	};

	babelHelpers.interopRequireWildcard = function (obj) {
		if (obj && obj.__esModule) {
			return obj;
		} else {
			var newObj = {};

			if (obj != null) {
				for (var key in obj) {
					if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key];
				}
			}

			newObj["default"] = obj;
			return newObj;
		}
	};

	babelHelpers.interopRequireDefault = function (obj) {
		return obj && obj.__esModule ? obj : {
			"default": obj
		};
	};

	babelHelpers._typeof = function (obj) {
		return obj && obj.constructor === Symbol ? "symbol" : typeof obj;
	};

	babelHelpers._extends = Object.assign || function (target) {
			for (var i = 1; i < arguments.length; i++) {
				var source = arguments[i];

				for (var key in source) {
					if (Object.prototype.hasOwnProperty.call(source, key)) {
						target[key] = source[key];
					}
				}
			}

			return target;
		};

	babelHelpers.get = function get(object, property, receiver) {
		if (object === null) object = Function.prototype;
		var desc = Object.getOwnPropertyDescriptor(object, property);

		if (desc === undefined) {
			var parent = Object.getPrototypeOf(object);

			if (parent === null) {
				return undefined;
			} else {
				return get(parent, property, receiver);
			}
		} else if ("value" in desc) {
			return desc.value;
		} else {
			var getter = desc.get;

			if (getter === undefined) {
				return undefined;
			}

			return getter.call(receiver);
		}
	};

	babelHelpers.set = function set(object, property, value, receiver) {
		var desc = Object.getOwnPropertyDescriptor(object, property);

		if (desc === undefined) {
			var parent = Object.getPrototypeOf(object);

			if (parent !== null) {
				set(parent, property, value, receiver);
			}
		} else if ("value" in desc && desc.writable) {
			desc.value = value;
		} else {
			var setter = desc.set;

			if (setter !== undefined) {
				setter.call(receiver, value);
			}
		}

		return value;
	};

	babelHelpers.newArrowCheck = function (innerThis, boundThis) {
		if (innerThis !== boundThis) {
			throw new TypeError("Cannot instantiate an arrow function");
		}
	};

	babelHelpers.classCallCheck = function (instance, Constructor) {
		if (!(instance instanceof Constructor)) {
			throw new TypeError("Cannot call a class as a function");
		}
	};

	babelHelpers.objectDestructuringEmpty = function (obj) {
		if (obj == null) throw new TypeError("Cannot destructure undefined");
	};

	babelHelpers.temporalUndefined = {};

	babelHelpers.temporalAssertDefined = function (val, name, undef) {
		if (val === undef) {
			throw new ReferenceError(name + " is not defined - temporal dead zone");
		}

		return true;
	};

	babelHelpers.selfGlobal = typeof global === "undefined" ? self : global;
	babelHelpers.typeofReactElement = typeof Symbol === "function" && Symbol["for"] && Symbol["for"]("react.element") || 60103;

	babelHelpers.defaultProps = function (defaultProps, props) {
		if (defaultProps) {
			for (var propName in defaultProps) {
				if (typeof props[propName] === "undefined") {
					props[propName] = defaultProps[propName];
				}
			}
		}

		return props;
	};

	babelHelpers._instanceof = function (left, right) {
		if (right != null && right[Symbol.hasInstance]) {
			return right[Symbol.hasInstance](left);
		} else {
			return left instanceof right;
		}
	};

	babelHelpers.interopRequire = function (obj) {
		return obj && obj.__esModule ? obj["default"] : obj;
	};
})(typeof global === "undefined" ? self : global);
```

**Comment by lookfirst** [comment]
babel-core/external-helpers.js

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/systemjs/builder/commit/1c76fddf26a9173985f716c93266a364973250db.

**Comment by lookfirst** [comment]
I have `{externalHelpers: true}` in the babel compile, which then means that I need this file.

**Comment by lookfirst** [comment]
@guybedford Thanks again. I'm trying to stay on top of your releases so that I can help you validate things.

**Comment by guybedford** [comment]
Sure, much appreciated for braving the edge, it helps a lot.

**Comment by guybedford** [comment]
Fixed in 0.16.21.

**Comment by kumargandhi** [comment]
Hi,

I am getting similar error but for typescript. PFB for the trace.
-----------------------------------------------------------------------------------------------------
Unhandled rejection Error: Unable to import "typescript".
SystemJS Builder uses a System loader variant for tracing.
When writing plugins, use System.pluginLoader.import in place of System.import to load utility code.
    at SystemJSNodeLoader.loader.import (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:123:27)
    at Object.exports.compile (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\compilers\esm.js:177:111)
    at compileLoad (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:107:57)
    at C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:230:14
    at tryCatcher (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\relea
se\promise.js:489:31)
    at Promise._settlePromise (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.
js:546:18)
    at Promise._settlePromiseCtx (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promi
se.js:583:10)
    at Async._drainQueue (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:130:
12)
    at Async._drainQueues (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:135
:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\blueb
ird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)


err  TypeError: Cannot read property 'toString' of undefined
         at C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:46:50
         at Array.forEach (native)
         at processOutputs (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:31:11)
         at createOutput (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:59:19)
         at exports.writeOutputs (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:145:16)
         at C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:550:14
         at tryCatcher (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:11:23)
         at Promise._settlePromiseFromHandler (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\
release\promise.js:489:31)
         at Promise._settlePromise (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\pro
mise.js:546:18)
         at Promise._settlePromise0 (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\pr
omise.js:591:10)
         at Promise._settlePromises (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\pr
omise.js:674:18)
         at Async._drainQueue (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js
:125:16)
         at Async._drainQueues (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.j
s:135:10)
         at Immediate.Async.drainQueues [as _onImmediate] (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\
bluebird\js\release\async.js:16:14)
         at processImmediate [as _immediateCallback] (timers.js:383:17)
---------------------------------------------------------------------------------------------------------------

**Comment by kumargandhi** [comment]
I used below command to bundle my app.
jspm bundle app/main.ts dist/main.js --inject

**Comment by guybedford** [comment]
@kumargandhi if you can share a test case that might help to understand the issue. Also make sure you are running the latest version.

**Comment by kumargandhi** [comment]
Hi @guybedford , Thank you for writing back.

I figured out the issue (may be i think), latest version was the problem. i did a fresh setup on jspm@0.16.19 and it worked. Now when i run the command 'jspm bundle app dist/main.js --inject' i do not get that error.

**Comment by mreiche** [comment]
Hi. I'm really desperate. I'm running a fresh jspm@0.16.42 installation and I still get this error
```Error: (SystemJS) babelHelpers is not defined``` when bundling my app with jspm.

Shall I copy the bable-helpers.js provided by @lookfirst into my code or what is the best way to get rid of this message?

I also recently added externalHelpers in my config.js
```
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "externalHelpers": true,
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  }
...```
