### ISSUE TITLE
jspm init error in @0.17.0-beta

### ISSUE THREAD

**Issue by yjj5855** [jspm/jspm-cli#1427]
localhost:angular2.jspm.com yangjiajun$ jspm -v
0.17.0-beta
Running against global jspm install.

localhost:angular2.jspm.com yangjiajun$ jspm init

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.

Package.json file does not exist, create it? [Yes]: Yes

err  TypeError: Error reading package.json
  File SyntaxError: Unexpected end of input.
    at ConfigFile.configError (/usr/local/lib/node_modules/jspm/lib/config/config-file.js:54:9)
    at ConfigFile.read (/usr/local/lib/node_modules/jspm/lib/config/config-file.js:446:17)
    at new ConfigFile (/usr/local/lib/node_modules/jspm/lib/config/config-file.js:46:8)
    at new PackageConfig (/usr/local/lib/node_modules/jspm/lib/config/package.js:45:15)
    at /usr/local/lib/node_modules/jspm/lib/config/index.js:95:20

**Comment by guybedford** [comment]
Many thanks for reporting.
