### ISSUE TITLE
Unhandled rejection Error: Unable to load registry %github%

### ISSUE THREAD

**Issue by nukuuk** [jspm/jspm-cli#1430]
Sorry if this is a really "dumb" question.  I have gulp-jspm bundling my ng2 boot.js file into a self-executing file.  It was working great, but now I am getting the following error: 

[15:18:23] Starting 'jspm_bundle'...
Unhandled rejection Error: Unable to load registry %github%
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at DestroyableTransform._transform (c:\my-ng2-project\node_modules\gulp-jspm\index.js:40:10)
    at DestroyableTransform.Transform._read (c:\my-ng2-project\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (c:\my-ng2-project\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (c:\my-ng2-project\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:335:12)
    at writeOrBuffer (c:\my-ng2-project\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:321:5)
    at DestroyableTransform.Writable.write (c:\my-ng2-project\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:248:11)
    at write (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
    at DestroyableTransform.Transform._read (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (c:\my-ng2-project\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24) 

Thanks for any help you can provide.

**Comment by gcnm-pgeil** [comment]
Looks like the `jspm-github` package isn't properly installed, which is responsible for handling - surprise! - installations of package hosted in a github repository. I don't know where this problem comes from, but since you use gulp-jspm and ahve the problem whereas things work fine when using jspm-cli alone, I'd suggest you to investigate towards how gulp-jspm installs/jspm.
