### ISSUE TITLE
jspm bundle failing.

### ISSUE THREAD

**Issue by kumargandhi** [jspm/jspm-cli#1453]
Hi,

PFB error i get when i try to run command >jspm bundle app dist/main.js --inject

Unhandled rejection Error: Unable to import "typescript".
SystemJS Builder uses a System loader variant for tracing.
When writing plugins, use System.pluginLoader.import in place of System.import to load utility code.
    at SystemJSNodeLoader.loader.import (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:123:27)
    at Object.exports.compile (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\compilers\esm.js:177:111)
    at compileLoad (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:107:57)
    at C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:230:14
    at tryCatcher (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\relea
se\promise.js:489:31)
    at Promise._settlePromise (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promise.
js:546:18)
    at Promise._settlePromiseCtx (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\promi
se.js:583:10)
    at Async._drainQueue (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:130:
12)
    at Async._drainQueues (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js:135
:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\blueb
ird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

err  TypeError: Cannot read property 'toString' of undefined
         at C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:46:50
         at Array.forEach (native)
         at processOutputs (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:31:11)
         at createOutput (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:59:19)
         at exports.writeOutputs (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\output.js:145:16)
         at C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:550:14
         at tryCatcher (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\util.js:11:23)
         at Promise._settlePromiseFromHandler (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\
release\promise.js:489:31)
         at Promise._settlePromise (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\pro
mise.js:546:18)
         at Promise._settlePromise0 (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\pr
omise.js:591:10)
         at Promise._settlePromises (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\pr
omise.js:674:18)
         at Async._drainQueue (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.js
:125:16)
         at Async._drainQueues (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\bluebird\js\release\async.j
s:135:10)
         at Immediate.Async.drainQueues [as _onImmediate] (C:\JSProjects\jspm_setupTest1\node_modules\jspm\node_modules\systemjs-builder\node_modules\
bluebird\js\release\async.js:16:14)
         at processImmediate [as _immediateCallback] (timers.js:383:17)

I did a fresh setup. App runs file but i try to bundle i get above error. Please check.
PFA for my code.

**Comment by kumargandhi** [comment]
PFA's.

**Comment by kumargandhi** [comment]
Rolled back to jspm@0.16.19 and it worked.

**Comment by guybedford** [comment]
Glad to hear that.

**Comment by andrenarchy** [comment]
I get the same error. Has this issue been addressed in the meantime? I'm wondering because it has been closed and using an older version doesn't look like a valid fix for the future. ;)

**Comment by guybedford** [comment]
@andrenarchy of course you are right, but this is a bug in plugin code running `System.import` during builds where `System` is not a valid instance of SystemJS to be doing importing with. Previously we would silently fail here. Which typescript transpilation process are you using? It would help to know how this is coming up.

**Comment by diegolaciar** [comment]
I have the same error , using "jspm": "0.16.25".
I'm using typescript build-in jspm. I mean, I'm not using a plugin to transpile typescript.
System.js version is v0.19.17

**Comment by diegolaciar** [comment]
Also  jspm@0.16.19  not working for me. When I run : `jspm bundle app/main dist/app.min.js --minify --skip-source-maps` and it fails silently. In fact, I had to kill the terminal.

**Comment by jakemoves** [comment]
Same issue here. I followed the sequence here: https://gist.github.com/robwormald/429e01c6d802767441ec#gistcomment-1691615

jspm v0.16.27
systemjs v0.19.19

No idea if it's relevant but there was an odd moment in my jspm install where I saw:
npm:typescript@^1.6.2 (1.8.0)
