### ISSUE TITLE
Issue with bundle

### ISSUE THREAD

**Issue by matthieu-ravey** [jspm/jspm-cli#1459]
I get the following error when trying to build a bundle:
```
Building the bundle tree for ./compiled/src/app/fr_FR/studio.js...

err  TypeError: Cannot read property 'map' of undefined
         at /redacted/node_modules/systemjs-builder/lib/trace.js:182:23
         at tryCatcher (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:11:23)
         at Promise._settlePromiseFromHandler (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:489:31)
         at Promise._settlePromise (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:546:18)
         at Promise._settlePromiseCtx (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:583:10)
         at Async._drainQueue (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:130:12)
         at Async._drainQueues (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:135:10)
         at Immediate.Async.drainQueues [as _onImmediate] (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:16:14)
         at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The exact command I used is: `./node_modules/.bin/jspm bundle ./compiled/src/app/fr_FR/studio.js`. I'm not sure what's happening ?

**Comment by guybedford** [comment]
@matthieu-ravey any chance you could share the replication, or edit `/redacted/node_modules/systemjs-builder/lib/trace.js:182` and add: `console.log(normalizedPkgName, canonical)` just before that line and share the output?

**Comment by matthieu-ravey** [comment]
@guybedford Here is the output with the console.log added:

```javascript
Building the bundle tree for ./compiled/src/app/fr_FR/studio.js...
file:///redacted/jspm_packages/github/dankogai/js-base64@2.1.9.js jspm_packages/github/dankogai/js-base64@2.1.9/#:buffer

err  TypeError: Cannot read property 'map' of undefined
         at /redacted/node_modules/systemjs-builder/lib/trace.js:183:23
         at tryCatcher (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:11:23)
         at Promise._settlePromiseFromHandler (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:489:31)
         at Promise._settlePromise (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:546:18)
         at Promise._settlePromiseCtx (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:583:10)
         at Async._drainQueue (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:130:12)
         at Async._drainQueues (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:135:10)
         at Immediate.Async.drainQueues [as _onImmediate] (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:16:14)
         at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I think it might be related to the issue I had here: https://github.com/systemjs/systemjs/issues/1017

**Comment by guybedford** [comment]
Thanks, I believe this should be fixed by https://github.com/systemjs/builder/commit/5bf7c6e018b36e132b5594bbac8c06a97536bbe3.

**Comment by matthieu-ravey** [comment]
@guybedford thanks. So next version of jspm will have the fix ?

**Comment by guybedford** [comment]
Yes exactly.

**Comment by guybedford** [comment]
Released in jspm@0.16.25.

**Comment by matthieu-ravey** [comment]
@guybedford Thanks I've tried it but I've got a new error:

```
err  Error: Unable to build dependency jspm_packages/github/dankogai/js-base64@2.1.9/#:buffer. normalize must be disabled for bundles containing conditionals.
         at /redacted/node_modules/systemjs-builder/lib/compile.js:94:13
         at /redacted/node_modules/systemjs-builder/lib/compile.js:83:21
         at Array.forEach (native)
         at remapLoadRecord (/redacted/node_modules/systemjs-builder/lib/compile.js:82:30)
         at compileLoad (/redacted/node_modules/systemjs-builder/lib/compile.js:88:20)
         at /redacted/node_modules/systemjs-builder/lib/compile.js:230:14
         at tryCatcher (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:11:23)
         at Promise._settlePromiseFromHandler (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:491:31)
         at Promise._settlePromise (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:548:18)
         at Promise._settlePromiseCtx (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:585:10)
         at Async._drainQueue (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:130:12)
         at Async._drainQueues (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:135:10)
         at Immediate.Async.drainQueues [as _onImmediate] (/redacted/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:16:14)
         at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by guybedford** [comment]
@matthieu-ravey right, you'll need to setup a custom build through the API at https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder, setting `normalize: false` as a build option. Alternatively run on the jspm 0.17 beta.
