### ISSUE TITLE
0.16.20 broke jspm bundle for me

### ISSUE THREAD

**Issue by teohhanhui** [jspm/jspm-cli#1469]
Relevant part of `config.js` here: https://github.com/jspm/jspm-cli/issues/1204#issuecomment-166861392

`jspm bundle` command here: https://github.com/jspm/jspm-cli/issues/1204#issuecomment-167743455

It was working fine (except for the minor problem as noted in #1204) up to 0.16.19

**Comment by teohhanhui** [comment]
```
     Building the bundle tree for app/**/* - [app/**/*] - config.json!systemjs-json...

err  Error: ENOENT: no such file or directory, open '/srv/tripviss-webadmin/public/app/app.css.js'
         at Error (native)
         at SystemJSNodeLoader.loader.fetch (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:168:20)
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:358:23
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:351:8
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:324:6
         at Trace.getLoadRecord (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:120:4)
         at Trace.getAllLoadRecords (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:496:15)
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:51:19
         at Trace.traceCanonical (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:49:4)
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:152:31
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:146:16
         at Array.reduce (native)
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:145:31
         at processImmediate [as _immediateCallback] (timers.js:374:17)
         at exports.traceExpression (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:143:24)
         at Builder.trace (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:372:10)
         at /srv/tripviss-webadmin/node_modules/jspm/lib/bundle.js:95:26
         at process._tickCallback (node.js:357:9)
         at Function.Module.runMain (module.js:477:11)
         at startup (node.js:118:18)
         at node.js:952:3
     From previous event:
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:422:13
     From previous event:
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:324:6
     From previous event:
         at Trace.getLoadRecord (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:120:4)
         at Trace.getAllLoadRecords (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:496:15)
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:51:19
     From previous event:
         at Trace.traceCanonical (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/trace.js:49:4)
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:152:31
     From previous event:
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:146:16
         at Array.reduce (native)
         at /srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:145:31
         at processImmediate [as _immediateCallback] (timers.js:374:17)
     From previous event:
         at exports.traceExpression (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/arithmetic.js:143:24)
         at Builder.trace (/srv/tripviss-webadmin/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:372:10)
         at /srv/tripviss-webadmin/node_modules/jspm/lib/bundle.js:95:26
         at process._tickCallback (node.js:357:9)
         at Function.Module.runMain (module.js:477:11)
         at startup (node.js:118:18)
         at node.js:952:3
```

**Comment by teohhanhui** [comment]
Perhaps it'd be good to add a test each time these are fixed to guard against regression?

**Comment by guybedford** [comment]
Try using `app/**/*.js - [app/**/*.js] - config.json!systemjs-json`. This is actually a regression due to the interaction between normalization changes and defaultJSExtensions, and is strictly correct in theory, despite being breaking.
