### ISSUE TITLE
TypeError: Cannot set property 'main' of undefined

### ISSUE THREAD

**Issue by prokher** [jspm/jspm-cli#1480]
Getting `TypeError: Cannot set property 'main' of undefined` during new project initialization with the following set of setting:

    jspm init
    Package.json file does not exist, create it? [Yes]: Yes
    Init Mode (Quick, Standard, Custom) [Quick]: Custom
    Prefix package.json properties under jspm? [Yes]: Yes
    Local package name (recommended, optional): 
    package.json directories.baseURL: 
    package.json directories.packages [jspm_packages]: assets/libs
    package.json configFiles.jspm [jspm.config.js]: jspm.config.js
    package.json configFiles.jspm:browser [jspm.browser.js]: jspm.browser.js
    System.config browser URL to assets/libs [/assets/libs]: /assets/libs
    System.config local package main [app.js]: app.js

    err  TypeError: Cannot set property 'main' of undefined
        at /usr/lib/node_modules/jspm/lib/config/index.js:615:27
        at tryCatcher (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/util.js:11:23)
        at Promise._settlePromiseFromHandler (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:491:31)
        at Promise._settlePromise (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:548:18)
        at Promise._settlePromise0 (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:593:10)
        at Promise._settlePromises (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:676:18)
        at Async._drainQueue (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:125:16)
        at Async._drainQueues (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:135:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:16:14)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

JSPM installed on Ubuntu with `npm install jspm@beta1`:

    > jspm --version
    0.17.0-beta.5
    Running against local jspm install.

**Comment by prokher** [comment]
> jspm --version
    0.17.0-beta.5
    Running against local jspm install.

**Comment by guybedford** [comment]
Thanks for reporting. Fixed in https://github.com/jspm/jspm-cli/commit/104652daf43840bc8f4eac0203dcbf7d96207a80 pending release.
