### ISSUE TITLE
jspm crashes (0.17.0-beta.5)

### ISSUE THREAD

**Issue by andrenarchy** [jspm/jspm-cli#1487]
With jspm 0.17.0-beta.5, `jspm init` fails with
```
$ jspm init

err  TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at objectToProperties (/tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:303:10)
    at /tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:306:15
    at Array.forEach (native)
    at objectToProperties (/tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:303:20)
    at /tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:306:15
    at Array.forEach (native)
    at objectToProperties (/tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:303:20)
    at /tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:306:15
    at Array.forEach (native)
    at objectToProperties (/tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:303:20)
    at ConfigFile.setObject (/tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:439:42)
    at ConfigFile.read (/tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:484:8)
    at new ConfigFile (/tmp/paperhive-frontend/node_modules/jspm/lib/config/config-file.js:46:8)
    at new PackageConfig (/tmp/paperhive-frontend/node_modules/jspm/lib/config/package.js:46:15)
    at /tmp/paperhive-frontend/node_modules/jspm/lib/config/index.js:92:20
```

It seems to depend on the surrounding directory. It works with a newly created project (`npm init`) but fails on [this one](https://github.com/paperhive/paperhive-frontend/tree/typescript). Any ideas?

**Comment by andrenarchy** [comment]
After added the config manually, I noticed that also `jspm install` crashes.

**Comment by andrenarchy** [comment]
Removing the `browserify-shim` (!) section from my `package.json` (see [here](https://github.com/paperhive/paperhive-frontend/blob/f1a8f82eb57088e9da7926bdd4a553e555b6e91d/package.json#L75)) solved it for me. I'm not closing this issue since this behavior is not expected.

**Comment by SomethingSexy** [comment]
I am having a similar issue when trying to install "github:twbs/bootstrap@4.0.0-alpha.2"

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/jspm/jspm-cli/commit/f746fe58093248f443baff49dc6c42d7ab66474a pending release hopefully tomorrow.
