### ISSUE TITLE
0.17 conflicts with .babelrc

### ISSUE THREAD

**Issue by bhavinkamani** [jspm/jspm-cli#1516]
I have installed `babel-cli` and `preset-react` via **npm** for my gulp tasks. 
I have also installed `plugin-babel` via **jspm** for browser based transpilation. When `.babelrc` is used, following command throws an error
```
jspm bundle app/main.jsx src/app/main.js
```
Following error is thrown
```
TypeError: Module /Volumes/DATA/Projects/temp/jspm_17/node_modules/babel-preset-es2015/index.js not declared as a dependency.
    at eval (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:3836:2256)
    at OptionManager.mergePresets (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:6643:30)
    at OptionManager.mergeOptions (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:6611:14)
    at OptionManager.addConfig (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:6571:12)
    at OptionManager.findConfigs (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:6677:18)
    at OptionManager.init (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:6714:14)
    at File.initOptions (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:7543:77)
    at new File (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:7481:24)
    at Pipeline.transform (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:3900:18)
    at eval (file:///Volumes/DATA/Projects/temp/jspm_17/src/jspm_packages/npm/systemjs-plugin-babel@0.0.2/plugin-babel.js:133:24)
```
If I remove `.babelrc` it works as expected. Am I missing something in my configuration or in my understanding of using npm based babel installation as well jspm based plugin-babel?

Here's the [gist](https://gist.github.com/bhavinkamani/9f176dcec03576c37244) of my config files.
My directory structure is 
```
jspm_17/
  .babelrc
  package.json
  node_modules/
  src/
    app/
    jspm_packages
    jspm.browser.js
    jspm.config.js
```

**Comment by guybedford** [comment]
I've added https://github.com/systemjs/plugin-babel/commit/3f372a6130bfeefb6c9b3c7595b91aba7c4d9f49 which should resolve this with the next release of the plugin.

**Comment by bhavinkamani** [comment]
Thanks @guybedford

**Comment by masaeedu** [comment]
@guybedford Does this work for the runtime version of babel as well?
