### ISSUE TITLE
making systemjs work on production without bundling and in-browser transpilation 

### ISSUE THREAD

**Issue by bhavinkamani** [jspm/jspm-cli#1527]
I am working on converting my app code to embrace http2 best practices. One of which is to move away from resource bundling. 

Is it currently possible to transpile individual js files to `systemjs` or any other compatible format on the server side and make them work on the browser without loading any transpiler-runtime? 

I tried a naive way with following [code](https://gist.github.com/bhavinkamani/7e4d72b2c8892783bd83). Though it does not throw any error, it shows a blank screen. Looks like my app code is not getting run as none of my vendor libraries are loaded. For the purpose of this experiment, I have temporarily bundled up vendor libraries.

**Comment by guybedford** [comment]
Note it is still best practice to bundle apps.

SystemJS builder provides a `builder.compile` method which can be used to pre-compile individual modules, that would be compatible with the SystemJS-CSP-Production loader variation.

**Comment by bhavinkamani** [comment]
Just trying to understand - given that http2 multiplexes requests and all of the modern browser supports http2, what advantage would bundling still carry?

Yes, I could compile individual modules through `builder.compile`. Would I still require `bundles` extension in my config files for compiled modules to work on my browser or would `depCache` alone should hold good. 

Also, should I be importing [`system-csp-production.js`](https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#csp-compatible-production) instead of `system.js` for the compiled module to work on the browser.

When I tried to generate `depCache` with following command 
```
jspm depcache jsp_17/main.prd.js
```
It throws following error
```
TypeError: modules.sort is not a function
    at logTree (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/jspm/lib/bundle.js:255:13)
    at /Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/jspm/lib/bundle.js:96:5
    at tryCatcher (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/promise.js:676:18)
    at Async._drainQueue (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Volumes/DATA/Bhavin/Projects/temp/jspm_17/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
I ran with compiled module file. Because with `jspm_17/main.js`, it throws ` SyntaxError: Unexpected token import`. Hence, I am assuming that it requires compiled file as an input.

Thanks once again for your time and support.

**Comment by guybedford** [comment]
From what I've heard I think the browser JS execution thread is not optimized for gradual execution being interrupted by the network, as you get in HTTP/2, as well as it is optimized for single synchronous script execution.

You can use systemJS normally but set `meta: {  'app/*': { format: 'register' } }` at least when using compile as that is the output format of compile.

It's definitely advisable to stick to bundles though.

**Comment by bhavinkamani** [comment]
Thanks @guybedford for the explanation.

Any clue on the depcache error or am I doing something wrong here?

**Comment by guybedford** [comment]
It's been fixed in the latest release.

**Comment by bhavinkamani** [comment]
thanks @guybedford. Will check that out..

**Comment by bhavinkamani** [comment]
its working well for me now. Thank you very much.
