### ISSUE TITLE
Fails to lookup github.com host

### ISSUE THREAD

**Issue by nicky-lenaers** [jspm/jspm-cli#1536]
I have installed ``jspm`` both globally and locally with version ``0.17.0-beta.7``

When running ``jspm install angular-ui-router`` I get:

```
$ jspm install angular-ui-router
     Updating registry cache...

err  Error on locate for jspm:angular-ui-router
Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all && git reset --hard origin/master"
fatal: unable to access 'https://github.com/jspm/registry.git/': Couldn't resolve host 'github.com'
error: Could not fetch origin

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

err  Error locating jspm:angular-ui-router.

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
This sounds like a connection issue? Was it perhaps related to the github ddos? Has it resolved now?

**Comment by nicky-lenaers** [comment]
I was not aware of the github ddos, but I noticed this issue over a 2 to 3 day span earlier this week. For now, I've resolved it using ``jspm install npm:angular-ui-router``, which worked fine.
