### ISSUE TITLE
Unable to install npm:dagre

### ISSUE THREAD

**Issue by jryans** [jspm/jspm-cli#1547]
When I try to install npm:dagre with the 0.17 branch, I get:

```
jryans@vin:~/projects/visual-parser (master)$ jspm -v
0.17.0-beta.7
Running against local jspm install.

jryans@vin:~/projects/visual-parser (master)$ jspm install npm:dagre
     Updating registry cache...
     Downloading npm:dagre@0.7.4

err  Error building package npm:dagre@0.7.4.
Error on processPackage
TypeError: req.substr is not a function
    at /Users/jryans/projects/visual-parser/node_modules/jspm-npm/lib/node-conversion.js:254:21
    at Array.forEach (native)
    at /Users/jryans/projects/visual-parser/node_modules/jspm-npm/lib/node-conversion.js:252:27
    at tryCatcher (/Users/jryans/projects/visual-parser/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jryans/projects/visual-parser/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/Users/jryans/projects/visual-parser/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromiseCtx (/Users/jryans/projects/visual-parser/node_modules/bluebird/js/release/promise.js:592:10)
    at Async._drainQueue (/Users/jryans/projects/visual-parser/node_modules/bluebird/js/release/async.js:130:12)
    at Async._drainQueues (/Users/jryans/projects/visual-parser/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jryans/projects/visual-parser/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

warn Installation changes not saved.
```

Here's the package.json at the time of running this command:

```
{
  "name": "visual-parser",
  "version": "0.0.0",
  "description": "Visual parser creation / inspection UI",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "jspm": "^0.17.0-beta.7"
  },
  "jspm": {
    "dependencies": {
      "co": "npm:co@^4.6.0",
      "codemirror": "npm:codemirror@^5.11.0",
      "d3": "npm:d3@^3.5.16",
      "graphlib": "npm:graphlib@^2.0.0"
    },
    "devDependencies": {},
    "peerDependencies": {
      "process": "github:jspm/nodelibs-process@^0.2.0-alpha"
    },
    "overrides": {
      "npm:d3@3.5.16": {
        "meta": {
          "d3.js": {
            "exports": "d3"
          }
        }
      }
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jryans/visual-parser.git"
  },
  "author": "J. Ryan Stinnett <jryans@gmail.com> (http://convolv.es/)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jryans/visual-parser/issues"
  },
  "homepage": "https://github.com/jryans/visual-parser#readme"
}
```

**Comment by jryans** [comment]
It looks like the issue is triggered by the minified file inside the package: https://github.com/cpettitt/dagre/blob/master/dist/dagre.min.js.

**Comment by AdamBurgess** [comment]
Error happens because the file tries to `require(10)` (i.e. a number, not a string), [line 4036 in dist/dagre.js](https://github.com/cpettitt/dagre/blob/master/dist/dagre.js#L4036) (error only occurs in the minified file, but easier to see in the non-minified)
so, a fix could be
```js
if (typeof req != 'string')
  return;
```
in jspm/npm/[node-conversion.js:252](https://github.com/jspm/npm/blob/0.17/lib/node-conversion.js#L252).

**Comment by jryans** [comment]
Thanks @AdamBurgess! I've filed that fix as PR on the npm repo just now.
