### ISSUE TITLE
window is not defined (0.16.29)

### ISSUE THREAD

**Issue by fknop** [jspm/jspm-cli#1560]
Hi !

I downloaded `bootstrap-less` on the JSPM registry to be able to change the path variable. I also downloaded the `less` plugin for systemjs. In my application I just include the main bootstrap less file and change the path variable.

When I try to bundle the app, I'm getting a `window is not defined`:

```
err  ReferenceError: window is not defined
        Evaluating file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/aaike/jspm-less-plugin@0.0.5/less.js
        Evaluating file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/aaike/jspm-less-plugin@0.0.5.js
        Error loading file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/aaike/jspm-less-plugin@0.0.5.js
         at Object.2../add-default-options (file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/distros/less@2.4.0/less.js:72:15)
         at s (file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/distros/less@2.4.0/less.js:13:576)
         at e (file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/distros/less@2.4.0/less.js:13:747)
         at eval (file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/distros/less@2.4.0/less.js:13:765)
         at execute (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3977:30)
         at linkDynamicModule (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3126:32)
         at linkDynamicModule (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3120:11)
         at getModule (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3094:9)
         at C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3130:16
         at require (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3740:29)
         at Object.eval (file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/aaike/jspm-less-plugin@0.0.5/less.js:1:88)
         at eval (file:///C:/Workspace/Framework/Application/Application.Web/Scripts/jspm_packages/github/aaike/jspm-less-plugin@0.0.5/less.js:79:4)
         at eval (native)
         at SystemJSNodeLoader.__exec (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:1395:16)
         at entry.execute (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3767:18)
         at linkDynamicModule (C:\Workspace\Framework\Application\Application.Web\node_modules\systemjs\dist\system.src.js:3126:32)
```

I saw an issue about that from 2 years ago. I don't know if this has been entirely fixed.
Is there any way to fix this by myself or this is a bug ?

Thanks.

**Comment by amenadiel** [comment]
I had the same problem and, in the end, I had to make a new plugin.

https://www.npmjs.com/package/systemjs-less-plugin

However this is not jspm's fault at all. If anything, it would be a problem with less.js, the main dependency of aalike's plugin.

**Comment by fknop** [comment]
@amenadiel Great ! Thank you ! I'll try that.

**Comment by fknop** [comment]
@ahmedshuhel It works great thanks! 

I'm closing this.

**Comment by guybedford** [comment]
@amenadiel nice work on the LESS plugin. Did you want to add it to the list at https://github.com/systemjs/systemjs#plugins and in the jspm registry at https://github.com/jspm/registry/blob/master/registry.json#L12? It would be fine to replace the existing less plugin there with yours as it sounds like it is more feature complete.
