### ISSUE TITLE
0.17.0-beta.8: linking is broken

### ISSUE THREAD

**Issue by nmschulte** [jspm/jspm-cli#1567]
It seems the latest beta build has broken linking.  This works fine with the previous beta (-beta.7).

```
$ jspm link ~/src/cesium npm:cesium@dev

err  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /home/nmschulte/temp2/node_modules/jspm/lib/link.js:125:22
    at Promise._execute (/home/nmschulte/temp2/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:468:18)
    at new Promise (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:77:14)
    at /home/nmschulte/temp2/node_modules/jspm/lib/link.js:124:12
    at tryCatcher (/home/nmschulte/temp2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:624:18)
    at Promise._resolveCallback (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:510:17)
    at Promise._settlePromise (/home/nmschulte/temp2/node_modules/bluebird/js/release/promise.js:555:18)

```

**Comment by guybedford** [comment]
Thanks, fixed in 0.17.0-beta.9.
