### ISSUE TITLE
With jspm 0.17 beta, meta/shim no longer supports array for "exports"

### ISSUE THREAD

**Issue by kwesterfeld** [jspm/jspm-cli#1579]
I am migrating my app to 0.17 beta, and have a bunch of overrides and could not load my application due to the following exception:

```
TypeError: p.split is not a function
    at readMemberExpression (https://localhost:8183/smc/jspm_packages/system.src.js:1450:18)
    at loader.set.loader.newModule.prepareGlobal (https://localhost:8183/smc/jspm_packages/system.src.js:3624:27)
    at entry.execute (https://localhost:8183/smc/jspm_packages/system.src.js:3534:16)
    at linkDynamicModule (https://localhost:8183/smc/jspm_packages/system.src.js:3132:32)
    at link (https://localhost:8183/smc/jspm_packages/system.src.js:2975:11)
    at Object.Promise.all.then.normalizedDeps.execute (https://localhost:8183/smc/jspm_packages/system.src.js:3312:13)
    at doDynamicExecute (https://localhost:8183/smc/jspm_packages/system.src.js:708:25)
    at link (https://localhost:8183/smc/jspm_packages/system.src.js:910:20)
    at doLink (https://localhost:8183/smc/jspm_packages/system.src.js:562:7)
    at updateLinkSetOnLoad (https://localhost:8183/smc/jspm_packages/system.src.js:610:18)
```

It turns out that my overrides sometimes declared exports as an array, which the new version does not support.

For example, the conversion of my 0.16 override left this in place:

```
      "npm:bootbox@4.4.0": {
        "main": "bootbox",
        "format": "global",
        "files": [
          "bootbox.js",
          "bower.json",
          "package.json",
          "LICENSE*",
          "README*"
        ],
        "meta": {
          "bootbox.js": {
            "exports": [
              "bootbox"
            ],
            "format": "global"
          }
        }
      },
```

changing exports to a single entry works, but seems like it should have been converted, handled or warned.

**Comment by kwesterfeld** [comment]
Moving to systemjs: https://github.com/systemjs/systemjs/issues/1133
