### ISSUE TITLE
Fail to load react-canvas using jspm 0.16.30

### ISSUE THREAD

**Issue by chauthai** [jspm/jspm-cli#1586]
I wasn't able to install [react-canvas](https://github.com/Flipboard/react-canvas) due to this error:

```javascript
Failed to load resource: the server responded with a status of 404 (Not Found)
system.js:4 Uncaught (in promise) Error: XHR error (404 Not Found) loading 
http://localhost:3000/jspm_packages/github/mjohnston/scroller@1.2.2.js
	Error loading http://localhost:3000/jspm_packages/github/mjohnston/scroller@1.2.2.js as "scroller" from http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0/lib/ListView.js
    at t (http://localhost:3000/src/jspm_packages/system.js:4:61)
    at g (http://localhost:3000/src/jspm_packages/system.js:4:9914)
    at http://localhost:3000/src/jspm_packages/system.js:4:8054
```
The `scroller` repo has a `package.json` and a `index.js` , but it is not used when being installed with jspm. Even directly installing it via `jspm install` did not recognize the `index.js`.  
Trying to fix this error with a `scroller@1.2.2.js` containing
```javascript
module.exports = require("github:mjohnston/scroller@1.2.2/src/Scroller.js");
```
resulted in this error:
```
system.src.js:4857 Uncaught (in promise) Error: Invalid string. Length must be a multiple of 4
	Evaluating http://localhost:3000/jspm_packages/npm/linebreak@0.3.0/src/linebreaker.js
	Evaluating http://localhost:3000/jspm_packages/npm/linebreak@0.3.0.js
	Evaluating http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0/lib/measureText.js
	Evaluating http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0/lib/CanvasUtils.js
	Evaluating http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0/lib/DrawingUtils.js
	Evaluating http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0/lib/RenderLayer.js
	Evaluating http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0/lib/Surface.js
	Evaluating http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0/lib/ReactCanvas.js
	Evaluating http://localhost:3000/jspm_packages/npm/react-canvas@1.1.0.js
	Error loading http://localhost:3000/index.js
    at t (http://localhost:3000/src/jspm_packages/system.js:4:61)
    at g (http://localhost:3000/src/jspm_packages/system.js:4:9747)
    at http://localhost:3000/src/jspm_packages/system.js:4:9289
    at b (http://localhost:3000/src/jspm_packages/system.js:4:11045)
    at x (http://localhost:3000/src/jspm_packages/system.js:4:11393)
    at p (http://localhost:3000/src/jspm_packages/system.js:4:9271)
    at h (http://localhost:3000/src/jspm_packages/system.js:4:9656)
    at http://localhost:3000/src/jspm_packages/system.js:4:7925t @ system.src.js:4857g @ system.src.js:4857(anonymous function) @ system.src.js:4857b @ system.src.js:4857x @ system.src.js:4857p @ system.src.js:4857h @ system.src.js:4857(anonymous function) @ system.src.js:4857
```
I'm lost on this one.
I'm using jspm@0.16.30, babel-core@5.8.24 and babel-runtime@5.8.24 and Chrome@49.0.2623.75

**Comment by guybedford** [comment]
Perhaps try using jspm 0.17 here? It has more comprehensive npm package support.

**Comment by guybedford** [comment]
I'm happy to help get this configured further if you'd like help with it on jspm 0.17.

**Comment by chauthai** [comment]
Thank you very much for the offer. I will try to upgrade in the next couple of days. Is it stable enough though?

**Comment by guybedford** [comment]
Yes jspm 0.17 is production-ready, it's only really delayed on documentation at this point.
