### ISSUE TITLE
Plugin github:systemjs/plugin-image@0.1.0/image.js does not support static builds

### ISSUE THREAD

**Issue by MSakamaki** [jspm/jspm-cli#1639]
I use version 0.17.0-beta.11

This code works unless bundle

```typescript
import atomGif from './img/atom.gif!image';

const imgDiv:HTMLDivElement = <HTMLDivElement>document.querySelector('#smpl_img');
imgDiv.appendChild(atomGif);
```

a error similar to the following will come out at bundle

```sh
$ jspm build app  dest/compile/browser/app.js
     Creating the single-file build for app...

err  TypeError: Plugin github:systemjs/plugin-image@0.1.0/image.js does not support static builds, compiling app/img/atom.gif!github:systemjs/plugin-image@0.1.0/image.js.
    at /Users/msakamaki/project/electron/electron-platform/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:209:13
    at Array.filter (native)
    at compileTree (/Users/msakamaki/project/electron/electron-platform/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:206:33)
    at /Users/msakamaki/project/electron/electron-platform/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:636:18

```

Do you need a special config when bundle the `github:systemjs/plugin-image@0.1.0/image.js` ?

Similar question seems to be in the  issues #438

**Comment by guybedford** [comment]
Yes this is not supported - it is only designed as a plugin to preload images when using the dynamic loader.

**Comment by MSakamaki** [comment]
Thank you for answering!
