### ISSUE TITLE
bundle --watch not resolving baseURL in 0.17.beta13

### ISSUE THREAD

**Issue by kwesterfeld** [jspm/jspm-cli#1714]
I realize @guybedford  intended this to be addressed with [bbaa11b](https://github.com/jspm/jspm-cli/commit/bbaa11b65d569ab48ceb68e49baa3d668cb7db89) a week ago, but I tried the latest jspm just released and I am still getting an issue:

```
err  Error: resolve_projpath: path .../smc/ui/app does not exist
    at BunserBuf.<anonymous> (.../smc/ui/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:90:13)
    at BunserBuf.emit (events.js:182:7)
    at BunserBuf.process (.../smc/ui/node_modules/bser/index.js:289:10)
    at .../smc/ui/node_modules/bser/index.js:244:12
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

The structure of my app is:

 -  baseURL: 'smc'

 - entrypoint of application is app/main under smc:   ie. smc/app/main.js

Build instruction:

```
jspm bundle 'app/main + systemjs-hot-reloader' smc/bundle/smc-bundle.js --inject --watch
```

How can I help resolve this?   I do have watchman in my path.  If I remove watchman, I get a different error:

```
err  Error: watch .../smc/ui/app ENOENT
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at NodeWatcher.watchdir (.../smc/ui/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (.../smc/ui/node_modules/sane/src/node_watcher.js:45:8)
    at sane (.../smc/ui/node_modules/sane/index.js:17:12)
    at buildWatch (.../smc/ui/node_modules/jspm/lib/bundle.js:297:17)
    at WatchmanWatcher.<anonymous> (.../smc/ui/node_modules/jspm/lib/bundle.js:305:5)
    at emitOne (events.js:90:13)
    at WatchmanWatcher.emit (events.js:182:7)
    at Client.<anonymous> (.../smc/ui/node_modules/sane/src/watchman_watcher.js:58:10)
    at emitOne (events.js:90:13)
    at Client.emit (events.js:182:7)
    at spawnError (.../smc/ui/node_modules/fb-watchman/index.js:170:10)
    at ChildProcess.<anonymous> (.../smc/ui/node_modules/fb-watchman/index.js:193:5)
    at emitOne (events.js:90:13)
```

To fix this, I add a symlink to "app" in the current directory, but I feel I should not have to do this.

**Comment by guybedford** [comment]
Where is the `ui` path configured here?

**Comment by kwesterfeld** [comment]
I'm not exactly sure what you mean, but I probably confused things a bit.  Sorry, I masked the directory structure here out of paranoia.  The "ui" in this case is the current directory, which is my ui project (contained within a larger java app), and contains `package.json`.  There is an app source folder called `smc` in that directory that contains `jspm.config.js`, etc., and contains `jspm_packages`.  The `baseURL` points to this dir.

The app config relevant here:

```
  packages: {
    "app": {
      "main": "main.js"
    },

```

**Comment by guybedford** [comment]
Is it definitely bundling ok without watching?

**Comment by kwesterfeld** [comment]
Yes I use build and bundle.

The project was migrated from a prior version of JSPM.  I think the
directories: lib is not present--would that matter?

**Comment by kwesterfeld** [comment]
@guybedford, it looks like that if I uninstall watchman this now
works....if I keep watchman it is still broken, so I was fooled into
thinking this was broken.

So, if you have watchman installed it seems there is still an issue.  Does
that help?

**Comment by guybedford** [comment]
@kwesterfeld the line numbers in the error there don't match up to the latest jspm version. Are you sure you're running the latest 0.13 beta?

**Comment by kwesterfeld** [comment]
OK, I'm having a hard time reproducing now....maybe it was a late-night snafu on my part. 

Thanks and sorry!
