### ISSUE TITLE
Build doesn't work on node 6

### ISSUE THREAD

**Issue by perrin4869** [jspm/jspm-cli#1764]
Regarding my project [react-stay-scrolled](https://github.com/perrin4869/react-stay-scrolled) again, script building fails on node 6, but works on node 5. Here is the error:

```bash
$ cd examples && npm install && jspm install
$ jspm build react-stay-scrolled-demo                                                                                                               
     Creating the single-file build for react-stay-scrolled-demo...

err  Error on translate for react-stay-scrolled-demo/main.jsx at file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/src/main.jsx
  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:6675:38
    at file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:6691:24
    at Array.map (native)
    at OptionManager.resolvePresets (file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:6680:22)
    at OptionManager.mergePresets (file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:6670:12)
    at OptionManager.mergeOptions (file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:6646:16)
    at OptionManager.init (file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:6762:12)
    at File.initOptions (file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:7585:77)
    at new File (file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:7516:24)
    at Pipeline.transform (file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/systemjs-babel-node.js:3924:18)
    at file:///home/perrin4869/projects/frontend/react/react-stay-scrolled/examples/jspm_packages/npm/systemjs-plugin-babel@0.0.8/plugin-babel.js:142:24
```

Using `jspm@0.17beta.14`.

**Comment by guybedford** [comment]
This is actually a Babel Node 6 bug, so will work when we update the version of Babel there. Created https://github.com/systemjs/plugin-babel/issues/34 to track.

**Comment by perrin4869** [comment]
got it, thanks!!

**Comment by tyrsius** [comment]
@guybedford I am on node 6, running jspm@0.17.0-beta.32 and I am encountering this bug

**Comment by tyrsius** [comment]
My issue was that updating the cli doesnt cause the `plugin-babel` depedency to get updated. Manually updating `plugin-babel` fixed the issue
