### ISSUE TITLE
jspm 0.17 beta 14: two rolled up files importing a non-rollup module (e.g. cjs) to same name fail

### ISSUE THREAD

**Issue by adamburgess** [jspm/jspm-cli#1765]
A bit of a cryptic title, but I'll try to explain.

I'll use the fs module in the examples, but any module/package that isn't rolled up will cause the same error.
to reproduce:
`npm init -y && npm install jspm@beta && jspm init -y && jspm install fs`
then create two files importing the modules differently:
`1.js: import fs from 'fs'; console.log(fs)`
`2.js: import * as fs from 'fs'; console.log(fs)`
(console.log is to stop rollup from omitting the imports)
then build them together: `jspm build 1.js + 2.js`
```
R:\Coding\Test\jspm-14>jspm build 1.js + 2.js
     Creating the single-file build for 1.js + 2.js...

err  TypeError: unknown: Duplicate declaration "fs"
> 1 | import fs, * as fs from 'fs';
    |                 ^
  2 |
  3 | console.log(fs);
  4 |
    at File.buildCodeFrameError (R:\Coding\Test\jspm-14\node_modules\babel-core\lib\transformation\file\index.js:407:15)
    at Scope.checkBlockScopedCollisions (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\scope\index.js:407:27)
    at Scope.<anonymous> (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\scope\index.js:548:18)
    at Scope.registerBinding (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\scope\index.js:567:8)
    at Scope.registerDeclaration (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\scope\index.js:492:14)
    at Object.Declaration (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\scope\index.js:109:36)
    at NodePath._call (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\path\context.js:63:18)
    at NodePath.call (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\path\context.js:47:17)
    at NodePath.visit (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\path\context.js:93:12)
    at TraversalContext.visitQueue (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\context.js:152:16)
    at TraversalContext.visitMultiple (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\context.js:110:17)
    at TraversalContext.visit (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\context.js:182:19)
    at Function.traverse.node (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\index.js:135:17)
    at Object.traverse [as default] (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\index.js:69:12)
    at NodePath.traverse (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\path\index.js:141:23)
    at Scope._crawl (R:\Coding\Test\jspm-14\node_modules\babel-traverse\lib\scope\index.js:773:10)
```

what's expected: (and what happens in jspm 13, afaik) rollup changes the second fs to be fs$2 or similar, avoiding the duplicate

**Comment by adamburgess** [comment]
Actually, it seems like jspm .17 beta13 had this problem too, but silently ignored it:
```js
setters: [function($__m) {
  m = $__m.default;
  m = $__m;
}],
```
(here, m was the name of the imported module from 2 files, but they should be unique and not overwritten)

**Comment by guybedford** [comment]
Do the `fs` requires definitely resolve to completely different final modules? If they do resolve to the same actual underlying module, then even though they have the same unnormalized name (`fs`) it is correct that the name binding is shared, so the silent failure in jspm beta 13 is actually correct.

This is due to Babel being stricter about duplicated imports, which should probably be handled as a Rollup bug though either way, since Rollup should be able to produce Babel-compatible output itself I guess.

Can you confirm if that sounds about right?

**Comment by adamburgess** [comment]
>so the silent failure in jspm beta 13 is actually correct.

if I have a cjs module 'test.js' like so:
```js
exports.__esModule = true;
exports.a = 1;
exports.default = 2;
```
then `import * as x from './test.js` should give me `{ a: 1, default: 2 }`, right?
then `import x from './test.js` should give me `2`?

**Comment by guybedford** [comment]
Ah of course it is a different binding between the import forms even if the
names match.

Could you post this as a Rollup bug? It's an Esm output from rollup causing
the issue exactly then.

**Comment by guybedford** [comment]
Posted https://github.com/rollup/rollup/issues/637.

**Comment by guybedford** [comment]
Closing to track at the rollup issue directly.
