### ISSUE TITLE
Error on translate...when bundling a project

### ISSUE THREAD

**Issue by GlurG** [jspm/jspm-cli#1772]
Upon issuing `jspm bundle boot.js -id` I get the following error:

```
err  Error on translate for boot.js at file:///C:/Projects/spoilstoolbox.com/client/boot.js
  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6645:38
    at file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6661:24
    at Array.map (native)
    at OptionManager.resolvePresets (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6650:22)
    at OptionManager.mergePresets (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6640:12)
    at OptionManager.mergeOptions (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6616:16)
    at OptionManager.init (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6732:12)
    at File.initOptions (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7375:77)
    at new File (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7319:24)
    at Pipeline.transform (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:3923:18)
    at file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/plugin-babel.js:154:24
```

The error happens in this function in systemjs-babel-node.js:

```
OptionManager.prototype.mergePresets = function mergePresets(presets, dirname) {
      var _this2 = this;
      this.resolvePresets(presets, dirname, function(presetOpts, presetLoc) {
        _this2.mergeOptions({
          options: presetOpts,
          alias: presetLoc,
          loc: presetLoc,
          dirname: _path2["default"].dirname(presetLoc) <--- Crash happens here
        });
      });
    };
```

The reason being that presetLoc is undefined. I'm guessing because my babel presets are not configured properly(?)

I have also tried bundling with the following script:

```
"use strict";

let B = require("jspm").Builder
let Builder = new B("client", "client/jspm.config.js");

Builder.config({
	"separateCSS": true
});

Builder.bundle("boot.js", "client/bundle.js", {
	"sourceMaps": false,
	"minify": false,
	"mangle": false
}).then(function() {
	console.log("Done");
});
```

But I only get a very similar error message:

```
Unhandled rejection Error on translate for boot.js at file:///C:/Projects/spoilstoolbox.com/client/boot.js
        TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6645:38
    at file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6661:24
    at Array.map (native)
    at OptionManager.resolvePresets (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6650:22)
    at OptionManager.mergePresets (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6640:12)
    at OptionManager.mergeOptions (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6616:16)
    at OptionManager.init (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6732:12)
    at File.initOptions (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7375:77)
    at new File (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7319:24)
    at Pipeline.transform (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:3923:18)
    at file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/npm/systemjs-plugin-babel@0.0.9/plugin-babel.js:154:24
```

boot.js contains:

`import $ from "jquery";`

Relevant part of of my jspm.config.js:

```
SystemJS.config({
  transpiler: "plugin-babel",
  babelOptions: {},
  meta: {
    "/js/*.js": {
      "loader": "plugin-babel"
    },

  map: {
    "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js",
    ...
  }
})

SystemJS.config({
  packageConfigPaths: [
    "github:*/*.json",
    "npm:@*/*.json",
    "npm:*.json"
  ],
  map: {
    "plugin-babel": "npm:systemjs-plugin-babel@0.0.9",
    "plugin-css": "github:systemjs/plugin-css@0.1.21",
    "plugin-text": "github:systemjs/plugin-text@0.0.7"
  }
});
```

jspm.browser.js:

```
SystemJS.config({
	baseURL: "/",
	paths: {
		"github:*": "jspm_packages/github/*",
		"npm:*": "jspm_packages/npm/*"
	}
});
```

Relevant parts of package.json:

```
"jspm": {
    "name": "spoilstoolbox.com",
    "directories": {
      "lib": "client",
      "packages": "client/jspm_packages",
      "baseURL": "client",
      "configFile": "client/jspm.config.js"
    },
    "dependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.9",
      "plugin-css": "github:systemjs/plugin-css@^0.1.21",
      "plugin-text": "github:systemjs/plugin-text@^0.0.7"
    },
    "devDependencies": {}
  }
```

My directory structure is as follows:

```
package.json
client/jspm.browser.js
client/jspm.config.js
client/jspm_packages/*
```

I'm running 0.17.0-beta.14

**Comment by guybedford** [comment]
This issue is Node 6 support for the Babel plugin. Tracking at https://github.com/systemjs/plugin-babel/issues/34. The workaround is to downgrade to Node 5.

**Comment by danwellman** [comment]
I suddenly started getting this issue today as well. Literally yesterday I was running Node 6.9.5 with JSPM 0.17.0-beta.41 and I was able to use the JSPM bundle command without any issues. 
Today I inadvertently updated to JSPM 0.17.0-beta.42 and suddenly I am seeing a very similar error:

> (SystemJS) Cannot set property 'open' of undefined
