### ISSUE TITLE
TypeError: unknown: Duplicate declaration "html" when making sfx build on 0.17 beta 14

### ISSUE THREAD

**Issue by jonricaurte** [jspm/jspm-cli#1824]
@johnsoftek wasn't sure if this was supposed to be in plugin-jade, but seemed more like systemjs sfx issue cause other plugins expose same kind of api

When using plugin-jade, everything works fine when bundling:
```
import { html } from './home.jade';
```

However, when making an sfx build, I get the following error:
```
err  TypeError: unknown: Duplicate declaration "html"
  39 | import { html } from './home.jade';
> 40 | import { html } from './registration_modal.jade';
```
I know sfx builds combine everything into one file, but bundling does too and the imports above are in two different files. Here is the bundle and build command I use: 

jspm bundle h2 public/h2_assets/build.js --skip-source-maps -wd
jspm build h2 public/h2_assets/build.js --skip-source-maps

I don't get any errors for the bundle command, but i get the above error for the sfx build.

**Comment by johnsoftek** [comment]
@jonricaurte Well, I don't see how it can be a problem with the plug-in.
 As a workaround in the short term, I suggest you use an alias e.g.
```
import { html  as home_html } from './home.jade';
```
and 
```
import { html as registration_modal_html } from './registration_modal.jade';
```

**Comment by jonricaurte** [comment]
@johnsoftek That's what I was thinking. @guybedford this seems like it could happen if two different libraries exported the same variable/method. Thoughts?

**Comment by guybedford** [comment]
Try adding `--skip-rollup` to the build command? This may be rollup related.

**Comment by jonricaurte** [comment]
That was it! It worked when I added --skip-rollup. Thanks @guybedford !

**Comment by guybedford** [comment]
@jonricaurte if you can share the export tree information that would help a lot to track down the Rollup bug.

**Comment by jonricaurte** [comment]
@guybedford is this what you wanted?

```
err  TypeError: unknown: Duplicate declaration "html"
  39 | import { html } from './home.jade';
> 40 | import { html } from './cart.jade';
     |          ^
  41 | import { html } from './chat_with_us.jade';
  42 | import { html } from './footer.jade';
  43 | import { html } from './popup/shipping_popup/shipping_popup.jade';
    at File.buildCodeFrameError (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/lib/transformation/file/index.js:467:15)
    at Scope.checkBlockScopedCollisions (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:490:27)
    at Scope.registerBinding (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:679:16)
    at Scope.registerDeclaration (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:599:14)
    at Object.Declaration (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:148:36)
    at NodePath._call (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:78:18)
    at NodePath.call (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:49:17)
    at NodePath.visit (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:108:12)
    at TraversalContext.visitQueue (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:174:16)
    at TraversalContext.visitMultiple (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:119:17)
    at TraversalContext.visit (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:217:19)
    at Function.traverse.node (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:171:17)
    at traverse (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:90:12)
    at NodePath.traverse (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:156:49)
    at Scope._crawl (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:950:10)
    at Scope.crawl (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:855:10)
    at Scope.init (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:850:32)
    at NodePath.setScope (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:154:30)
    at NodePath.setContext (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:169:8)
    at File._addAst (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/lib/transformation/file/index.js:552:8)
    at File.addAst (node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/lib/transformation/file/index.js:560:10)
```

**Comment by guybedford** [comment]
@jonricaurte that seems like the rollup output, but to get to that you would have had a structure like:

a.js
```javascript
import { html } from './home.jade';
import './b.js'
```

b.js
```javascript
import { html } from './card.jade';
```

etc that resulted in that Rollup output, which is how we might be able to replicate the bug on http://rollupjs.org to share.

**Comment by jonricaurte** [comment]
@guybedford That is correct. My html imports are in separate files like the following:

```
import FooterController from './footer.controller';
import { html } from './footer.jade';
import { chatWithUs } from 'h2/common/components';

var moduleName = 'components.footer';

angular.module(moduleName, [
  'ui.router',
  chatWithUs
])
  .component('appFooter', {
    template: html,
    controller: FooterController
  });

export default moduleName;
```

And then in a different file:

```
import ProductSearchController from './product_search.controller';
import { html } from './product_search.jade';
import { productSearch } from 'h2/common/services';

var moduleName = 'components.productSearch';

angular.module(moduleName, [
  'ui.router',
  'ui.bootstrap',
  productSearch
])
  .component('productSearch', {
    template: html,
    controller: ProductSearchController
  });

export default moduleName;
```

It is an angular app and each file represents a component and I import the html as the template.

**Comment by guybedford** [comment]
@jonricaurte thanks so much for the clear description. I was able to isolate it and create the Rollup bug - https://github.com/rollup/rollup/issues/659.

**Comment by jonricaurte** [comment]
@guybedford thanks for looking into it!
