### ISSUE TITLE
How do I use pug template engine with Express and jspm?

### ISSUE THREAD

**Issue by tomeraz** [jspm/jspm-cli#1828]
JSPM is awesome and looks like it would suite my setup perfectly.
I'm following the guide on http://jspm.io/0.17-beta-guide/universal-js-with-server-rendering.html

Express works fine without a template engine but when I try to use pug as a template engine I get the error below.
Don't know how to make express require pug properly.
Can you help?
Thanks!

### Code
```
import express from 'express';
import React from 'react';
import ReactDOMServer from 'react-dom/server.js';
import {HelloWorld} from 'jspm-react-component';

let app = express();
app.use(express.static('.'));
// Set view path
app.set('views', `./views`);
// set up ejs for templating
app.set('view engine', 'pug');
app.get('/', (req, res) => {
  let reactHtml = ReactDOMServer.renderToString(React.createElement(HelloWorld));
  // Output html rendered by react
  let templateData = {
    reactOutput: reactHtml
  }
  // render html template		
  res.render('index', templateData);
});

app.listen('8080', () => console.log('Listening on port 8080'));
```
### Error
```
Error: Module pug not declared as a dependency of file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/view.js
   at /Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3303:13
   at require (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3946:29)
   at new View (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/view.js:78:30)
   at EventEmitter.render (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/application.js:569:12)
   at ServerResponse.render (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/response.js:961:7)
   at file:///Users/tomer/code/playground/jspm-nisuy/server.js!transpiled:30:13
   at Layer.handle [as handle_request] (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/router/layer.js:95:5)
   at next (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/router/route.js:131:13)
   at Route.dispatch (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/router/layer.js:95:5)
   at file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/router/index.js:277:22
   at Function.process_params (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/router/index.js:330:12)
   at next (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/express@4.13.4/lib/router/index.js:271:10)
   at SendStream.error (file:///Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/serve-static@1.10.2/index.js:120:7)
   at emitOne (events.js:96:13)
   at SendStream.emit (events.js:188:7)
```

**Comment by OrKoN** [comment]
Hey, it looks like express requires pug without declaring it as a dependency - I would try to come up with an override for express which adds pug a dependency: http://jspm.io/0.17-beta-guide/overrides.html

**Comment by tomeraz** [comment]
Thanks!
Fixed using the following code in the overrides section in package.json:
```
      "npm:express@4.13.4": {
        "meta": {
          "lib/view.js": {
            "deps": [
              "pug"
            ],
            "cjsDeferDepsExecute": true
          }
        }
      },
```
