### ISSUE TITLE
jspm import throws an error

### ISSUE THREAD

**Issue by tomeraz** [jspm/jspm-cli#1832]
Hey @guybedford,
Using jspm@0.17.0-beta.14
When trying to import jspm inside a node module I get an error.
Is there anything I need to configure in order for this to run?
Thanks!
### Code
```
import jspm from 'jspm'
```
### Error
```
err  path.js:7
      throw new TypeError('Path must be a string. Received ' + inspect(path));
      ^
  TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.dirname (path.js:1324:5)
      at Object.<anonymous> (/Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/traceur.js:19:27)
      at /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/traceur.js:37:4
      at Object.exports.runInThisContext (vm.js:54:17)
      at SystemJSNodeLoader.__exec (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1514:12)
      at entry.execute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3979:18)
      at linkDynamicModule (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3292:32)
      at getModule (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3260:9)
      at /Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3296:16
      at require (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3946:29)
      at Object.<anonymous> (/Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/api.js:23:15)
      at /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/api.js:61:4
      at Object.exports.runInThisContext (vm.js:54:17)
      at SystemJSNodeLoader.__exec (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1514:12)
      at entry.execute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3979:18)
      at linkDynamicModule (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3292:32)
      at link (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3135:11)
      at Object.execute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:3473:13)
      at doDynamicExecute (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:798:25)
      at link (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1000:20)
      at doLink (/Users/tomer/code/playground/jspm-nisuy/node_modules/jspm/node_modules/systemjs/dist/system.src.js:652:7)
  Evaluating /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/traceur.js
  Evaluating /Users/tomer/code/playground/jspm-nisuy/jspm_packages/npm/traceur@0.0.105/src/node/api.js
  Error loading /Users/tomer/code/playground/jspm-nisuy/server.js
```

**Comment by tomeraz** [comment]
This error happens when requiring other modules as well.
Any solutions?

**Comment by guybedford** [comment]
How are you executing that `import jspm from 'jspm'` statement? Importing jspm from within itself is not supported.

**Comment by tomeraz** [comment]
I want to jspm bundle on the server and download on the client dynamically.
How should I do it?
I can spawn a child thread with jspm cli but I prefer to call it inside my script.

**Comment by guybedford** [comment]
You should rather use a Node entry point to run jspm - 

```javascript
var Builder = require('jspm').Builder;
// etc
```

running the above through `node`. Support directly in jspm would be the ideal in future though certainly! See https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder for more info, or the SystemJS builder project page.
