### ISSUE TITLE
[0.16.35] Application not working after systemjs@0.19.29 update

### ISSUE THREAD

**Issue by eberlitz** [jspm/jspm-cli#1865]
Hi, my application stop working after I updated the systemjs to 0.19.29. In the browser it gives me the following error:

```
Error: SyntaxError: Unexpected identifier
	Evaluating http://localhost:3000/app/app.ts
	Error loading http://localhost:3000/app/app.ts
```

When I try to run `jspm bundle app/app` the same error happens:

```
     Building the bundle tree for app/app...

err  Error on dependency parsing for app/app.ts at file:///C:/projetos/portal/Portais/Front/client/app/app.ts
        SyntaxError: Unexpected identifier
            at Object.exports.runInThisContext (vm.js:53:16)
            at SystemJSNodeLoader.loader.instantiate (C:\projetos\portal\Portais\Front\node_modules\jspm\node_modules\systemjs-builder\compilers\amd.js:292:30)
            at SystemJSNodeLoader.loader.instantiate (C:\projetos\portal\Portais\Front\node_modules\jspm\node_modules\systemjs-builder\compilers\esm.js:54:32)
            at C:\projetos\portal\Portais\Front\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:444:25
            at tryCatcher (C:\projetos\portal\Portais\Front\node_modules\bluebird\js\release\util.js:16:23)
            at Promise._settlePromiseFromHandler (C:\projetos\portal\Portais\Front\node_modules\bluebird\js\release\promise.js:502:31)
            at Promise._settlePromise (C:\projetos\portal\Portais\Front\node_modules\bluebird\js\release\promise.js:559:18)
            at Promise._settlePromise0 (C:\projetos\portal\Portais\Front\node_modules\bluebird\js\release\promise.js:604:10)
            at Promise._settlePromises (C:\projetos\portal\Portais\Front\node_modules\bluebird\js\release\promise.js:683:18)
            at Async._drainQueue (C:\projetos\portal\Portais\Front\node_modules\bluebird\js\release\async.js:138:16)
        Evaluating C:/projetos/portal/Portais/Front/client/app/app.ts
```

The given error doesn't show any valuable information for me. Really don't know whats is going on with this. Any lights? It was working fine on systemjs@0.19.24. There is a way to download a previous version of the systemjs with jspm??

**Comment by guybedford** [comment]
What transpiler configuration are you using here to run the TypeScript?

**Comment by eberlitz** [comment]
```
typescriptOptions: {
    "module": "system",
    "resolveTypings": true,
    "typeCheck": false,
    "experimentalDecorators": true,
    "target": "es5",
    "supportHtmlImports": true
  },
```

But I think I resolve the issue. I upgraded all my npm dependencies packages, and now it's working again. Probably it wasn't a JSPM problem at all. I'll try to find the problematic package version that causes this.

**Comment by eberlitz** [comment]
Just to state the solution. I had the same problem today with an old code that was with this configuration:

```
packages: {
    "app": {
      "main": "app",
      "defaultExtension": "ts",
      "modules": {
        "*.ts": {
          "loader": "ts"
        }
      }
    }
}
```

Changing "modules" to "meta" make this work again.

```
packages: {
    "app": {
      "main": "app",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    }
}
```
