### ISSUE TITLE
Bundling fails (0.17.0-beta.17)

### ISSUE THREAD

**Issue by panicbit** [jspm/jspm-cli#1882]
Bundling fails (even in blank projects using the default config) with the following error:

```
err  Error on translate for app/app.js at file:///<project>/src/app.js
  TypeError: file:///<project>/src/app.js: (0 , _getIterator3.default) is not a function
    at Parser.loadPlugins (file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:31925:58)
    at new Parser (file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:31894:29)
    at parse (file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:32462:12)
    at File.parse (file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:9404:36)
    at File.parseCode (file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:9476:22)
    at file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:9620:14
    at File.wrap (file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:9445:18)
    at Pipeline.transform (file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-node.js:9618:19)
    at file:///<project>/jspm_packages/npm/systemjs-plugin-babel@0.0.11/plugin-babel.js:166:24
```

**Comment by guybedford** [comment]
Perhaps try updating tot he latest `plugin-babel@0.0.12` and see if that helps?

**Comment by panicbit** [comment]
Jspm already seems to use that version:
```
     Downloading npm:systemjs-plugin-babel@0.0.12
ok   Installed dev dependency plugin-babel to npm:systemjs-plugin-babel@^0.0.12 (0.0.12)
```

**Comment by panicbit** [comment]
I tried downgrading `plugin-babel` and got the same errors down to version `0.0.9` where I got this instead:
```
err  Error on translate for foo/app.js at file:///tmp/foo/src/app.js
  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6645:38
    at file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6661:24
    at Array.map (native)
    at OptionManager.resolvePresets (file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6650:22)
    at OptionManager.mergePresets (file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6640:12)
    at OptionManager.mergeOptions (file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6616:16)
    at OptionManager.init (file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6732:12)
    at File.initOptions (file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7375:77)
    at new File (file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7319:24)
    at Pipeline.transform (file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:3923:18)
    at file:///tmp/foo/jspm_packages/npm/systemjs-plugin-babel@0.0.9/plugin-babel.js:154:24
```

**Comment by guybedford** [comment]
You definitely want to be using 0.0.12 here.

If you can share the configuration file and app file (is it just empty?) that gives the error that would help.

**Comment by panicbit** [comment]
The app is really just empty.
[The config.](http://pastebin.com/raw/tedmTDSY)
[Full transcript from project creation to error.] (http://pastebin.com/raw/8eY7vW2P)
[The complete project.](https://github.com/jspm/jspm-cli/files/299307/demo.zip)

**Comment by OrKoN** [comment]
@panicbit your demo projects worked for me just fine

```
cd demo
jspm install
jspm bundle src/app.js 
     Building the bundle tree for src/app.js...
     
       app/app.js
     
ok   Built into build.js with source maps, unminified.
```

```
jspm --version
0.17.0-beta.17
Running against global jspm install.
```

**Comment by panicbit** [comment]
That's weird. Maybe my node installation is broken in a weird way?
I already tried using a local installation of jspm in case my global installation is somehow messed up but no luck there.

**Comment by OrKoN** [comment]
@panicbit which node version do you use?

**Comment by panicbit** [comment]
`v6.2.0` on Arch Linux.

**Comment by OrKoN** [comment]
@panicbit still works for me fine :-(

**Comment by panicbit** [comment]
I'm going to nuke everything node related now and see if that helps.

**Comment by panicbit** [comment]
Sick. This issue is actually node related. Downgrading to node `6.1.0` makes everything work. Going to `6.2.0` breaks stuff again.
So... What do I do now? I'm not sure how to describe this issue to the node devs :confused:.

**Comment by OrKoN** [comment]
@panicbit it works for me on 6.2.0

**Comment by panicbit** [comment]
@OrKoN Which OS are you on?

**Comment by OrKoN** [comment]
@panicbit Ubuntu 16.04

Maybe npm is somehow related: mine is 3.9.5

**Comment by xiankai** [comment]
It works for me on Ubuntu 14.04 / node 6.2.0 / npm 3.8.9 as well

**Comment by panicbit** [comment]
Closing because it doesn't look like a jspm issue.

**Comment by revov** [comment]
For a workaround check the related nodejs issue: https://github.com/nodejs/node/issues/7163#issuecomment-237297482
