### ISSUE TITLE
Updating a package to JSPM 0.17 fails if it has linked depencencies

### ISSUE THREAD

**Issue by donald-50** [jspm/jspm-cli#1939]
I upgraded my (global) JSPM installation to 0.17.0-beta.22, then ran `jspm clean` to upgrade a package to the new package structure. It failed with the error message below.

On a hunch, I replaced some linked dependencies with the official versions, re-can `jspm clean`, and it worked. So it seems the upgrade logic has a problem with linked dependencies.

```
➜  AA git:(master) ✗ jspm clean

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.

jspm will now attempt to upgrade your project to the 0.17 configuration.
Are you sure you want to proceed? [Yes]: Yes

     Upgrading jspm 0.16 Node core libraries to jspm 0.17 universal implementations...

     Checking all overrides into the package.json file to ensure reproducibility independent of the jspm registry...

     Updating registry cache...
     Re-downloading all installed packages...

     Downloading npm:core-js@1.2.6
     Downloading npm:babel-runtime@5.8.38
     Downloading npm:babel-core@5.8.38

err  TypeError: registry.load(...).lookup is not a function
    at /Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/lib/package.js:128:84
    at tryCatcher (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

err  Error looking up jspm:B.
```

**Comment by guybedford** [comment]
It sounds like you had a bad npm install perhaps? `registry.load` would have loaded `jspm-npm` or `jspm-github`, which is expected to have a `lookup` function. If not, that's an invalid install of jspm itself.

**Comment by yunjia** [comment]
I think @donald-50  issue is not a bad install. I came across this recently, and it was the link done in 0.16 that caused the problem. The possible steps to reproduce this:

- Using jspm 0.16 to create link:
```
jspm link # in package-a, to install a global cache
jspm install --link jspm:package-a # in package-b
```
- Upgrade to 0.17
- Do `jspm install`
- `jspm link ../package-a # in package b`

The work around this is to remove  the `package-a` dep that's been added in `jspm.config.js` as a result of upgrade, and do the link again.
