### ISSUE TITLE
`jspm link` fails in 0.17

### ISSUE THREAD

**Issue by DanielSWolf** [jspm/jspm-cli#1942]
I migrated a package to 0.17.0-beta.22. Calling `jspm link` resulted in the following error:

```
jspm link

err  TypeError: Cannot read property 'indexOf' of undefined
    at Object.exports.link (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/lib/link.js:31:10)
    at /Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/cli.js:520:12
    at Object.<anonymous> (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/cli.js:599:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Liftoff.<anonymous> (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/jspm.js:35:5)
    at Liftoff.<anonymous> (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/liftoff/index.js:197:12)
    at Liftoff.<anonymous> (/Users/wolf/.nvm/versions/node/v6.0.0/lib/node_modules/jspm/node_modules/liftoff/index.js:164:7)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)```

**Comment by skorlir** [comment]
This sounds similar to the issue I just posted, #1943. Although the TypeError in that case is related to `lastIndexOf`, it's still eerily similar.

**Comment by skorlir** [comment]
This is probably a red herring, but the stack traces both clearly point to [this call to `core.cacheClear`](https://github.com/jspm/jspm-cli/blob/master/cli.js#L599). Seems odd, at least.

**Comment by guybedford** [comment]
Link expects an argument - `jspm link ../path/to/folder`. Definitely a better error here would be worthwhile.

**Comment by DanielSWolf** [comment]
Thanks! I didn't realise the link command-line syntax had changed. I agree that a syntax-related error message would be helpful.

**Comment by guybedford** [comment]
Thanks I've included a basic validation here.
