### ISSUE TITLE
Plugin 2 specified in "base" provided an invalid property of "default"

### ISSUE THREAD

**Issue by Vanuan** [jspm/jspm-cli#1947]
Got the following error after update to the latest beta (0.17 beta 22):

```
   Loading index.js
   Error: Plugin 2 specified in "base" provided an invalid property of "default"
     at Plugin.init (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7131:15)
     at Function.normalisePlugin (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6507:14)
     at file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6532:32
     at Array.map (native)
     at Function.normalisePlugins (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6511:22)
     at OptionManager.mergeOptions (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6592:38)
     at OptionManager.init (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:6732:12)
     at File.initOptions (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7375:77)
     at new File (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:7319:24)
     at Pipeline.transform (file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/systemjs-babel-node.js:3923:18)
     at file:///src/jspm_packages/npm/systemjs-plugin-babel@0.0.9/plugin-babel.js:154:24
```

**Comment by Vanuan** [comment]
Probably, it was because of relay plugin wrapper.
