### ISSUE TITLE
"defaultExtension": "ts" isn't being passed to plugin-typescript

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#1957]
```js
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "app/": "javascripts/app/",
    "admin/": "javascripts/admin/"
  },
  typescriptOptions: {
    "tsconfig": true,
    "typeCheck": "strict"
  },
  transpiler: "plugin-typescript",
  packages: {
    "app": {
      "main": "main.ts",
      "defaultExtension": "ts"
    },
    "admin": {
      "main": "admin.ts",
      "defaultExtension": "ts"
    }
  }
});
```

when trying to build the `jspm build app dist/app.js` package, the "imports" from my Typescript files aren't having the `defaultExtension` set.

```
err  Error: Error on fetch for javascripts/modules/base at file:///g:/www/marcos/javascripts/modules/base
  Loading admin/admin.ts
  ENOENT: no such file or directory, open 'g:\www\marcos\javascripts\modules\base'
    at Error (native)
    at SystemJSNodeLoader.loader.fetch (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:177:20)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:431:12
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:423:8
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:389:6
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
    at Trace.getLoadRecord (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:132:4)
    at Trace.getAllLoadRecords (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:590:15)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:601:21
    at Array.map (native)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:600:151
    at Trace.getAllLoadRecords (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:591:4)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:55:19
    at Trace.traceCanonical (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:53:4)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:243:35
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:232:20
    at Array.reduce (native)
    at processExpandedOperations (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:231:35)
    at exports.traceExpression (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:229:8)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:695:14
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:694:6
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
    at Builder.buildStatic (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:686:4)
    at Builder.buildStatic (C:\nodejs\node_modules\jspm\lib\bundle.js:110:48)
    at C:\nodejs\node_modules\jspm\lib\bundle.js:230:28
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3
From previous event:
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:521:13
From previous event:
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:389:6
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Trace.getLoadRecord (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:132:4)
    at Trace.getAllLoadRecords (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:590:15)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:601:21
    at Array.map (native)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:600:151
From previous event:
    at Trace.getAllLoadRecords (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:591:4)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:55:19
From previous event:
    at Trace.traceCanonical (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:53:4)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:243:35
From previous event:
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:232:20
    at Array.reduce (native)
    at processExpandedOperations (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:231:35)
From previous event:
    at exports.traceExpression (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:229:8)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:695:14
From previous event:
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:694:6
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Builder.buildStatic (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:686:4)
    at Builder.buildStatic (C:\nodejs\node_modules\jspm\lib\bundle.js:110:48)
    at C:\nodejs\node_modules\jspm\lib\bundle.js:230:28
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3
```

notice that the `  ENOENT: no such file or directory, open 'g:\www\marcos\javascripts\modules\base'` has no extension (should be `.ts`). 

using jspm 17-beta.22

EDIT: the start of the admin/admin.ts looks like this: 

```typescript
'use strict';

import '../modules/base';
import './main/dash';
import './main/login';
import './main/info';
```

**Comment by guybedford** [comment]
You mean the file is at `javascripts/admin.ts` here right?

**Comment by pocesar** [comment]
the initial file is at `javascripts/admin/admin.ts`, but the result of `jspm build admin/admin.ts admin.js` and `jspm build admin admin.js` is the same

**Comment by guybedford** [comment]
I think you'd need to add a `modules` package here that gives default extensions. Default extensions apply to the scope of the package of the module being resolved, regardless of where it is resolved from.

**Comment by pocesar** [comment]
oh, that's kind of a puzzling :zap: 
I added the `javascripts/` to the paths and packages, and now it works. thanks
