### ISSUE TITLE
Error parsing package.json

### ISSUE THREAD

**Issue by mikz** [jspm/jspm-cli#1994]
Looks like jspm can corrupt downloaded files in a way, that is not able to recover itself.

I suspect it happens in following scenario:

1. jspm install (jspm_packages is missing) starts downloading bunch of files
2. jspm opens files on fs to write to them from network (creating those files)
2. some of the files fails to load (network error)
3. jspm aborts downloading of all the files
4. empty .json package files are left on the filesystem
5. run jspm install again, crashes on `Error parsing package.json file .../jspm_packages/github/jspm/foo@0.2.0-alpha.json`
6. `jspm install -f` does not fix the issue and crashes the same
7.  Only working fix at this point is `rm -rf jspm_packages`

Related to https://github.com/jspm/jspm-cli/issues/1950

**Comment by mikz** [comment]
Looks like #1992 is a great way to reproduce this bug.

**Comment by guybedford** [comment]
The issue here seems to be that when we quit on an error, any in-progress downloads are abruptly aborted. 

An easy fix for this I think is just to use sync fs to write the package.json files so abruptly exiting the jspm process should at least not stop at these points.

Added https://github.com/jspm/jspm-cli/commit/24f32055b0d7432ffa3da271511024715fe6a653, pending further testing.

**Comment by mikz** [comment]
Thank you! Will try it out and report back.

**Comment by mikz** [comment]
Now I get this error for some reason (haven't shrinkwrapped before and it worked, this happens after shrinkwrap):

```

err  TypeError: createLoaderConfig(...).then is not a function
    at /Users/mikz/Developer/3scale/system/node_modules/jspm/lib/package.js:658:12
    at tryCatcher (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/mikz/Developer/3scale/system/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by guybedford** [comment]
@mikz that was corrected in https://github.com/jspm/jspm-cli/commit/25029603b2834d2c63e336ae6dca5850bd98c5cf I think.

**Comment by mikz** [comment]
@guybedford works quite well for us now. Haven't had any issues like this since. Thank you!
