### ISSUE TITLE
Dev bundles attempt to watch non-related node modules (>= 0.17.0-beta.23)

### ISSUE THREAD

**Issue by DorianGrey** [jspm/jspm-cli#2011]
I'm currently using five dev bundles in parallel (using [concurrently](https://github.com/kimmobrunfeldt/concurrently)), which are defined like:
```
"scripts": {
  "dev-bundle-unittest": "jspm bundle -wd unittest-helpers/**/*.ts - assets/javascripts/bundles/libs.js assets/javascripts/bundles/dev/unittest.helpers.js --log ok",
    "dev-bundle-common": "jspm bundle -wd --inline-source-maps --hires-source-maps --no-mangle --source-map-contents common/**/module.ts - assets/javascripts/bundles/libs.js assets/javascripts/bundles/common.js --log ok",
    "dev-bundle-public": "jspm bundle -wd --inline-source-maps --hires-source-maps --no-mangle --source-map-contents public/**/module.ts - common - assets/javascripts/bundles/libs.js assets/javascripts/bundles/public.js --log ok",
    "dev-bundle-private": "jspm bundle -wd --inline-source-maps --hires-source-maps --no-mangle --source-map-contents private/**/module.ts - common - assets/javascripts/bundles/libs.js assets/javascripts/bundles/private.js --log ok",
    "dev-bundle-admin": "jspm bundle -wd --inline-source-maps --hires-source-maps --no-mangle --source-map-contents admin/**/module.ts - private - common - assets/javascripts/bundles/libs.js assets/javascripts/bundles/admin.js --log ok",
    "dev": "npm run 'dev-bundle-libs' && gulp jspm:config && gulp dev:lite && concurrently -k -r 'gulp watch:lite' 'npm run dev-bundle-unittest' 'npm run dev-bundle-common' 'npm run dev-bundle-public' 'npm run dev-bundle-private' 'npm run dev-bundle-admin' 'npm run dev-test'"
}
```
Regularly, I'm using the `dev` task.
The modules referenced here are defined like:
```
"map": {
    "unittest-helpers": "assets/javascripts/modules/unittest-helpers",
    "common": "assets/javascripts/modules/common",
    "public": "assets/javascripts/modules/public",
    "private": "assets/javascripts/modules/private",
    "admin": "assets/javascripts/modules/admin",
}
```
This worked fine up to 0.17.0-beta.22. But trying to update to >= 0.17.0-beta.23, it seems that several additional files (from the `node_modules` directory) are added to the list of "to be watched" files that are not related to or required by the files bundles above.
Some examples:
```
err  Error: watch /home/linne/Projects/Cust/node_modules/through2 ENOSPC
    at exports._errnoException (util.js:1008:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at /home/linne/Projects/Cust/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:123:15)

err  Error: watch /home/linne/Projects/Cust/node_modules/uglify-js ENOSPC
    at exports._errnoException (util.js:1008:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at /home/linne/Projects/Cust/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:123:15)

err  Error: watch /home/linne/Projects/Cust/node_modules/http-proxy/lib ENOSPC
    at exports._errnoException (util.js:1008:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at /home/linne/Projects/Cust/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:123:15)

err  Error: watch /home/linne/Projects/Cust/node_modules/hooker/dist ENOSPC
    at exports._errnoException (util.js:1008:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/linne/Projects/Cust/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at /home/linne/Projects/Cust/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:123:15)
```
It would not be a problem to increase the file watcher limit, but I'm not sure why the above happens. The modules mentioned in the errors are referenced by the gulp task, and not by any of the files listed in the bundles.

**Comment by guybedford** [comment]
Thanks, let's track this in https://github.com/jspm/jspm-cli/issues/1999.

**Comment by guybedford** [comment]
The best thing for now is probably to use Watchman.

**Comment by guybedford** [comment]
Alternatively, if you're able to test the suggestion in https://github.com/jspm/jspm-cli/issues/1999#issuecomment-236884147 that would be really interesting to hear.

**Comment by DorianGrey** [comment]
Just for reference - reply can be found in the other issue's discussion: https://github.com/jspm/jspm-cli/issues/1999#issuecomment-236917053 .
