### ISSUE TITLE
0.16.43 breaks JSPM bundle (angular-ui-router) 

### ISSUE THREAD

**Issue by isonet** [jspm/jspm-cli#2046]
The following error occurs since version 0.16.43.

```
angular.js:13711 TypeError: Cannot read property '1' of undefined
    at Object.link (http://localhost:8080/windWeb/build/build.js:4503:38)
    at eval (http://localhost:8080/windWeb/build/build.js:6620:42)
    at invokeLinkFn (http://localhost:8080/windWeb/build/build.js:14982:15)
    at nodeLinkFn (http://localhost:8080/windWeb/build/build.js:14432:17)
    at compositeLinkFn (http://localhost:8080/windWeb/build/build.js:13759:19)
    at nodeLinkFn (http://localhost:8080/windWeb/build/build.js:14427:30)
    at compositeLinkFn (http://localhost:8080/windWeb/build/build.js:13759:19)
    at compositeLinkFn (http://localhost:8080/windWeb/build/build.js:13761:19)
    at nodeLinkFn (http://localhost:8080/windWeb/build/build.js:14427:30)
    at compositeLinkFn (http://localhost:8080/windWeb/build/build.js:13759:19) 
<a ui-sref="messages">(anonymous function) 
@ angular.js:13711(anonymous function) 
@ angular.js:10350invokeLinkFn 
@ angular.js:9819nodeLinkFn 
@ angular.js:9218compositeLinkFn 
@ angular.js:8513nodeLinkFn 
@ angular.js:9213compositeLinkFn 
@ angular.js:8513compositeLinkFn 
@ angular.js:8516nodeLinkFn 
@ angular.js:9213compositeLinkFn 
@ angular.js:8513nodeLinkFn 
@ angular.js:9213compositeLinkFn 
@ angular.js:8513nodeLinkFn 
@ angular.js:9213compositeLinkFn 
@ angular.js:8513publicLinkFn 
@ angular.js:8393(anonymous function) 
@ angular-ui-router.js:1944(anonymous function) 
@ angular.js:1243invokeLinkFn 
@ angular.js:9817nodeLinkFn 
@ angular.js:9218compositeLinkFn 
@ angular.js:8513publicLinkFn 
@ angular.js:8393lazyCompilation 
@ angular.js:8731updateView 
@ angular-ui-router.js:1879(anonymous function) 
@ angular-ui-router.js:1848$broadcast 
@ angular.js:17770(anonymous function) 
@ angular-ui-router.js:1592processQueue 
@ angular.js:16173(anonymous function) 
@ angular.js:16189$eval 
@ angular.js:17447$digest 
@ angular.js:17260$apply 
@ angular.js:17555done 
@ angular.js:11700completeRequest 
@ angular.js:11906requestLoaded 
@ angular.js:11839
```

The concerned code:
![bugjspm](https://cloud.githubusercontent.com/assets/21219305/17930226/6ecc40be-6a05-11e6-814b-db52cf2e282d.PNG)

0.16.42 works fine.

My command to install and bundle is:
`npm install && jspm install --production && jspm bundle app/bootstrap.js build/build.js`

This might be related to #2039 

I have no idea how to debug this, but if anyone has any idea, I'm happy to help and test :smile:

**Comment by guybedford** [comment]
Posted https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/issues/8.

**Comment by guybedford** [comment]
This should be fixed as of the latest release.
