### ISSUE TITLE
"Binding eval in strict mode" babel error when running jspm bundle

### ISSUE THREAD

**Issue by MattLishman** [jspm/jspm-cli#2049]
I am trying to import a file from "ace" which has been downloaded via jspm.
`jspm install ace`

*main.ts* 
```
import 'ace/worker-php';
```

This works when I just import normally using a `System.import` with no bundling.

*index.html*
```
<html>
    <head></head>
    <body>
        Test

        <script src="/jspm_packages/system.js"></script>
        <script src="config.js"></script>
        <script>
            System.import('main.js');
        </script>
    </body>
</html>
```

**However**, when I try to bundle, I get an error from babel.

`jspm bundle main.js main-build.js`

```     
Building the bundle tree for main.js...

       github:ajaxorg/ace-builds@1.2.5/ace.js
       github:ajaxorg/ace-builds@1.2.5/worker-php.js
       main.js


err  SyntaxError: jspm_packages/github/ajaxorg/ace-builds@1.2.5/worker-php.js: Binding eval in strict mode (2328:44)
  2326 |
       2327 |
> 2328 | PHP.Parser = function ( preprocessedTokens, eval ) {
       |                                             ^
       2329 |
       2330 |     var yybase = this.yybase,
       2331 |     yydefault = this.yydefault,
         at Parser.pp.raise (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:22:13)
         at Parser.pp.checkLVal (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/lval.js:239:14)
         at Parser.pp.parseFunctionBody (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:992:14)
         at Parser.pp.parseFunction (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:647:8)
         at Parser.pp.parseFunctionExpression (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:530:17)
         at Parser.pp.parseExprAtom (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:492:19)
         at Parser.pp.parseExprSubscripts (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:278:19)
         at Parser.pp.parseMaybeUnary (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:258:19)
         at Parser.pp.parseExprOps (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:188:19)
         at Parser.pp.parseMaybeConditional (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:165:19)
         at Parser.pp.parseMaybeAssign (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:128:19)
         at Parser.pp.parseMaybeAssign (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:151:23)
         at Parser.pp.parseExpression (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:92:19)
         at Parser.pp.parseStatement (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:163:19)
         at Parser.pp.parseBlockBody (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:529:21)
         at Parser.pp.parseBlock (/private/tmp/jspm_ace/node_modules/jspm/node_modules/systemjs-builder/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:510:8)

```

To me, this looks like babel is complaining that the file `jspm_packages/github/ajaxorg/ace-builds@1.2.5/worker-php.js` contains some poor code, overwriting eval. This might be true, but I would rather this didn't break the bundling.
Does the builder run babel on each file I try and import?

If my understanding is correct, is it possible to tell the bundler to **not** run a check on certain files?
If not, does anyone have any suggestions on how I can resolve this?

**Comment by guybedford** [comment]
I think we just need to turn off strict mode in Babel's parsing? I've created https://github.com/systemjs/builder/issues/679 to track.

**Comment by MattLishman** [comment]
Great, thanks for the fast reply.

**Comment by MattLishman** [comment]
When using the builder, where can I exclude files? I can't find it in the documentation.

Is there an excludes flag/property?

```
let builder = new jspm.Builder();

    jspm.setPackagePath('.');
    return builder.buildStatic(
        'app.js,
        'app.min.js,
        {
            excludes: ['ace/worker-php'],
        });
```

**Comment by guybedford** [comment]
It's `externals`.

**Comment by MattLishman** [comment]
Ah, that's why I couldn't find it! Thank you.
