### ISSUE TITLE
0.16.43 breaks JSPM bundle-sfx

### ISSUE THREAD

**Issue by HeinrichFilter** [jspm/jspm-cli#2052]
In our project, JSPM bundle-sfx started failing when we upgraded from 0.16.42 to 0.16.43:
```bash
$ npm install jspm@0.16.42
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
- babel-plugin-transform-cjs-system-require@0.1.1 node_modules/babel-plugin-transform-cjs-system-require
- babel-plugin-transform-cjs-system-wrapper@0.2.1 node_modules/babel-plugin-transform-cjs-system-wrapper
vrps-web@0.0.1 /Users/heinrichfilter/dev/filteris/vrps-web
└─┬ jspm@0.16.42
  ├── systemjs@0.19.36
  └── systemjs-builder@0.15.26

$ jspm bundle-sfx index.js
     Building the single-file sfx bundle for index.js...
ok   Built into src/static/js/build.js with source maps, unminified.

$ npm install jspm@0.16.43
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
vrps-web@0.0.1 /Users/heinrichfilter/dev/filteris/vrps-web
└─┬ jspm@0.16.43
  ├── systemjs@0.19.37
  └─┬ systemjs-builder@0.15.28
    └─┬ babel-plugin-transform-cjs-system-wrapper@0.0.3
      └── babel-plugin-transform-cjs-system-require@0.0.2

$ jspm bundle-sfx index.js
err  SyntaxError: jspm_packages/npm/sanitize-caja@0.1.3/sanitizer-bundle.js: Octal literal in strict mode (1057:15)
  1055 |       'quot': '"',
       1056 |       'apos': '\'',
> 1057 |       'nbsp': '\240'
       |                ^
       1058 |     };
       1059 |     var decimalEscapeRe = /^#(\d+)$/;
       1060 |     var hexEscapeRe = /^#x([0-9A-Fa-f]+)$/;
         at Parser.pp.raise (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/location.js:22:13)
         at Parser.readEscapedChar (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/tokenizer/index.js:826:22)
         at Parser.readString (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/tokenizer/index.js:719:23)
         at Parser.getTokenFromCode (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/tokenizer/index.js:520:23)
         at Parser.readToken (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/tokenizer/index.js:180:21)
         at Parser.nextToken (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/tokenizer/index.js:169:21)
         at Parser.next (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/tokenizer/index.js:81:12)
         at Parser.eat (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/tokenizer/index.js:90:14)
         at Parser.pp.parseObjPropValue (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:815:12)
         at Parser.pp.parseObj (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:789:10)
         at Parser.pp.parseExprAtom (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:489:19)
         at Parser.pp.parseExprSubscripts (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:278:19)
         at Parser.pp.parseMaybeUnary (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:258:19)
         at Parser.pp.parseExprOps (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:188:19)
         at Parser.pp.parseMaybeConditional (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:165:19)
         at Parser.pp.parseMaybeAssign (/Users/heinrichfilter/dev/filteris/vrps-web/node_modules/systemjs-builder/node_modules/babylon/lib/parser/expression.js:128:19)
```

I also tried 0.16.45 but still get the same error.

Please let me know if I you need more info.

**Comment by guybedford** [comment]
This looks like it could be a parsing issue with strict v non strict mode?

If so this may be fixed by https://github.com/systemjs/builder/issues/679 in the coming release.

**Comment by guybedford** [comment]
The latest release should have resolved this I believe, but let me know if you are still having problems.
