### ISSUE TITLE
Cannot transpile stateless functional components

### ISSUE THREAD

**Issue by xiankai** [jspm/jspm-cli#2053]
So I'm a bit late to this stateless functional component pattern, but when I gave it a try, I encountered the following error:

Version: 0.17.0-beta.28
app.js:
```
import React from 'react';

const Stateless = () => <span></span>;
export default Stateless;
```

Output:
```
err  Error on translate for app.js at file:///Users/kj/jspm-test/app.js
  SyntaxError: file:///Users/kj/jspm-test/app.js: Unexpected token (3:24)
  1 | import React from 'react';
  2 | 
> 3 | const Stateless = () => <span></span>;
    |                         ^
  4 | export default Stateless;
    at Parser.pp.raise (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:29406:15)
    at Parser.pp.unexpected (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:27314:10)
    at Parser.pp.parseExprAtom (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28833:14)
    at Parser.pp.parseExprSubscripts (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28633:21)
    at Parser.pp.parseMaybeUnary (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28615:21)
    at Parser.pp.parseExprOps (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28565:21)
    at Parser.pp.parseMaybeConditional (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28546:21)
    at Parser.pp.parseMaybeAssign (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28515:21)
    at Parser.pp.parseFunctionBody (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:29169:24)
    at Parser.pp.parseArrowExpression (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:29161:10)
    at Parser.pp.parseParenAndDistinguishExpression (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28929:19)
    at Parser.pp.parseExprAtom (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28801:21)
    at Parser.pp.parseExprSubscripts (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28633:21)
    at Parser.pp.parseMaybeUnary (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28615:21)
    at Parser.pp.parseExprOps (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28565:21)
    at Parser.pp.parseMaybeConditional (file:///Users/kj/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.13/systemjs-babel-node.js:28546:21)
```

**Comment by guybedford** [comment]
Follow http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html for getting jsx support enabled in Babel.
