### ISSUE TITLE
import pkg from '../package.json'; json file isn't parsed correctly

### ISSUE THREAD

**Issue by eliagrady** [jspm/jspm-cli#2066]
Intent: getting the 'version' property using an import statement.

In my main src/index.js file, there is an import statement for the package.json:
`import` pkg from '../package.json';`

When I run:
`jspm build src/index.js dist/module.js --format global --global-name MODULENAME --source-map-contents`

I get:

`Creating the single-file build for src/index.js...

err  SyntaxError: package.json: Unexpected token (2:8)
  1 | {
> 2 |   "name": "MODULENAME ",
    |         ^
  3 |   "description": "A MODULENAME",
  4 |   "version": "1.12.0",
  5 |   "license": "MIT",`
...

`at Parser.pp.raise (C:\dev\modules\DFP\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.unexpected (C:\dev\modules\DFP\node_modules\babylon\lib\parser\util.js:91:8)
    at Parser.pp.semicolon (C:\dev\modules\DFP\node_modules\babylon\lib\parser\util.js:76:38)
    at Parser.pp.parseExpressionStatement (C:\dev\modules\DFP\node_modules\babylon\lib\parser\statement.js:499:8)
    at Parser.pp.parseStatement (C:\dev\modules\DFP\node_modules\babylon\lib\parser\statement.js:168:17)
    at Parser.pp.parseBlockBody (C:\dev\modules\DFP\node_modules\babylon\lib\parser\statement.js:529:21)
    at Parser.pp.parseBlock (C:\dev\modules\DFP\node_modules\babylon\lib\parser\statement.js:510:8)
    at Parser.pp.parseStatement (C:\dev\modules\DFP\node_modules\babylon\lib\parser\statement.js:127:19)
    at Parser.pp.parseBlockBody (C:\dev\modules\DFP\node_modules\babylon\lib\parser\statement.js:529:21)
    at Parser.pp.parseTopLevel (C:\dev\modules\DFP\node_modules\babylon\lib\parser\statement.js:36:8)
    at Parser.parse (C:\dev\modules\DFP\node_modules\babylon\lib\parser\index.js:129:19)
    at parse (C:\dev\modules\DFP\node_modules\babylon\lib\index.js:47:47)
    at File.parse (C:\dev\modules\DFP\node_modules\babel-core\lib\transformation\file\index.js:517:34)
    at File.parseCode (C:\dev\modules\DFP\node_modules\babel-core\lib\transformation\file\index.js:603:20)
    at C:\dev\modules\DFP\node_modules\babel-core\lib\transformation\pipeline.js:49:12
    at File.wrap (C:\dev\modules\DFP\node_modules\babel-core\lib\transformation\file\index.js:563:16)`

I tried using the json plugin - but it didn't work out.
Any ideas as to why importing a json file doesn't work?

**Comment by guybedford** [comment]
Try configuring json to load correctly with:

```javascript
System.config({
  meta: {
    '*.json': { format: 'json' }
  }
});
```

**Comment by eliagrady** [comment]
It changed the error to: 
`
     Creating the single-file build for src/index.js...

err  Error: Mismatched sourcesContent for: src\index.js
    at C:\dev\modules\DFP\node_modules\systemjs-builder\lib\sourcemaps.js:54:21
    at Array.forEach (native)
    at exports.concatenateSourceMaps (C:\dev\modules\DFP\node_modules\systemjs-builder\lib\sourcemaps.js:42:19)
    at createOutput (C:\dev\modules\DFP\node_modules\systemjs-builder\lib\output.js:63:21)
    at exports.writeOutputs (C:\dev\modules\DFP\node_modules\systemjs-builder\lib\output.js:150:16)
    at C:\dev\modules\DFP\node_modules\systemjs-builder\lib\builder.js:769:14
    at tryCatcher (C:\dev\modules\DFP\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\modules\DFP\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\dev\modules\DFP\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\dev\modules\DFP\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\dev\modules\DFP\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\dev\modules\DFP\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\dev\modules\DFP\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\dev\modules\DFP\node_modules\bluebird\js\release\async.js:17:
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)`

Was able to build after changing:
`jspm build src/index.js dist/module.js --format global --global-name DFP --source-map-contents`
to:
`jspm build src/index.js dist/module.js --format global --global-name DFP`
