### ISSUE TITLE
jspm install typeerror

### ISSUE THREAD

**Issue by jsiegmund** [jspm/jspm-cli#2070]
Getting the following after executing jspm install on some sources I cloned from github: 

`err  TypeError: Path must be a string. Received undefined
         at assertPath (path.js:8:11)
         at Object.win32.resolve (path.js:130:5)
         at Package.getPath (E:\Sources\github\AngularJS2ElectronOffice365App\node_modules\jspm\lib\config\package-name.js:82:15)
         at Object.exports.download (E:\Sources\github\AngularJS2ElectronOffice365App\node_modules\jspm\lib\package.js:435:25)
         at E:\Sources\github\AngularJS2ElectronOffice365App\node_modules\jspm\lib\install.js:321:18
         at lib$rsvp$$internal$$tryCatch (E:\Sources\github\AngularJS2ElectronOffice365App\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:1036:16)
         at lib$rsvp$$internal$$invokeCallback (E:\Sources\github\AngularJS2ElectronOffice365App\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:1048:17)
         at E:\Sources\github\AngularJS2ElectronOffice365App\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:331:11
         at lib$rsvp$asap$$flush (E:\Sources\github\AngularJS2ElectronOffice365App\node_modules\jspm\node_modules\rsvp\dist\rsvp.js:1198:9)
         at nextTickCallbackWith0Args (node.js:420:9)
         at process._tickCallback (node.js:349:13)

warn Installation changes not saved.`

Need some help finding out what is wrong here, greatly appreciated!

**Comment by guybedford** [comment]
Odd, if you're able to share a replication at all here that would help.

**Comment by jsiegmund** [comment]
Sure, I just tried the same on another machine and that gave me the exact same issue. The repo is this one: https://github.com/maliksahil/AngularJS2ElectronOffice365App. I am running Windows 10, this problem arises after simply cloning the repo and doing a 'npm install && jspm install' (only jspm install gives the same error). Let me know if you need anything more specific.

**Comment by guybedford** [comment]
Thanks, I added a fix in https://github.com/jspm/jspm-cli/commit/80728a93077a841a718fc1d7a2535fccc44168a0.

We do actually have this in jspm 0.17, but it's worth including here for 0.16 too.

**Comment by guybedford** [comment]
Released in the latest jspm 0.16.
