### ISSUE TITLE
'with' in strict mode  error JSPM 0.17 latest

### ISSUE THREAD

**Issue by devmondo** [jspm/jspm-cli#2076]
hi, trying to create static build  i get the below error for this package [Domino](https://www.npmjs.com/package/domino)

```
err  SyntaxError: jspm_packages/npm/domino@1.0.25/lib/sloppy.js: 'with' in strict mode (10:4)
   8 |   Window_run: function _run(code, file) {
   9 |     if (file) code += '\n//@ sourceURL=' + file;
> 10 |     with(this) eval(code);
     |     ^
  11 |   },
  12 |   EventHandlerBuilder_build: function build() {
  13 |     try {
    at Parser.pp.raise (C:\projects\jspm-test\node_modules\babylon\lib\parser\location.js:22:13)
    at Parser.pp.parseWithStatement (C:\projects\jspm-test\node_modules\babylon\lib\parser\statement.js:439:31)
    at Parser.pp.parseStatement (C:\projects\jspm-test\node_modules\babylon\lib\parser\statement.js:125:19)
    at Parser.pp.parseBlockBody (C:\projects\jspm-test\node_modules\babylon\lib\parser\statement.js:529:21)
    at Parser.pp.parseBlock (C:\projects\jspm-test\node_modules\babylon\lib\parser\statement.js:510:8)
    at Parser.pp.parseFunctionBody (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:923:22)
    at Parser.pp.parseFunction (C:\projects\jspm-test\node_modules\babylon\lib\parser\statement.js:647:8)
    at Parser.pp.parseFunctionExpression (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:530:17)
    at Parser.pp.parseExprAtom (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:492:19)
    at Parser.pp.parseExprSubscripts (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:278:19)
    at Parser.pp.parseMaybeUnary (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:258:19)
    at Parser.pp.parseExprOps (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:188:19)
    at Parser.pp.parseMaybeConditional (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:165:19)
    at Parser.pp.parseMaybeAssign (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:128:19)
    at Parser.pp.parseObjPropValue (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:816:99)
    at Parser.pp.parseObj (C:\projects\jspm-test\node_modules\babylon\lib\parser\expression.js:789:10)
```

**Comment by guybedford** [comment]
Yes this is a bug... updating to SystemJS Builder 0.15.31 as we will be providing in the next jspm release should fix this though.

**Comment by devmondo** [comment]
@guybedford Awesome man

**Comment by guybedford** [comment]
This upgrade has finally been released.
