### ISSUE TITLE
can no longer bundle angular 2.0 for release... HELP!

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#2079]
can no longer bundle angular 2.0 for release...
up to version rc.5 all was well.
now with angular 2.0 uglify will fail with an error of:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (C:\msweb\studioDashboard\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at wrapper (C:\msweb\studioDashboard\node_modules\lodash\_createHybrid.js:87:15)
    at trycatch (C:\msweb\studioDashboard\node_modules\gulp-uglify\minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (C:\msweb\studioDashboard\node_modules\gulp-uglify\minifier.js:76:19)
    at DestroyableTransform.Transform._read (C:\msweb\studioDashboard\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\msweb\studioDashboard\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\msweb\studioDashboard\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\msweb\studioDashboard\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (C:\msweb\studioDashboard\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at write (C:\msweb\studioDashboard\node_modules\readable-stream\lib\_stream_readable.js:623:24)
```

so I tried removing it all together (no uglify) and will fail with the attached image

![capture](https://cloud.githubusercontent.com/assets/5090936/18576134/7f572f44-7b93-11e6-86af-363e7fd22ba2.PNG)

I also tried adding --minify to my command as in:

```
gulp.task("x_bundle",
    shell.task(["jspm bundle src/App.js " + paths.dist + "/" + paths.targetJS + ' --minify'])
);
```

and got diff errors:

```
[22:31:09] Starting 'x_bundle'...
     Building the bundle tree for src/App.js...

err  Error: SyntaxError: Unexpected token: string (./src/platform-browser-dynamic) (line: 2345, col: 16, pos: 104806)

Error
    at new JS_Parse_Error (eval at <anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\jspm\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\jspm\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (C:\Users\root\AppData\Roaming\npm\node_modules\jspm\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2092:9)
```

which leads me to believe some how ng2 changed it's es6 exportation or something, and so we can no longer bundle targeting es5

I hope someone can point me to the right direction as I have been trying to solve this for 5 hours now and just about to give up and go to webpack... which I don't want to do, but I have to get this build into production asap! HELP :(

tx

Sean

**Comment by born2net** [comment]
after spending 2 days trying to fix jspm with bundling I was finally able to fix it, in jspm you need to remove from packages the statement of :
```
packages: {
 "@angular/common": {
            "main": "index.js",
            "defaultExtension": "js"
        },
        "@angular/compiler": {
            "main": "index.js",
            "defaultExtension": "js"
        },
        "@angular/core": {
            "main": "index.js",
            "defaultExtension": "js"
        },
        "@angular/http": {
            "main": "index.js",
            "defaultExtension": "js"
        },
        "@angular/platform-browser": {
            "main": "index.js",
            "defaultExtension": "js"
        },
        "@angular/platform-browser-dynamic": {
            "main": "index.js",
            "defaultExtension": "js"
        },
        "@angular/router": {
            "main": "index.js",
            "defaultExtension": "js"
        }
		...
```
I have no idea what changed in ng2 prior to rc.6 that would require this removel, but here you go, this fixes it and now I can FINALLY run:

```
jspm bundle app/main ./dist/index.js --minify --skip-source-maps
```

hopes it helps someone 

Sean
