### ISSUE TITLE
CJS format fails to load for postmate library with jspm

### ISSUE THREAD

**Issue by gajewsk2** [jspm/jspm-cli#2083]
I'm using jspm .0.16.30 and trying to include postmate: https://github.com/dollarshaveclub/postmate

However, I get on package import: 
`system.src.js:41 Uncaught (in promise) Error: Unexpected token =
	Evaluating http://localhost:8000/static/jspm_packages/github/dollarshaveclub/postmate@1.0.2/src/postmate.js
	Evaluating http://localhost:8000/static/jspm_packages/github/dollarshaveclub/postmate@1.0.2.js
	Error loading http://localhost:8000/static/scripts/cms/index.es6.js
    at addToError (http://localhost:8000/static/jspm_packages/system.src.js:41:18)
    at linkSetFailed (http://localhost:8000/static/jspm_packages/system.src.js:628:15)
    at http://localhost:8000/static/jspm_packages/system.src.js:563:9
    at doDynamicExecute (http://localhost:8000/static/jspm_packages/system.src.js:711:7)
    at link (http://localhost:8000/static/jspm_packages/system.src.js:910:20)
    at doLink (http://localhost:8000/static/jspm_packages/system.src.js:562:7)
    at updateLinkSetOnLoad (http://localhost:8000/static/jspm_packages/system.src.js:610:18)
    at http://localhost:8000/static/jspm_packages/system.src.js:422:11addToError @ system.src.js:41linkSetFailed @ system.src.js:628(anonymous function) @ system.src.js:563doDynamicExecute @ system.src.js:711link @ system.src.js:910doLink @ system.src.js:562updateLinkSetOnLoad @ system.src.js:610(anonymous function) @ system.src.js:422`

I tried updating my jspm instance but there seems to be a separate issue with that: https://github.com/systemjs/systemjs/issues/440

**Comment by guybedford** [comment]
Perhaps try using jspm 0.17?
