### ISSUE TITLE
Trying to embed CSS in angular2 project: Error: Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by born2net** [jspm/jspm-cli#2085]
getting an error of:

```
Uncaught (in promise) Error: (SystemJS) Expected 'styles' to be an array of strings.
	Error: Expected 'styles' to be an array of strings.
	    at assertArrayOfStrings (http://localhost:9089/jspm_packages/npm/@angular/compiler@2.0.0/bundles/compiler.umd.js:3519:21)
	    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:9089/jspm_packages/npm/@angular/compiler@2.0.0/bundles/compiler.umd.js:14024:19)
```

my component:

```
import RatesTableTemplate from './RatesTable.html!text';
import RatesTableStyle from './RatesTable.css!';

@Component({
    selector: 'RatesTable',
    moduleId: __moduleName,
    changeDetection: ChangeDetectionStrategy.OnPush,
    styles: [RatesTableStyle],
    template: RatesTableTemplate
})

export class RatesTable {
```

jspm config plugin is configured:

```
  "src": {
            "main": "App",
            "defaultExtension": "ts",
            "meta": {
                "*.js": {
                    "loader": false
                },
                "*.ts": {
                    "loader": "ts"
                },
                "*.css": {
                    "loader": "css"
                }
            }
        },

     ...
   
   map: {
      ...
        "css": "github:systemjs/plugin-css@0.1.27"
    ...

```

is this supported? embedding the CSS inline with angular 2 project?

regards

Sean

**Comment by born2net** [comment]
ok found the solution, make sue NO css plugin is installed (remove from jspm config entirely) and set:
```
import RatesTableTemplate from './RatesTable.html!text';
import RatesTableStyle from './RatesTable.css!text';

@Component({
    selector: 'RatesTable',
    moduleId: __moduleName,
    changeDetection: ChangeDetectionStrategy.OnPush,
    styles: [RatesTableStyle],
    template: RatesTableTemplate
})
```

**Comment by sebasrodriguez** [comment]
@born2net just as a side note, how are you handling typings for angular 2 imports with jspm? do you have to npm install angular2 in order to resolve them with nodejs resolution?

**Comment by born2net** [comment]
Can check out my setup on this repo
https://github.com/born2net/ng2Boilerplate
jspm optimized with ts path mappings and much more
