### ISSUE TITLE
bootstrap download failure (tunneling socket could not be established, cause=Parse Error)

### ISSUE THREAD

**Issue by jansohn** [jspm/jspm-cli#2087]
I'm in a corporate network behind a proxy with restricted access to the internet. I've had the following domains opened up:

`nodejs.org`
`*.npmjs.org`
`github.com`
`*.jspm.io`

`HTTP_PROXY` and `HTTPS_PROXY` are set as environment variables. I can successfully install most packages, e.g. `jspm install npm:showdown`:

         Looking up npm:showdown
         Updating registry cache...
         Downloading npm:showdown@1.4.3
    [...]
    ok   Installed showdown as npm:showdown@^1.4.3 (1.4.3)
         Clearing configuration for npm:process@0.11.6
         Clearing configuration for github:showdownjs/showdown@1.4.3
         Removing package files for npm:process@0.11.6
         Removing package files for github:showdownjs/showdown@1.4.3
         Installed Forks
    
                                                                       npm:glob 5.0.15 7.0.5
                                                                    npm:isarray 0.0.1 1.0.0
                                                                     npm:lodash 3.10.1 4.3.0
    
         To inspect individual package constraints, use jspm inspect registry:name.
    
    
    ok   Install complete.

It fails however when I try to install bootstrap, `jspm install github:twbs/bootstrap`:

         Looking up github:twbs/bootstrap
         Updating registry cache...
         Downloading github:twbs/bootstrap@3.3.7
         Looking up npm:jquery
    
    warn Error on download for github:twbs/bootstrap
         Error: tunneling socket could not be established, cause=Parse Error
             at ClientRequest.onError (D:\XXX\node_modules\tunnel-agent\index.js:176:17)
             at ClientRequest.g (events.js:260:16)
             at emitOne (events.js:77:13)
             at ClientRequest.emit (events.js:169:7)
             at Socket.socketOnData (_http_client.js:325:9)
             at emitOne (events.js:77:13)
             at Socket.emit (events.js:169:7)
             at readableAddChunk (_stream_readable.js:153:18)
             at Socket.Readable.push (_stream_readable.js:111:10)
             at TCP.onread (net.js:531:20)
    
    err  Error downloading github:twbs/bootstrap.
    
    warn Installation changes not saved.

I can access `https://github.com/twbs/bootstrap` from the browser, so it's definitely reachable through the proxy. I'm new to this JSPM stuff, so I guess I must have missed something.

**Comment by jansohn** [comment]
From a wireshark capture I've learned that for the bootstrap installation additional stuff is pulled from `github-cloud.s3.amazonaws.com`. It would be nice to have this kind of information logged in JSPM (debug or trace mode).
