### ISSUE TITLE
[0.16.47] jspm bundle with babel complains about not exporting plugin instance

### ISSUE THREAD

**Issue by zbyte64** [jspm/jspm-cli#2144]
Project has two toplevel folders, `jpsm_packages` and `src`. When running `jspm bundle src/app.jsx` the following error occurs:

```
err  TypeError: Error compiling cjs module "npm:core-js@1.2.7/modules/es5.js" at jspm_packages/npm/core-js@1.2.7/modules/es5.js
    The plugin [null,{"deps":["npm:core-js@1.2.7/modules/$.js","npm:core-js@1.2.7/modules/$.export.js","npm:core-js@1.2.7/modules/$.descriptors.js","npm:core-js@1.2.7/modules/$.property-desc.js","npm:core-js@1.2.7/modules/$.html.js","npm:core-js@1.2.7/modules/$.dom-create.js","npm:core-js@1.2.7/modules/$.has.js","npm:core-js@1.2.7/modules/$.cof.js","npm:core-js@1.2.7/modules/$.invoke.js","npm:core-js@1.2.7/modules/$.fails.js","npm:core-js@1.2.7/modules/$.an-object.js","npm:core-js@1.2.7/modules/$.a-function.js","npm:core-js@1.2.7/modules/$.is-object.js","npm:core-js@1.2.7/modules/$.to-object.js","npm:core-js@1.2.7/modules/$.to-iobject.js","npm:core-js@1.2.7/modules/$.to-integer.js","npm:core-js@1.2.7/modules/$.to-index.js","npm:core-js@1.2.7/modules/$.to-length.js","npm:core-js@1.2.7/modules/$.iobject.js","npm:core-js@1.2.7/modules/$.uid.js","npm:core-js@1.2.7/modules/$.array-methods.js","npm:core-js@1.2.7/modules/$.array-includes.js","npm:core-js@1.2.7/modules/$.is-array.js"],"optimize":true,"static":false,"systemGlobal":"System"}] didn't export a Plugin instance
         at PluginManager.validate (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
         at PluginManager.add (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
         at File.buildTransformers (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/babel-core/lib/transformation/file/index.js:237:21)
         at new File (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/babel-core/lib/transformation/file/index.js:139:10)
         at Pipeline.transform (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
         at Object.exports.compile (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/systemjs-builder/compilers/compiler.js:24:22)
         at Object.exports.compile (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/systemjs-builder/compilers/cjs.js:88:19)
         at /Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/systemjs-builder/lib/compile.js:117:43
         at tryCatcher (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/bluebird/js/release/util.js:16:23)
         at Promise._settlePromiseFromHandler (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/bluebird/js/release/promise.js:510:31)
         at Promise._settlePromise (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/bluebird/js/release/promise.js:567:18)
         at Promise._settlePromiseCtx (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/bluebird/js/release/promise.js:604:10)
         at Async._drainQueue (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/bluebird/js/release/async.js:143:12)
         at Async._drainQueues (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/bluebird/js/release/async.js:148:10)
         at Immediate.Async.drainQueues (/Users/jasonkraus/Repos/project-cms-backend/project-cms/node_modules/bluebird/js/release/async.js:17:14)
         at runCallback (timers.js:574:20)
```

config.js:

```
System.config({
  baseURL: "/project-cms",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "ignore": ["jspm_packages"],
    "blacklist": [],
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
    "stage": 0
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  packages: {
    "src": {
      "defaultExtension": "js",
      "meta": {
        "*.jsx": {
          "format": "esm"
        },
        "*.css": {
          "loader": "css"
        }
      }
    }
  }
....
```

I am not sure why packages in `jspm_packages` are being ran through Babel. The entire project can be viewed at: https://github.com/zbyte64/project-cms/tree/jspm-update if anyone would like to take stab.

**Comment by sbaechler** [comment]
I had the same issue after installing Babel. So I reinstalled jspm and it worked again.
