### ISSUE TITLE
Repo jspm:plugin-babel not found

### ISSUE THREAD

**Issue by niedzielski** [jspm/jspm-cli#2157]
I can't seem to create the simplest project. The error message is `err  Repo jspm:plugin-babel not found. Perhaps try jspm install npm:plugin-babel.` and the config file is never made.

```
$ mkdir foo
$ cd foo
$ npm -v
3.10.8
$ node -v
v7.0.0
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (foo) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
license: (ISC) 
About to write to /home/stephen/Desktop/foo/package.json:

{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Stephen Niedzielski <stephen@niedzielski.com> (niedzielski.com)",
  "license": "ISC"
}


Is this ok? (yes) 
$ npm i -D jspm@0.17.0-beta.31
foo@1.0.0 /home/stephen/Desktop/foo
└─┬ jspm@0.17.0-beta.31 
  ├── bluebird@3.4.6 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├── core-js@1.2.7 
  ├─┬ glob@6.0.4 
  │ ├─┬ inflight@1.0.6 
  │ │ └── wrappy@1.0.2 
  │ ├── inherits@2.0.3 
  │ ├── once@1.4.0 
  │ └── path-is-absolute@1.0.1 
  ├── graceful-fs@4.1.10 
  ├─┬ jspm-github@0.14.11 
  │ ├─┬ expand-tilde@1.2.2 
  │ │ └── os-homedir@1.0.2 
  │ ├── netrc@0.1.4 
  │ ├─┬ tar-fs@1.14.0 
  │ │ ├─┬ pump@1.0.1 
  │ │ │ └─┬ end-of-stream@1.1.0 
  │ │ │   └── once@1.3.3 
  │ │ └─┬ tar-stream@1.5.2 
  │ │   ├─┬ bl@1.1.2 
  │ │   │ └── readable-stream@2.0.6 
  │ │   └── xtend@4.0.1 
  │ └─┬ which@1.2.11 
  │   └── isexe@1.1.2 
  ├─┬ jspm-npm@0.30.0 
  │ ├── buffer-peek-stream@1.0.1 
  │ ├─┬ readdirp@2.1.0 
  │ │ ├─┬ readable-stream@2.1.5 
  │ │ │ ├── buffer-shims@1.0.0 
  │ │ │ ├── core-util-is@1.0.2 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ ├── process-nextick-args@1.0.7 
  │ │ │ ├── string_decoder@0.10.31 
  │ │ │ └── util-deprecate@1.0.2 
  │ │ └── set-immediate-shim@1.0.1 
  │ └─┬ rmdir@1.2.0 
  │   └─┬ node.flow@1.2.3 
  │     └─┬ node.extend@1.0.8 
  │       ├── is@0.2.7 
  │       └── object-keys@0.4.0 
  ├─┬ jspm-registry@0.4.2 
  │ ├── rsvp@3.3.3 
  │ └── semver@4.3.6 
  ├─┬ liftoff@2.3.0 
  │ ├── extend@3.0.0 
  │ ├─┬ findup-sync@0.4.3 
  │ │ ├─┬ detect-file@0.1.0 
  │ │ │ └── fs-exists-sync@0.1.0 
  │ │ ├─┬ is-glob@2.0.1 
  │ │ │ └── is-extglob@1.0.0 
  │ │ ├─┬ micromatch@2.3.11 
  │ │ │ ├─┬ arr-diff@2.0.0 
  │ │ │ │ └── arr-flatten@1.0.1 
  │ │ │ ├── array-unique@0.2.1 
  │ │ │ ├─┬ braces@1.8.5 
  │ │ │ │ ├─┬ expand-range@1.8.2 
  │ │ │ │ │ └─┬ fill-range@2.2.3 
  │ │ │ │ │   ├── is-number@2.1.0 
  │ │ │ │ │   ├── isobject@2.1.0 
  │ │ │ │ │   └── randomatic@1.1.5 
  │ │ │ │ ├── preserve@0.2.0 
  │ │ │ │ └── repeat-element@1.1.2 
  │ │ │ ├─┬ expand-brackets@0.1.5 
  │ │ │ │ └── is-posix-bracket@0.1.1 
  │ │ │ ├── extglob@0.3.2 
  │ │ │ ├── filename-regex@2.0.0 
  │ │ │ ├─┬ kind-of@3.0.4 
  │ │ │ │ └── is-buffer@1.1.4 
  │ │ │ ├── normalize-path@2.0.1 
  │ │ │ ├─┬ object.omit@2.0.1 
  │ │ │ │ ├─┬ for-own@0.1.4 
  │ │ │ │ │ └── for-in@0.1.6 
  │ │ │ │ └── is-extendable@0.1.1 
  │ │ │ ├─┬ parse-glob@3.0.4 
  │ │ │ │ ├─┬ glob-base@0.3.0 
  │ │ │ │ │ └── glob-parent@2.0.0 
  │ │ │ │ └── is-dotfile@1.0.2 
  │ │ │ └─┬ regex-cache@0.4.3 
  │ │ │   ├── is-equal-shallow@0.1.3 
  │ │ │   └── is-primitive@2.0.0 
  │ │ └─┬ resolve-dir@0.1.1 
  │ │   └─┬ global-modules@0.2.3 
  │ │     ├─┬ global-prefix@0.1.4 
  │ │     │ ├── ini@1.3.4 
  │ │     │ └── osenv@0.1.3 
  │ │     └── is-windows@0.2.0 
  │ ├─┬ fined@1.0.2 
  │ │ ├── lodash.assignwith@4.2.0 
  │ │ ├── lodash.isempty@4.4.0 
  │ │ ├── lodash.pick@4.4.0 
  │ │ └─┬ parse-filepath@1.0.1 
  │ │   ├─┬ is-absolute@0.2.6 
  │ │   │ └─┬ is-relative@0.2.1 
  │ │   │   └─┬ is-unc-path@0.1.1 
  │ │   │     └── unc-path-regex@0.1.2 
  │ │   ├── map-cache@0.2.2 
  │ │   └─┬ path-root@0.1.1 
  │ │     └── path-root-regex@0.1.2 
  │ ├── flagged-respawn@0.3.2 
  │ ├── lodash.isplainobject@4.0.6 
  │ ├── lodash.isstring@4.0.1 
  │ ├── lodash.mapvalues@4.6.0 
  │ ├── rechoir@0.6.2 
  │ └── resolve@1.1.7 
  ├─┬ minimatch@3.0.3 
  │ └─┬ brace-expansion@1.1.6 
  │   ├── balanced-match@0.4.2 
  │   └── concat-map@0.0.1 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── ncp@2.0.0 
  ├─┬ proper-lockfile@1.2.0 
  │ ├── err-code@1.1.1 
  │ └── retry@0.10.0 
  ├─┬ request@2.78.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.5.0 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.1 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ is-my-json-valid@2.15.0 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ └── jsonpointer@4.0.0 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.1 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.10.1 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.0 
  │ │   ├─┬ dashdash@1.14.0 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.14.3 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.12 
  │ │ └── mime-db@1.24.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.3.0 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ └── tunnel-agent@0.4.3 
  ├─┬ rimraf@2.5.4 
  │ └─┬ glob@7.1.1 
  │   └── fs.realpath@1.0.0 
  ├─┬ sane@1.4.1 
  │ ├─┬ exec-sh@0.2.0 
  │ │ └── merge@1.2.0 
  │ ├─┬ fb-watchman@1.9.0 
  │ │ └─┬ bser@1.0.2 
  │ │   └── node-int64@0.4.0 
  │ ├── minimist@1.2.0 
  │ ├─┬ walker@1.0.7 
  │ │ └─┬ makeerror@1.0.11 
  │ │   └── tmpl@1.0.4 
  │ └── watch@0.10.0 
  ├── semver@5.3.0 
  ├─┬ systemjs@0.19.40 
  │ └── when@3.7.7 
  ├─┬ systemjs-builder@0.15.33 
  │ ├─┬ babel-core@6.18.2 
  │ │ ├─┬ babel-code-frame@6.16.0 
  │ │ │ ├── esutils@2.0.2 
  │ │ │ └── js-tokens@2.0.0 
  │ │ ├─┬ babel-generator@6.18.0 
  │ │ │ ├─┬ detect-indent@4.0.0 
  │ │ │ │ └─┬ repeating@2.0.1 
  │ │ │ │   └─┬ is-finite@1.0.2 
  │ │ │ │     └── number-is-nan@1.0.1 
  │ │ │ └── jsesc@1.3.0 
  │ │ ├── babel-helpers@6.16.0 
  │ │ ├── babel-messages@6.8.0 
  │ │ ├─┬ babel-register@6.18.0 
  │ │ │ ├── core-js@2.4.1 
  │ │ │ └─┬ home-or-tmp@2.0.0 
  │ │ │   └── os-tmpdir@1.0.2 
  │ │ ├─┬ babel-runtime@6.18.0 
  │ │ │ ├── core-js@2.4.1 
  │ │ │ └── regenerator-runtime@0.9.6 
  │ │ ├── babel-template@6.16.0 
  │ │ ├─┬ babel-traverse@6.18.0 
  │ │ │ ├── globals@9.12.0 
  │ │ │ └─┬ invariant@2.2.1 
  │ │ │   └── loose-envify@1.3.0 
  │ │ ├─┬ babel-types@6.18.0 
  │ │ │ └── to-fast-properties@1.0.2 
  │ │ ├── babylon@6.13.1 
  │ │ ├── convert-source-map@1.3.0 
  │ │ ├─┬ debug@2.2.0 
  │ │ │ └── ms@0.7.1 
  │ │ ├── json5@0.5.0 
  │ │ ├── lodash@4.16.6 
  │ │ ├── private@0.1.6 
  │ │ └── slash@1.0.0 
  │ ├─┬ babel-plugin-transform-cjs-system-wrapper@0.2.1 
  │ │ └── babel-plugin-transform-cjs-system-require@0.1.1 
  │ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.18.0 
  │ │ └── babel-helper-hoist-variables@6.18.0 
  │ ├── babel-plugin-transform-global-system-wrapper@0.0.1 
  │ ├── babel-plugin-transform-system-register@0.0.1 
  │ ├── data-uri-to-buffer@0.0.4 
  │ ├─┬ es6-template-strings@2.0.1 
  │ │ ├─┬ es5-ext@0.10.12 
  │ │ │ ├─┬ es6-iterator@2.0.0 
  │ │ │ │ └── d@0.1.1 
  │ │ │ └── es6-symbol@3.1.0 
  │ │ └─┬ esniff@1.1.0 
  │ │   └── d@1.0.0 
  │ ├── glob@7.1.1 
  │ ├─┬ rollup@0.36.3 
  │ │ └── source-map-support@0.4.6 
  │ └── source-map@0.5.6 
  ├─┬ traceur@0.0.105 
  │ ├─┬ commander@2.9.0 
  │ │ └── graceful-readlink@1.0.1 
  │ ├── glob@5.0.15 
  │ ├── semver@4.3.6 
  │ └─┬ source-map-support@0.2.10 
  │   └─┬ source-map@0.1.32 
  │     └── amdefine@1.0.1 
  └─┬ uglify-js@2.7.4 
    ├── async@0.2.10 
    ├── uglify-to-browserify@1.0.2 
    └─┬ yargs@3.10.0 
      ├── camelcase@1.2.1 
      ├─┬ cliui@2.1.0 
      │ ├─┬ center-align@0.1.3 
      │ │ ├─┬ align-text@0.1.4 
      │ │ │ ├── longest@1.0.1 
      │ │ │ └── repeat-string@1.6.1 
      │ │ └── lazy-cache@1.0.4 
      │ ├── right-align@0.1.3 
      │ └── wordwrap@0.0.2 
      ├── decamelize@1.2.0 
      └── window-size@0.1.0 

npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.
$ node_modules/.bin/jspm cc
ok   Loader file cache cleared.
ok   Package cache cleared.
ok   github cache cleared.
ok   jspm cache cleared.
ok   npm cache cleared.

warn All caches cleared.
     Please post an issue if you suspect the cache isn't invalidating properly.
     jspm install -f is equivalent to running a cache clear for that specific package tree.
$ node_modules/.bin/jspm init
Configuration file jspm.config.js does not exist, create it? [Yes]: Yes
Init mode (Quick, Standard, Custom) [Quick]: Quick
Local package name (recommended, optional): foo
package.json directories.baseURL: .
package.json configFiles folder [./]: ./
Use package.json configFiles.jspm:dev? [No]: No
SystemJS.config browser baseURL (optional): /
SystemJS.config Node local project path [src/]: src/
SystemJS.config local package main [foo.js]: foo.js
SystemJS.config transpiler (Babel, Traceur, TypeScript, None) [babel]: babel

err  Repo jspm:plugin-babel not found. Perhaps try jspm install npm:plugin-babel.
$ node_modules/.bin/jspm install npm:plugin-babel
Configuration file jspm.config.js does not exist, create it? [Yes]: Yes
Init mode (Quick, Standard, Custom) [Quick]: Quick
Local package name (recommended, optional): foo
package.json directories.baseURL: .
package.json configFiles folder [./]: ./
Use package.json configFiles.jspm:dev? [No]: No
SystemJS.config browser baseURL (optional): /
SystemJS.config Node local project path [src/]: src/
SystemJS.config local package main [foo.js]: foo.js
SystemJS.config transpiler (Babel, Traceur, TypeScript, None) [babel]: babel

err  Repo jspm:plugin-babel not found. Perhaps try jspm install npm:plugin-babel.

warn Installation changes not saved.
```

**Comment by OrKoN** [comment]
@niedzielski Hi, I have just tried to reproduce this but it works for me... Can you provide additional details? `jspm install plugin-babel` also works for me.

**Comment by niedzielski** [comment]
@OrKoN, I've updated the description to include the full details of every step. I've also tried deleting ~/.jspm directory and using a global install of jspm. However, `jspm install plugin-babel` always fails.

**Comment by OrKoN** [comment]
@niedzielski I have retried with the exactly same version of Node and NPM as you have but it still works for me. `node_modules/.bin/jspm install npm:plugin-babel` results in a 404 error (which I think is correct). `jspm init` and `node_modules/.bin/jspm install jspm:plugin-babel` work without any problem.

**Comment by OrKoN** [comment]
@niedzielski do you have git installed? which version?

**Comment by niedzielski** [comment]
@OrKoN, I'm on Git v2.10.1. Both `jspm install jspm:plugin-babel` and `jspm install npm:plugin-babel` fail on my system. I'll try removing my NPM directory as well.

**Comment by niedzielski** [comment]
I deleted my NPM files and no luck :/

**Comment by niedzielski** [comment]
What's odd is that I can install the guybedford/jspm-react-component-demo. I was thinking this had something to do with the package.json format but if it's working for you, I guess that's less likely.

**Comment by niedzielski** [comment]
If I take the stock NPM package.json and add an empty "jspm" object to it, `jspm install npm:plugin-babel` produces the following new error:

```
err  TypeError: Install of jspm to 0.17.0-beta.31 within undefined has no registry property provided.
    at /home/stephen/Desktop/crap/node_modules/jspm/lib/common.js:143:13
    at Array.forEach (native)
    at processDeps (/home/stephen/Desktop/crap/node_modules/jspm/lib/common.js:126:21)
    at new PackageConfig (/home/stephen/Desktop/crap/node_modules/jspm/lib/config/package.js:150:28)
    at /home/stephen/Desktop/crap/node_modules/jspm/lib/config/index.js:176:20
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

warn Installation changes not saved.
```

If I then add an empty dependencies object to the jspm object, `jspm install npm:plugin-babel` then produces the following different error:

```
err  Repo npm:plugin-babel not found!

warn Installation changes not saved.
```

However, `jspm install npm:systemjs-plugin-babel` succeeds. Maybe it has something to do with how it's listed in the [registry][0]?

  [0]: https://www.npmjs.com/package/systemjs-plugin-babel

**Comment by guybedford** [comment]
Is this a Linux machine? There was an issue here, which was resolved in the latest jspm-registry. Try reinstalling jspm fresh and see if that helps.

**Comment by niedzielski** [comment]
:100: Woohoo! It works! Thanks for the quick turnaround! And yes, this is on Debian Linux :]

**Comment by guybedford** [comment]
Great, thanks for confirming.
