### ISSUE TITLE
Issue with JSPM beta 0.17.0-beta.35

### ISSUE THREAD

**Issue by myuseringithub** [jspm/jspm-cli#2225]
Using newly released 0.17.0-beta.35 seems to cause issues when installing a newly created package.json or one that already exists. 
node v8.0.0-nightly20170126a67a04d765

Shows following error:
```
root@24788fbdef1d:/app/clientSide/jspm_packages_modules# jspm install

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
(node:22) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

err  Error on getOverride for jspm:npm
TypeError: "timeout" must be an unsigned integer
    at validateTimeout (child_process.js:599:11)
    at Object.exports.execFile (child_process.js:150:3)
    at exports.exec (child_process.js:109:18)
    at tryApply (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1402:7)
    at handleValueInput (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1616:16)
    at fn (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1606:14)
    at registry.updateRegistry (/usr/local/lib/node_modules/jspm/node_modules/jspm-registry/registry.js:175:41)
    at registry.getOverride (/usr/local/lib/node_modules/jspm/node_modules/jspm-registry/registry.js:80:15)
    at /usr/local/lib/node_modules/jspm/lib/registry.js:139:30
    at tryCatcher (/usr/local/lib/node_modules/jspm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/jspm/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/usr/local/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/local/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/jspm/node_modules/bluebird/js/release/async.js:17:14)

warn Installation changes not saved.
```

**Comment by myuseringithub** [comment]
Turns out to be nodejs nightly build issue. Rolled back to stable node release. Everything works.
