### ISSUE TITLE
[0.17 beta 38] angular-translate.js detected as global but didn't execute correctly

### ISSUE THREAD

**Issue by Rush** [jspm/jspm-cli#2241]
After installing `angular-translate` with `jspm install angular-translate` and trying to load it.

```
system.js:4 Uncaught (in promise) Error: Module http://localhost:8080/jspm_packages/github/angular-translate/bower-angular-translate@2.13.1/angular-translate.js detected as global but didn't execute correctly.   Instantiating http://localhost:8080/jspm_packages/github/angular-translate/bower-angular-translate@2.13.1/angular-translate.js   Loading http://localhost:8080/javascripts/components/shared/common.js   Loading http://localhost:8080/javascripts/app.js   Loading http://localhost:8080/javascripts/application.js   Loading application.js     at http://localhost:8080/javascripts/jspm_packages/system.js:5:628
```

**Comment by Rush** [comment]
With `system.src.js`:
```
system.src.js:78 Uncaught (in promise) Error: Module http://localhost:8080/jspm_packages/github/angular-translate/bower-angular-translate@2.13.1/angular-translate.js detected as global but didn't execute correctly.
  Instantiating http://localhost:8080/jspm_packages/github/angular-translate/bower-angular-translate@2.13.1/angular-translate.js
  Loading http://localhost:8080/javascripts/components/shared/common.js
  Loading http://localhost:8080/javascripts/app.js
  Loading http://localhost:8080/javascripts/application.js
  Loading application.js
    at http://localhost:8080/javascripts/jspm_packages/system.src.js:3598:13
```

**Comment by guybedford** [comment]
Thanks, I've added a fix in https://github.com/jspm/jspm-cli/commit/e911f0526a37bc3740934c9d9655c2444d8c65da.
