### ISSUE TITLE
Bundle is failing with arithmetic with "Cannot read property 'forEach' of undefined"

### ISSUE THREAD

**Issue by pocesar** [jspm/jspm-cli#2244]
This kind of command used to work, I don't know what I did that broke it. 

JSPM 0.17 beta 39
Node 7.5.0

jspm.config.js

```js
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "dist": "dist/"
  },
  browserConfig: {
    "baseURL": "/"
  },
  packages: {
    "dist": {
      "format": "register"
    }
  },
  meta: {
    "*.css": {
      "loader": "css"
    }
  }
});
```

Stacktrace:
```
> jspm bundle --minify dist/app.js - [dist/app.js] - ./styles/styles.css! ./dist/vendor.js

     Building the bundle tree for dist/app.js - [dist/app.js] - ./styles/styles.css!...

err  TypeError: Cannot read property 'forEach' of undefined
    at Trace.getLoadDependencies (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:944:12)
    at traverseTree (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\arithmetic.js:377:16)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:156:5
    at Array.forEach (native)
    at getTreeModulesPostOrder (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:155:14)
    at compileTree (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\compile.js:269:17)
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:700:14
    at runCallback (timers.js:651:20)
From previous event:
    at C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:699:6
From previous event:
    at Builder.bundle (C:\nodejs\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:692:4)
    at Builder.bundle (C:\nodejs\node_modules\jspm\lib\bundle.js:76:43)
    at C:\nodejs\node_modules\jspm\lib\bundle.js:168:27
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

`app.js` is a file with `SystemJS.register()`s from Typescript, there's nothing wrong with the file (it's working fine on the browser)

**Comment by aluanhaddad** [comment]
Would you be able to provide more information about your project? Although you have some questionable configuration (you do not need to use both plugin syntax and meta configuration for example) I could not reproduce this.

**Comment by pocesar** [comment]
I'm using Typescript with outFile as `dist/app.js`, module "system", it generates one file from all my src files with `System.register('component/something', ` inside, so the type of this file is `register` like this:

```js
System.register("helpers", ["bluebird", "capture-stack-trace"], function (exports_2, context_2) {
    'use strict';
    var __moduleName = context_2 && context_2.id;
    function requestJson(url, body, method, token) {
        return bluebird.try(function () {
            var headers = {
                Accept: 'application/json',
                'Content-Type': 'application/json',
            };
            if (token) {
                headers['Authorization'] = token;
            }
            var request = {
                method: method,
                mode: 'same-origin',
                headers: headers,
            };
            if (body) {
                request.body = JSON.stringify(body);
            }
            return fetch(url, request).then(function (response) {
                if (response.ok) {
                    return response.json();
                }
                else {
                    return response.json().then(function (res) {
                        if (res.error) {
                            throw new RequestError(res.error, response.status);
                        }
                        else {
                            throw new RequestError(response.statusText, response.status);
                        }
                    });
                }
            });
        });
    }
    exports_2("requestJson", requestJson);
    var bluebird, captureStackTrace, RequestError;
    return {
        setters: [
            function (bluebird_1) {
                bluebird = bluebird_1;
            },
            function (captureStackTrace_1) {
                captureStackTrace = captureStackTrace_1;
            }
        ],
        execute: function () {
            RequestError = (function (_super) {
                __extends(RequestError, _super);
                function RequestError(message, status) {
                    var _this = _super.call(this, message) || this;
                    _this.status = status;
                    captureStackTrace(_this);
                    return _this;
                }
                return RequestError;
            }(Error));
            exports_2("RequestError", RequestError);
        }
    };
});
```

My entrypoint looks like this:

```js
System.register("index", ["open-sans-fontface/open-sans.css!", "twbs/bootstrap/dist/css/bootstrap.css!", "react-bootstrap-table/dist/react-bootstrap-table-all.min.css!", "../styles/styles.css!", "any-promise/register/bluebird", "whatwg-fetch", "twbs/bootstrap", "react-dom", "app"], function (exports_24, context_24) {
    'use strict';
    var __moduleName = context_24 && context_24.id;
    var react_dom_1, app_1;
    return {
        setters: [
            function (_1) {
            },
            function (_2) {
            },
            function (_3) {
            },
            function (_4) {
            },
            function (_5) {
            },
            function (_6) {
            },
            function (_7) {
            },
            function (react_dom_1_1) {
                react_dom_1 = react_dom_1_1;
            },
            function (app_1_1) {
                app_1 = app_1_1;
            }
        ],
        execute: function () {
            react_dom_1.default.render(app_1.default, document.getElementById('mount'));
        }
    };
});
//# sourceMappingURL=app.js.map
```

nothing ununsual in the dependencies or overrides. I then manually patched SystemJS builder inside `systemjs-builder\lib\trace.js:944:12` and checking that line if it was undefined 

```
  // add the dependencies
  if (load.deps) {
    load.deps.forEach(function(dep) {
      deps.push(load.depMap[dep]);
    });
  }
```

now it gives this error:

```
err  TypeError: actions was defined via a bundle, so can only be used for subtraction or union operations.
```

**Comment by aluanhaddad** [comment]
@pocesar Thanks, that is just the information we needed.

You have configured TypeScript to bundle your application into a System.register bundle. This means that you cannot also bundle it using JSPM. Both tools expect to build a bundle directly from a tree of anonymous modules, but in this case, you have already built the bundle meaning the format is not what is expected. Although it is in `register` format, and you have indicated this via metadata, there are multiple variants of this format including the _named register_ output produced by bundling. 

You have a few options. Personally, I recommend using plugin-typescript and JSPM to bundle your application. TypeScript will be called to transpile each of your modules but you will gain access to robust build options including automatic optimization via Rollup, the ability to switch between watch bundling and individual transpilation during development, and access to the module arithmetic you are wanting to leverage.

You can also do it both ways of course, in which case you would feed the TypeScript sources directly to JSPM to create the arithmetic bundle and also compile them separately into an outfile via tsc.

You can set up plugin-typescript in an existing project by running
```bash
jspm init
```
from the root of your project directory and selecting `typescript` when prompted to choose a transpiler.

I hope this helps.

**Comment by pocesar** [comment]
I see now, thanks for the thorough explanation, so when using outDir from Typescript it generates each file as `System.register([], function(){})` (that's the anonymous module I guess), and then SystemJS can understand it as per-file basis. it does make sense, and after changing my settings to use outDir instead of outFile, it's working again. and that's why `load.deps` is undefined, because it's not an anonymous module

I had problems with plugin-typescript in the past, that's why I'm staying clear of it for the time being, and using plain `tsc -p tsconfig.json`

**Comment by aluanhaddad** [comment]
@pocesar That makes sense. 
Yes, those are indeed anonymous modules.

Perhaps we could issue a better error message here instead of failing with the aforementioned exception.
