### ISSUE TITLE
jspm suddenly starts failing

### ISSUE THREAD

**Issue by adriatic** [jspm/jspm-cli#2281]
My machine crashed (Windows 10, `system-thread-exception-not-handled`) and after reboot, the command `jspm install` that I use for years many times a day, fails for any application with:

```
jspm install
     Looking up npm:aurelia-animator-css
     Looking up npm:aurelia-bootstrapper
     Looking up npm:aurelia-fetch-client
     Looking up npm:aurelia-framework
     Looking up npm:aurelia-history-browser
     Looking up npm:aurelia-loader-default
     Looking up npm:aurelia-logging-console
     Looking up npm:aurelia-pal-browser
     Looking up npm:aurelia-polyfills
     Looking up npm:aurelia-router
     Looking up npm:aurelia-templating-binding
     Looking up npm:aurelia-templating-resources
     Looking up npm:aurelia-templating-router
     Looking up npm:bluebird
     Looking up npm:font-awesome
     Looking up npm:jquery
     Updating registry cache...

warn Error on getOverride for jspm:npm, retrying (1).
     Error: Command failed: git fetch --all && git reset --hard origin/master
     error: bad signature
     fatal: index file corrupt

         at ChildProcess.exithandler (child_process.js:211:12)
         at emitTwo (events.js:106:13)
         at ChildProcess.emit (events.js:191:7)
         at maybeClose (internal/child_process.js:885:16)
         at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 ...
```

This warning repeats many times.

My global jspm version is 0.16.53 and project local local definition in package.json is `"jspm": "^0.16.47"`

Please note that due to long outstanding issue with aurelia apps, I cannot upgrade jspm.

Is this a temporary issue with GitHub, broken jspm setup on my machine - or something I cannot even grasp?

**Comment by adriatic** [comment]
**Answer** it seems that something happened to `.jspm/config` file or `.jspm/jspm-cache` folder - as removing them (both unfortunately) solved my problem.

I suspect that the problem was in the `jspm-cache` content which caused the `error: bad signature` and `fatal: index file corrupt` error message.
