### ISSUE TITLE
Fails on jspm config

### ISSUE THREAD

**Issue by JoakimSoderberg** [jspm/jspm-cli#2287]
It would be nicer if I got some kind of help or more friendly error when using the command line incorrectly.

I'm guessing this was not intentional:

```
$ jspm config

err  TypeError: Cannot read property 'split' of undefined
         at Object.exports.set (/usr/lib/node_modules/jspm/lib/global-config.js:128:23)
         at /usr/lib/node_modules/jspm/cli.js:600:20
         at Object.<anonymous> (/usr/lib/node_modules/jspm/cli.js:623:3)
         at Module._compile (module.js:570:32)
         at Object.Module._extensions..js (module.js:579:10)
         at Module.load (module.js:487:32)
         at tryModuleLoad (module.js:446:12)
         at Function.Module._load (module.js:438:3)
         at Module.require (module.js:497:17)
         at require (internal/module.js:20:19)
         at Liftoff.<anonymous> (/usr/lib/node_modules/jspm/jspm.js:40:5)
         at Liftoff.<anonymous> (/usr/lib/node_modules/jspm/node_modules/liftoff/index.js:202:12)
         at Liftoff.<anonymous> (/usr/lib/node_modules/jspm/node_modules/liftoff/index.js:169:7)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)
         at Module.runMain (module.js:606:11)
```

**Comment by SerkanSipahi** [comment]
i have made a PR (https://github.com/jspm/jspm-cli/pull/2291) but we have to clear it with @guybedford

**Comment by SerkanSipahi** [comment]
@guybedford please close issue due its resolved in https://github.com/jspm/jspm-cli/pull/2295
