### ISSUE TITLE
"Path must be a string" when running on Elastic Beanstalk

### ISSUE THREAD

**Issue by selfagency** [jspm/jspm-cli#2292]
i'm trying to configure and fetch my jspm packages on my initial container build on elastic beanstalk using container commands in my .ebextensions, but for some reason, though jspm installs fine and is found on the path when executing, when it actually does execute, i get the following:

```
: path.js:7
  throw new TypeError('Path must be a string. Received ' + inspect(path));
  ^
  
  TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.join (path.js:1211:7)
  at Object.<anonymous> (/var/node_modules/jspm/lib/core.js:256:32)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
   (ElasticBeanstalk::ExternalInvocationError)
```

if i attempt to run jspm while sshing in to the server it works fine. but if run either as a container command or a shell script, this is always the result.

any ideas what could be causing this and how i might resolve it?

**Comment by selfagency** [comment]
i was able to resolve this by running the container command sudoing as the ec2-user.
