### ISSUE TITLE
jspm bundle doesn't work with dynamic import syntax

### ISSUE THREAD

**Issue by fusionstrings** [jspm/jspm-cli#2306]
dynamic import works during development but while trying with `jspm bundle js-name`, it fails.
I 've tried with and without babel plugin 'babel-plugin-syntax-dynamic-import' as jspm dev dependency.

Repository to reproduce is https://github.com/fusionstrings/jspm-bundle-dynamic-import-issue
I am using-
Node: v7.9.0
NPM: 4.2.0
OS MacOS Sierra 10.12.5

```
➜  jspm-bundle-dynamic-import-issue git:(master) ✗ jspm bundle jspm-stack
     Building the bundle tree for jspm-stack...

err  Error on dependency parsing for jspm-stack/index.js at file:///Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/src/index.js
  SyntaxError: unknown: Unexpected token, expected { (5:6)
  3 | console.log(module);
  4 | 
> 5 | import('./module.js').then(function (module) {
    |       ^
  6 |   console.log(module.default);
  7 | });
    at Parser.pp$5.raise (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.expect (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:1749:33)
    at Parser.pp$1.parseImportSpecifiers (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:2898:8)
    at Parser.pp$1.parseImport (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:2868:10)
    at Parser.pp$1.parseStatement (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:1884:49)
    at Parser.pp$1.parseBlockBody (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:1673:17)
    at parse (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babylon/lib/index.js:7221:37)
    at File.parse (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babel-core/lib/transformation/file/index.js:517:15)
    at File.parseCode (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babel-core/lib/transformation/file/index.js:602:20)
    at /Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at SystemJSNodeLoader.loader.instantiate (/Users/dilip/github/issues/jspm-bundle-dynamic-import-issue/node_modules/systemjs-builder/compilers/esm.js:59:24)
```

**Comment by guybedford** [comment]
This feature isn't supported yes in SystemJS Builder. Tracking at https://github.com/systemjs/builder/issues/813.

**Comment by fusionstrings** [comment]
Thank @guybedford

**Comment by amenadiel** [comment]
Why don't just use SystemJS.import?
