### ISSUE TITLE
npm:babel-core@5.18.38 was changed!

### ISSUE THREAD

**Issue by robbiemu** [jspm/jspm-cli#2327]
Should core libraries be changed retroactively? this seems like a serious issue.
My demo project at this site https://robbiemu.github.io/roguelike/ has been working for months, but today I noticed it is not working. This project had no errors whatever when I stopped developing it, and I believe as recently as 2 days ago I played my little game at that url. In the logs I now find these errors:

```
system@0.19.34.src.js:1059 GET https://npm.jspm.io/babel-core@5.8.38/package.js 404 ()
Z @ system@0.19.34.src.js:1059
(anonymous) @ system@0.19.34.src.js:1782
(anonymous) @ system@0.19.34.src.js:1781
(anonymous) @ system@0.19.34.src.js:2810
(anonymous) @ system@0.19.34.src.js:3384
(anonymous) @ system@0.19.34.src.js:3696
(anonymous) @ system@0.19.34.src.js:4088
(anonymous) @ system@0.19.34.src.js:4551
(anonymous) @ system@0.19.34.src.js:4820
(anonymous) @ system@0.19.34.src.js:413
system@0.19.34.src.js:1059 XHR finished loading: GET "https://npm.jspm.io/babel-core@5.8.38/lib/transformation/file/options/config.js".
Z @ system@0.19.34.src.js:1059
(anonymous) @ system@0.19.34.src.js:1782
(anonymous) @ system@0.19.34.src.js:1781
(anonymous) @ system@0.19.34.src.js:2810
(anonymous) @ system@0.19.34.src.js:3384
(anonymous) @ system@0.19.34.src.js:3696
(anonymous) @ system@0.19.34.src.js:4088
(anonymous) @ system@0.19.34.src.js:4551
(anonymous) @ system@0.19.34.src.js:4820
(anonymous) @ system@0.19.34.src.js:413
Error: (SystemJS) XHR error (404) loading https://npm.jspm.io/babel-core@5.8.38/lib/transformation/file/options/config.js
	Error: XHR error (404) loading https://npm.jspm.io/babel-core@5.8.38/lib/transformation/file/options/config.js
	    at o (https://jspm.io/system@0.19.34.js:5:17650)
	    at XMLHttpRequest.Z.s.onreadystatechange (https://jspm.io/system@0.19.34.js:5:18238)
	Error loading https://npm.jspm.io/babel-core@5.8.38/lib/transformation/file/options/config.js as "../transformation/file/options/config" from https://npm.jspm.io/babel-core@5.8.38/lib/api/node.js
	Error loading https://robbiemu.github.io/roguelike/app/components/Game.jsx
system@0.19.34.src.js:1059 XHR finished loading: GET "https://npm.jspm.io/babel-core@5.8.38/package.js".
//...
system@0.19.34.src.js:1059 XHR finished loading: GET "https://npm.jspm.io/babel-core@5.8.38/lib/transformation/transformers/aliases.js".
Z @ system@0.19.34.src.js:1059
(anonymous) @ system@0.19.34.src.js:1782
(anonymous) @ system@0.19.34.src.js:1781
(anonymous) @ system@0.19.34.src.js:2810
(anonymous) @ system@0.19.34.src.js:3384
(anonymous) @ system@0.19.34.src.js:3696
(anonymous) @ system@0.19.34.src.js:4088
(anonymous) @ system@0.19.34.src.js:4551
(anonymous) @ system@0.19.34.src.js:4820
(anonymous) @ system@0.19.34.src.js:413
system@0.19.34.src.js:1059 GET https://npm.jspm.io/babel-core@5.8.38/lib/transformation/transformers/deprecated.js 404 ()
//...
system@0.19.34.src.js:1059 XHR finished loading: GET "https://npm.jspm.io/babel-core@5.8.38/lib/transformation/file/options/config.js".
//...
system@0.19.34.src.js:1059 GET https://npm.jspm.io/babel-plugin-runtime@1.0.7/lib/definitions.js 404 ()
//...
system@0.19.34.src.js:1059 GET https://npm.jspm.io/esprima-fb@15001.1001ev-harmony-fb.js 404 ()
//...
```

In my network responses I see:

### config.js
```
Repo and version matched, but path "lib/transformation/file/options/config.js" not found. Symlinks and submodules not currently supported, file an issue to request this use case.
```
### package.js
```
Repo and version matched, but path "package.js" not found. Symlinks and submodules not currently supported, file an issue to request this use case.
```
### depreciated.js
```
Repo and version matched, but path "lib/transformation/transformers/deprecated.js" not found. Symlinks and submodules not currently supported, file an issue to request this use case.
```
### aliases.js
```
Repo and version matched, but path "lib/transformation/transformers/deprecated.js" not found. Symlinks and submodules not currently supported, file an issue to request this use case.
```
### definitions.js
```
Repo and version matched, but path "lib/definitions.js" not found. Symlinks and submodules not currently supported, file an issue to request this use case.
```
### esprima-fb
```
Repo and version match for npm:esprima-fb@15001.1001ev-harmony-fb not found.
```

**Comment by guybedford** [comment]
Thanks, yes the CDN was updated recently. I'll aim to have a look at fixing this later today.

**Comment by guybedford** [comment]
Ok this should be working now again. Thanks for posting.

**Comment by robbiemu** [comment]
thanks :)
