### ISSUE TITLE
SyntaxError: Unexpected token operator «=», expected punc «,» at minify

### ISSUE THREAD

**Issue by selfagency** [jspm/jspm-cli#2415]
**JSPM Version:** `$ jspm --version`
0.17.0-beta.49

**Transpiler Plugin(s):** babel / traceur / typescript / I do not use a transpiler
babel

**Details:**
running in development/watch mode works just fine, but when i try to build my app—

```
➜ jspm build src/scripts/nylon.js public/scripts/nylon.js --format cjs --minify
     Creating the single-file build for src/scripts/nylon.js...

err  Error: SyntaxError: Unexpected token operator «=», expected punc «,»
    at minify (/Users/daniel/Dev/nylon-web/node_modules/systemjs-builder/lib/output.js:80:11)
    at exports.writeOutputs (/Users/daniel/Dev/nylon-web/node_modules/systemjs-builder/lib/output.js:154:14)
    at /Users/daniel/Dev/nylon-web/node_modules/systemjs-builder/lib/builder.js:807:14
    at tryCatcher (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/daniel/Dev/nylon-web/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

**Comment by guybedford** [comment]
The issue is that SystemJS Builder hasn't been updated to support all of the latest EcmaScript features. 

I've created an issue at https://github.com/systemjs/builder/issues/858 to track this.

I am not actively working on maintaining SystemJS builder anymore - so this will not be implemented unless someone decides to work on it.

**Comment by selfagency** [comment]
yeah, unfortunately i love jspm but, i've been forced to switch to fusebox due to increasing obsolescence.
