### ISSUE TITLE
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by asxelot** [jspm/jspm-cli#2426]
**JSPM Version:** `$ jspm --version` 0.16.2
`$ node -v` v10.13.0
`$ npm -v` 6.7.0
**Transpiler Plugin(s):** babel 

**Details:**
Can't install packages
```
err  TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

err  Error downloading loader files.

err  TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
         at maybeCallback (fs.js:129:9)
         at Object.writeFile (fs.js:1156:14)
         at /Users/user/work/frontend/node_modules/jspm/lib/core.js:293:17
         at tryCatch (/Users/user/work/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
         at invokeCallback (/Users/user/work/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
         at publish (/Users/user/work/frontend/node_modules/rsvp/dist/rsvp.js:508:7)
         at flush (/Users/user/work/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
         at process._tickCallback (internal/process/next_tick.js:61:11)
```

In node v10 `fs.writeFile` callback is required.

**Comment by guybedford** [comment]
Thanks, I've added a fix for this in https://github.com/jspm/jspm-cli/commit/4aa22ef5969f85ea46782c14716d79045511fec1, and released in 0.16.54.
