### ISSUE TITLE
Cannot find module C:\Program

### ISSUE THREAD

**Issue by dy** [jspm/jspm-cli#2483]
I run jspm following the docs, installing http-server
```
jspm install http-server --dev
jspm_packages/.bin/http-server.cmd
```

In the result I see:

```
internal/modules/esm/default_resolve.js:59
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module 'C:\Program' imported from C:\projects\spect\
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:59:13)
    at Loader.resolve (internal/modules/esm/loader.js:70:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:143:40)
    at Loader.import (internal/modules/esm/loader.js:127:28)
    at internal/process/esm_loader.js:44:43
    at Object.exports.initializeLoader (internal/process/esm_loader.js:51:5)
    at initializeESMLoader (internal/bootstrap/pre_execution.js:373:9)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:52:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'ERR_MODULE_NOT_FOUND'
```

Seems that it doesn't handle spaces in path properly

**Comment by dy** [comment]
Apparently `JSPM_PATH` both in `http-server` and `http-server.cmd` doesn't handle escapes properly.
