### ISSUE TITLE
jspm build: Could not load dom-helpers/removeClass

### ISSUE THREAD

**Issue by GongT** [jspm/jspm-cli#2503]
jspm build @material-ui/core
``` text
err (jspm) Error: Could not load /PATH/dist/dep-build/jspm_packages/npm/dom-helpers@5.1.3/removeClass.dew.js (imported by /PATH/dist/dep-build/jspm_packages/npm/react-transition-group@4.3.0/cjs/CSSTransition.dew.js): ENOENT: no such file or directory, open '/PATH/dist/dep-build/jspm_packages/npm/dom-helpers@5.1.3/removeClass.dew.js'
```

The file `/PATH/dist/dep-build/jspm_packages/npm/dom-helpers@5.1.3/removeClass` is not exist.

But `/PATH/dist/dep-build/jspm_packages/npm/dom-helpers@5.1.3/removeClass/package.json` is exist.

**Comment by TobyEalden** [comment]
You need to add an override to the `overrides` section of package.json.

Something like:
```js
      "npm:dom-helpers@5.1.3": {
        "map": {
          "./addClass.js": {
            "browser": "./esm/addClass.js"
          },
          "./removeClass.js": {
            "browser": "./esm/removeClass.js"
          }
        }
      }
```

**Comment by GongT** [comment]
Really thanks! It block me 2 days.

By the way, is there some document for this? I've searched jspm and rollup's document, did not found something about "overrides" or "map"

**Comment by GongT** [comment]
Oh, this is not work with rollup...

**Comment by GongT** [comment]
Oh... It does not works.

I can now use `jspm build @material-ui/core` to create a "dist/core.js", and I can see "removeClass" code there.

But, It not work with `jspm build ./my-code.js`.

(And I got another error: `err (jspm) Error: Could not load /PATH/jspm_packages/npm/@material-ui/icons@4.5.1/CheckCircle (imported by /PATH/dist/common/ui/notify/alertVariant.js): ENOENT: no such file or directory, open '/PATH/jspm_packages/npm/@material-ui/icons@4.5.1/CheckCircle'`

**Comment by GongT** [comment]
After some debug, I got some more information:

This may not a bug. But I don't know what is the "right" way to do this.

|  | jspm.json exists | NOT exists |
|:----|:---:|:---:|
|***module***| ❌ **A** | ❌ **B** |
|***commonjs***| ❌ **C** | ✔️ |

***module* means `"type": "module"` in `package.json` and write my code with `import`, *commonjs* is `"type": "module"` and `require`**

## A: module + jspm_packages
Error: I can only use `import x from "@material-ui/core/colors/index.js"` but not `import x from "@material-ui/core/colors"`
```
err (jspm) Error: Could not load /PatH/dist/out-ts/jspm_packages/npm/@material-ui/core@4.6.1/colors (imported by /PatH/dist/out-ts/common/ui/notify/alertVariant.js): EISDIR: illegal operation on a directory, read
```
This is not supported by any IDE or tools I used.

😭 And even I write code like above, It still has problem in `react-dom`. describe below.

## B: module + node_modules
This code cause `'render' is not exported by` error: (from `react-dom/index.js`)
```javascript
if (process.env.NODE_ENV === 'production') {
  // DCE check should happen before ReactDOM bundle executes so that
  // DevTools can report bad minification during injection.
  checkDCE();
  module.exports = require('./cjs/react-dom.production.min.js');
} else {
  module.exports = require('./cjs/react-dom.development.js');
}
```

```
err (jspm) Error: 'render' is not exported by ../../node_modules/react-dom/index.js?entry
    at error (/PatH/node_modules/rollup/dist/rollup.js:5351:30)
    at Module.error (/PatH/node_modules/rollup/dist/rollup.js:9643:9)
    at handleMissingExport (/PatH/node_modules/rollup/dist/rollup.js:9560:21)
    at Module.traceVariable (/PatH/node_modules/rollup/dist/rollup.js:9951:17)
    at ModuleScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:8620:39)
    at FunctionScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at ChildScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at ReturnValueScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at ChildScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at Identifier$1.bind (/PatH/node_modules/rollup/dist/rollup.js:4381:40)
```

## C: cjs + jspm_packages
Error: from my code (commonjs) require `react in jspm_packages` (esm), wrongof course.
```
err (jspm) SyntaxError: /PatH/dist/out-ts/jspm_packages/npm/react@16.12.0/index.js: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.

> 1 | import { dew } from './index.dew.js';
    | ^
  2 | export default dew();
  3 |
```

**Comment by TobyEalden** [comment]
This is expected due to the way ES6 modules work.

Try something like:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import Button from '@material-ui/core/Button/index.js';

const Hello = () => {
  return (
    <Button.default variant="contained" color="primary">HELLO WORLD</Button.default>
  );
};

ReactDOM.render(
  <Hello />,
  document.getElementById("root")
);
```

**Comment by GongT** [comment]
@TobyEalden But I can not import `react-dom`🤔

This is log:
```
/PatH/node_modules/jspm/bin/jspm build ./pages/test/1.js ./pages/test/2.js ./pages/test/3.js ./pages/welcome.js --format system -d /PatH/dist/rollup-build --clear-dir -o /PatH/dist/importmap.json --source-map
err (jspm) Error: 'render' is not exported by jspm_packages/npm/react-dom@16.12.0/index.js
    at error (/PatH/node_modules/rollup/dist/rollup.js:5351:30)
    at Module.error (/PatH/node_modules/rollup/dist/rollup.js:9643:9)
    at handleMissingExport (/PatH/node_modules/rollup/dist/rollup.js:9560:21)
    at Module.traceVariable (/PatH/node_modules/rollup/dist/rollup.js:9951:17)
    at ModuleScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:8620:39)
    at FunctionScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at ChildScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at ReturnValueScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at ChildScope.findVariable (/PatH/node_modules/rollup/dist/rollup.js:3043:38)
    at Identifier$1.bind (/PatH/node_modules/rollup/dist/rollup.js:4381:40)
process exited with code 1
```

**Comment by GongT** [comment]
Ok, I can not use `import { render } from 'react-dom';`

Not way to get IDE auto-complete support any more?

**Comment by GongT** [comment]
Sorry I have a new question.

In fact I'm using typescript.

But this can not pass type check:
```typescript
import Button from '@material-ui/core/Button/index.js';
console.log(Button.default); // no default on Button
```

Can I do anything without modify some internal library?

**Comment by GongT** [comment]
Resolved by apply `babel-plugin-transform-cjs-dew` to my compiled code.
