### ISSUE TITLE
jspm install produces "Lock file is already being hold"

### ISSUE THREAD

**Issue by koslambrou** [jspm/jspm-cli#2513]
In my Node project, I installed `jspm@2.0.0-beta.7` through: ```npm install jspm --save-dev```.

Installing `jquery` and `d3` through `./node_modules/.bin/jspm install jquery` and `./node_modules/.bin/jspm install d3` has no output error.

However, doing `./node_modules/.bin/jspm install rdflib` produced the following output:

```
warn (jspm) Deprecation warning for npm:request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warn (jspm) Deprecation warning for npm:text-encoding@0.6.4: no longer maintained
warn (jspm) Deprecation warning for npm:core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warn (jspm) Deprecation warning for npm:mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warn (jspm) Deprecation warning for npm:core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warn (jspm) Deprecation warning for npm:resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warn (jspm) Deprecation warning for npm:urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
err (jspm) Lock file is already being hold
     Resolving npm:@babel/helper-plugin-utils@^7.8.3
     Installing npm:@babel/plugin-transform-react-jsx@7.9.4.
     Installing npm:metro-react-native-babel-preset@0.58.0.
     Installing npm:metro-react-native-babel-transformer@0.58.0.
     Installing npm:react-native@0.62.0.
     Installing npm:react-native-securerandom@0.1.1.
     Installing npm:isomorphic-webcrypto@2.3.6.
     Installing npm:@solid/oidc-rp@0.10.0.
     Installing npm:@solid/cli@0.1.3.
     Installing npm:solid-auth-cli@1.0.12.
     Installing npm:rdflib@1.1.0.
     Error: Lock file is already being hold
    at options.fs.stat (/home/kolam/git/cq-rdf-viz/node_modules/proper-lockfile/index.js:54:47)
    at callback (/home/kolam/git/cq-rdf-viz/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:159:5)
```

Thanks for you help.

**Comment by koslambrou** [comment]
I probably has to do with the fact that `rdflib` depends upon `hermes-engine`.

If I try the command `./node_modules/.bin/jspm install hermes-engine`, it returns:

```                                
Looking up npm:hermes-engine
Downloading npm:hermes-engine@0.4.1
warn Error on download for npm:hermes-engine
         Response too large. 
err  Error downloading npm:hermes-engine.
warn Installation changes not saved. 
```

**Comment by guybedford** [comment]
Sorry, but jspm 2 is no longer maintained due to a lack of user interest.
