### ISSUE TITLE
Error installing package npm:telehash

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#337]
Happy holidays!

I've been trying out jspm for a new es6 project and am finding it absolute great so far. =)
But I ran into this issue when trying to install the telehash package using jspm install npm:telehash:

     Looking up npm:telehash
     Creating registry cache...
     Downloading npm:telehash@0.3.23

    err  TypeError: Cannot read property 'indexOf' of undefined
         at /usr/lib/node_modules/jspm/node_modules/jspm-npm/npm.js:499:23
         at parseDependencies (/usr/lib/node_modules/jspm/node_modules/jspm-npm/npm.js:663:5)
         at Object.NPMLocation.getPackageConfig (/usr/lib/node_modules/jspm/node_modules/jspm-npm/npm.js:179:26)
         at /usr/lib/node_modules/jspm/lib/package.js:434:36
         at $$$internal$$tryCatch (/usr/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:490:16)
         at $$$internal$$invokeCallback (/usr/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:502:17)
         at $$$internal$$publish (/usr/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:473:11)
         at $$rsvp$asap$$flush (/usr/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1581:9)
         at process._tickCallback (node.js:372:11)

For now I'm going to try to link to a local npm install'd version of the package as a workaround.

Thank you for your amazing work on this and many other projects!

**Comment by guybedford** [comment]
This is now working in the 0.10.1 release being posted out shortly.
