### ISSUE TITLE
jspm install fails (curDeps is undefined)

### ISSUE THREAD

**Issue by theefer** [jspm/jspm-cli#348]
When running `jspm install` with 0.10.1, I get:

```
err  TypeError: Cannot read property 'length' of undefined
         at /home/seb/work/media-service/kahuna/node_modules/jspm/lib/package.js:602:79
         at $$$internal$$tryCatch (/home/seb/work/media-service/kahuna/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:490:16)
         at $$$internal$$invokeCallback (/home/seb/work/media-service/kahuna/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:502:17)
         at $$$internal$$publish (/home/seb/work/media-service/kahuna/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:473:11)
         at Object.$$rsvp$asap$$flush [as _onImmediate] (/home/seb/work/media-service/kahuna/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1581:9)
         at processImmediate [as _immediateCallback] (timers.js:345:15)
```

caused by `curDeps` being `undefined` at:

``` javascript
    // if we gained a new dependency, download it
    if (pjson.dependencies && Object.keys(pjson.dependencies).length > curDeps.length) {
```

From a cursory look at the lines above, this is caused by `endpoint.build` being `undefined`, which means `curDeps` never gets initialised. I'm lacking a bit of context around this code to provide a patch I'm afraid.

This is with an existing project I'm trying to upgrade to the latest jspm.

**Comment by guybedford** [comment]
Thanks I've posted a 0.10.2 with a fix.

**Comment by theefer** [comment]
I'm afraid the fix doesn't solve the error (the code still looks up the `length` property of the `undefined` variable `curDeps`), I'm still getting the same error with 0.10.2.

A fix would be to change `curDeps.length` to `(curDeps || []).length`.

**Comment by guybedford** [comment]
Thanks!

**Comment by theefer** [comment]
Worked with 0.10.3!
