### ISSUE TITLE
jspm install read existed config.js?

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#359]
just want to discuss specific development work flow with others.

I have just realized that jspm install affect config.js if it exist. It could be a problem in situation when we have jspm_packages in .gitignore and project need to run jspm install after first git clone but existing config.js has and configuration, for example:

```js
System.traceurOptions.annotations = true;
```

is it conventional way to set this traceur property in config.js and leave it in source version control or there is some better pratice?

here is stack trace after running jspm install and affecting traceurOptions before traceur is really installed:

```bach
$ jspm install

err  TypeError: Cannot set property 'annotations' of undefined
         at eval (eval at <anonymous> (/home/aleksandar/projects/metabolicjs/node_modules/jspm/lib/config/loader.js:78:17), <anonymous>:10:35)
         at asp.catch.then.then.self.originalConfig_ (/home/aleksandar/projects/metabolicjs/node_modules/jspm/lib/config/loader.js:78:5)
         at $$$internal$$tryCatch (/home/aleksandar/projects/metabolicjs/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:490:16)
         at $$$internal$$invokeCallback (/home/aleksandar/projects/metabolicjs/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:502:17)
         at $$$internal$$publish (/home/aleksandar/projects/metabolicjs/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:473:11)
         at Object.$$rsvp$asap$$flush [as _onImmediate] (/home/aleksandar/projects/metabolicjs/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1581:9)
         at processImmediate [as _immediateCallback] (timers.js:345:15)

warn Installation changes not saved.

```

**Comment by djindjic** [comment]
yes, that's it, thanks!
