### ISSUE TITLE
rsvp.js:1372 SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by reggi** [jspm/jspm-cli#430]
Any command I issue I get this

```bash
thomas@workstation:riot$ jspm install moment

/Users/thomas/riotjs-klaviyo/node_modules/riot/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1372
});
   
SyntaxError: Unexpected end of input
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/thomas/riotjs-klaviyo/node_modules/riot/node_modules/jspm/lib/ui.js:17:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by reggi** [comment]
Did a full uninstall and reinstall and works! `npm uninstall jspm -g && npm install jspm -g`
