### ISSUE TITLE
`jspm bundle` when using image plugin

### ISSUE THREAD

**Issue by speigg** [jspm/jspm-cli#438]
lib/app:
```javascript
import myImage from './logo.png!image'
```

When I try to run `jspm bundle lib/app bundle.js`:
```shell
$ jspm bundle lib/app bundle.js
     Building the bundle tree for lib/app...

err  ReferenceError: Error loading "lib/logo.png!github:systemjs/plugin-image@master" at file:/Users/xxx/lib/logo.png
     Error loading "lib/logo.png!github:systemjs/plugin-image@master" from "lib/app" at file:/Users/xxx/lib/app.js
     Image is not defined
         at evalmachine.<anonymous>:8:39
         at new Promise (/usr/local/lib/node_modules/jspm/node_modules/traceur/bin/traceur.js:1765:7)
         at Loader.exports.fetch (evalmachine.<anonymous>:7:10)
         at Loader.loader.fetch (/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1658:41)
         at Loader.loader.fetch (/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1730:26)
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:255:33
         at /usr/local/lib/node_modules/jspm/node_modules/traceur/bin/traceur.js:1787:100
         at promiseHandle (/usr/local/lib/node_modules/jspm/node_modules/traceur/bin/traceur.js:1874:20)
         at /usr/local/lib/node_modules/jspm/node_modules/traceur/bin/traceur.js:1868:9
```

**Comment by guybedford** [comment]
@speigg thanks, I've updated the image plugin for this in https://github.com/systemjs/plugin-image/commit/d6ea97d06d6731a245f3f7c49e7ffa7d9f792505, and release a 0.1.0. Let me know if that works ok for you.

**Comment by guybedford** [comment]
This should be resolved now, please let me know if you notice any further issues.

**Comment by gsong** [comment]
What does bundling an image reference actually do? I know we get back an image element with the import during development, but where and how is the image actually stored in the bundle?

Also, with the latest released everything, I'm getting the following error when trying to bundle the with a .svg import:

```
err  TypeError: Object.keys called on non-object
         at keys (native)
         at Function.keys (/Users/george/src/apple-store-search/node_modules/traceur/bin/traceur.js:231:31)
         at remapLoadRecord (/Users/george/src/apple-store-search/node_modules/systemjs-builder/lib/compile.js:77:12)
         at compileLoad (/Users/george/src/apple-store-search/node_modules/systemjs-builder/lib/compile.js:83:20)
         at /Users/george/src/apple-store-search/node_modules/systemjs-builder/lib/compile.js:152:14
         at lib$rsvp$$internal$$tryCatch (/Users/george/src/apple-store-search/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/george/src/apple-store-search/node_modules/rsvp/dist/rsvp.js:505:17)
         at /Users/george/src/apple-store-search/node_modules/rsvp/dist/rsvp.js:1001:13
         at lib$rsvp$asap$$flush (/Users/george/src/apple-store-search/node_modules/rsvp/dist/rsvp.js:1198:9)
         at process._tickCallback (node.js:355:11)
```

Any ideas?

**Comment by guybedford** [comment]
@gsong images don't build - so the idea is that the plugin should remain used in production to load the image. This was actually a regression in the builder I've fixed in https://github.com/systemjs/builder/commit/d5520a107d91b4229835d8f5a56b668d6e6ea468. Will post out a release this weekend with the update.

**Comment by Xample** [comment]
(Same ?) issue with Plugin github:systemjs/plugin-image@0.1.0 does not support static builds
