### ISSUE TITLE
Using -fl instead of --force --latest crashes when config.js doesn't exist

### ISSUE THREAD

**Issue by Bubblyworld** [jspm/jspm-cli#475]
I created a new folder with the following package.json and nothing else:
```
{
  "jspm": {
    "dependencies": {
      "css": "^0.1.0"
    }
  }
}
```

Calling `jspm install --force --latest` works fine, but if I instead run `jspm install -fl` the following error occurs every time:
```
err  TypeError: Cannot call method 'copy' of undefined
         at storeResolution (/home/guy/github/jspm/jspm-cli/lib/install.js:289:33)
         at pkg.locate.then.then.then.seen (/home/guy/github/jspm/jspm-cli/lib/install.js:157:14)
         at $$$internal$$tryCatch (/home/guy/github/jspm/jspm-cli/node_modules/rsvp/dist/rsvp.js:490:16)
         at $$$internal$$invokeCallback (/home/guy/github/jspm/jspm-cli/node_modules/rsvp/dist/rsvp.js:502:17)
         at $$$internal$$publish (/home/guy/github/jspm/jspm-cli/node_modules/rsvp/dist/rsvp.js:473:11)
         at Object.$$rsvp$asap$$flush [as _onImmediate] (/home/guy/github/jspm/jspm-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
         at processImmediate [as _immediateCallback] (timers.js:354:15)
```

I'm using JSPM master at the time of posting this. Version 11.3.

**Comment by guybedford** [comment]
Ah, the issue is that `-l` is taken to be `--link`.

I've added a better error message in https://github.com/jspm/jspm-cli/commit/d227f1a6d7348057de73c432467a6fa4183da8af so it will be obvious this is a linking bug.
