### ISSUE TITLE
jquery doesn't seem to work jquery@2.1.3

### ISSUE THREAD

**Issue by jason** [jspm/jspm-cli#500]
main.js 

var $ = require('jquery');
console.log($.fn.jquery);

jspm run dist/main:

err  file:/Users/jason/Projects/bt/jspm_packages/github/components/jquery@2.1.3/jquery.js:887
	var div = document.createElement("div");
	                  ^
     TypeError: Cannot read property 'createElement' of undefined
         at assert (file:/Users/jason/Projects/bt/jspm_packages/github/components/jquery@2.1.3/jquery.js:887:20)
         at file:/Users/jason/Projects/bt/jspm_packages/github/components/jquery@2.1.3/jquery.js:2555:24
         at file:/Users/jason/Projects/bt/jspm_packages/github/components/jquery@2.1.3/jquery.js:2606:3
         at file:/Users/jason/Projects/bt/jspm_packages/github/components/jquery@2.1.3/jquery.js:34:3
         at file:/Users/jason/Projects/bt/jspm_packages/github/components/jquery@2.1.3/jquery.js:38:2
         at Object.exports.runInThisContext (vm.js:74:17)
         at doEval (/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2308:10)
         at __eval (/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2222:7)
         at Loader.exec [as __exec] (/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:335:5)
         at Loader.loader.instantiate (/usr/local/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1443:16)

**Comment by OrKoN** [comment]
@jason what was the problem in your case? it seems that I have the same problem.
