### ISSUE TITLE
jspm dl-loader --edge is not loading the latest version

### ISSUE THREAD

**Issue by hipertracker** [jspm/jspm-cli#580]
How to force jspm to use the latest es6-module-loader version? `jsp init` creates older es6-module-loader@0.14.0. And 'jspm dl-loader --edge` has some errors
```
$ jspm dl-loader --edge
     Looking up loader files...

err  Error downloading loader files 
     TypeError: Cannot read property 'hash' of undefined
         at /Users/hipertracker/tmp/node_modules/jspm/lib/core.js:216:46
         at lib$rsvp$$internal$$tryCatch (/Users/hipertracker/tmp/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/hipertracker/tmp/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/hipertracker/tmp/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/hipertracker/tmp/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at process._tickCallback (node.js:349:13)
       es6-module-loader.js.map
       es6-module-loader.js
       es6-module-loader.src.js
       system.js
       system.js.map
       system.src.js
```

When I check es6-module-loader.src.js it does not contain [last changes](https://github.com/ModuleLoader/es6-module-loader/commit/4d0e42cbbf62274983f7764f3935060b6077048a).

**Comment by guybedford** [comment]
Have you overridden the GitHub endpoint in any way here? I'm not able to replicate the hash issue at all.

The reason it wasn't giving the latest versions is because it requires a build to exist in the repos, which I only do when the development work is stable. I've pushed the builds up now so this should work. I'll make sure to keep these up-to-date, but the latest changes may well be breaking with jspm so I can't make any guarantees.

**Comment by mrspeaker** [comment]
I also get the `TypeError: Cannot read property 'hash' of undefined at /usr/local/lib/node_modules/jspm/lib/core.js:216:46` when I try to specify edge. It's a very simple project, all defaults, no overriding endpoints.

**Comment by guybedford** [comment]
That's why I asked if you'd overriddent the `github:` endpoint because it's not returning a lookup response, which makes it look like you may be using jspm-git.

**Comment by ryanberckmans** [comment]
Also receiving error from `--edge`. I used `jspm init` and have no customizations; first time jspm user.

```
> jspm dl-loader --edge
     Looking up loader files...

err  Error downloading loader files
     TypeError: Cannot read property 'hash' of undefined
         at /usr/local/lib/node_modules/jspm/lib/core.js:216:46
         at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at Object.lib$rsvp$asap$$flush [as _onImmediate] (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at processImmediate [as _immediateCallback] (timers.js:354:15)
       es6-module-loader.js
       es6-module-loader.src.js
       es6-module-loader.js.map
       system.js
       system.src.js
       system.js.map
```

**Comment by guybedford** [comment]
Ok thanks I'll have a look at this again.

**Comment by guybedford** [comment]
I did some more tests with removing the local cache files, and this definitely will definitely work fine with the upcoming release.

**Comment by ryanberckmans** [comment]
Thanks kindly
