### ISSUE TITLE
v0.15.0 bundle-sfx fails using babel

### ISSUE THREAD

**Issue by OrKoN** [jspm/jspm-cli#624]
The following error occurs:

```
[21:43:33] Error: Error loading "app" at <unknown>
Cannot find module 'babel-core/browser.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at setConfig (/tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/dist/system.src.js:880:38)
    at Loader.loader.locate (/tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/dist/system.src.js:893:9)
    at Loader.loader.locate (/tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/dist/system.src.js:1712:25)
    at Loader.loader.locate (/tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2190:25)
    at /tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1509:33
    at tryCatchReject (/tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/tmp/jspm-ember-playground/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
```

The command is:

```
jspm.bundleSFX('app', 'dist/app.js', { sourceMaps: false, minify: true, mangle: false });
```

Am I missing something in my config? To reproduce, clone https://github.com/OrKoN/jspm-ember-playground, npm instal, gulp jspm

**Comment by guybedford** [comment]
`babel` is a devDependency in jspm 0.15.0. Try running `jspm init` after upgrade to ensure the dev dependencies are installed.

**Comment by guybedford** [comment]
I think you probably need to add the `configFile` property to your package.json file here for jspm to find it?

**Comment by OrKoN** [comment]
@guybedford still happens. I did the following: deleted jspm packages, cleaned npm cache, cleaned jspm cache, jspm init, jspm install. 

jspm inspect shows:

```
jspm inspect
     Installed Versions

                     github:components/ember 1.11.0-beta.5
                    github:components/jquery 2.1.3
       github:n-fuse/ember-template-compiler 1.11.0-beta.5
              github:n-fuse/plugin-ember-hbs 1.11.0-beta.5
             github:n-fuse/plugin-ember-ihbs 1.11.0-beta.5
                                   npm:babel 4.7.16
                           npm:babel-runtime 4.7.16

```

Maybe I've got somehow the wrong dependencies or some dependencies are broken?

**Comment by guybedford** [comment]
Thanks this is a bug, posting a patch now.

**Comment by guybedford** [comment]
Ok if you reinstall jspm the patch should apply.

**Comment by OrKoN** [comment]
Thanks! I confirm that it works now

**Comment by guybedford** [comment]
Great, thanks so much for catching that.
