### ISSUE TITLE
Reached maximum number of retries.

### ISSUE THREAD

**Issue by djindjic** [jspm/jspm-cli#628]
Is this related to current github DDoS issue?

```bash
warn Error on getOverride for jspm:github, retrying (3).
     Error: Command failed: /bin/sh -c git fetch --all && git reset --hard origin/master
     fatal: unable to access 'https://github.com/jspm/registry.git/': Failed to connect to github.com port 443: Connection timed out
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:744:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1008:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1080:5)\
```

**Comment by guybedford** [comment]
Yes probably.

**Comment by guybedford** [comment]
Yes probably.

**Comment by djindjic** [comment]
hmmm interesting is that shippable.com CI service, flags me success build no matter that jspm has some warnings. It may be jspm issue, why not return an 0 if jspm install is not successful?

```bash
warn Error on download for github:ModuleLoader/es6-module-loader, retrying (2).
     Error: connect ETIMEDOUT
         at errnoException (net.js:901:11)
         at Object.afterConnect [as oncomplete] (net.js:892:19)

warn Error on download for github:systemjs/systemjs, retrying (2).
     Error: connect ETIMEDOUT
         at errnoException (net.js:901:11)
         at Object.afterConnect [as oncomplete] (net.js:892:19)
       es6-module-loader.js
       es6-module-loader.src.js
       es6-module-loader.js.map
       system.js
       system.src.js
       system.js.map
     
     Using loader versions:
       es6-module-loader@0.16.1
       systemjs@0.16.4
     Looking up github:jmcriffey/bower-traceur-runtime
     Looking up github:jmcriffey/bower-traceur
     Downloading github:jmcriffey/bower-traceur@0.0.87
ok   Installed traceur as github:jmcriffey/bower-traceur@0.0.87 (0.0.87)
     Downloading github:jmcriffey/bower-traceur-runtime@0.0.87

warn Error on download for github:jmcriffey/bower-traceur-runtime, retrying (1).
     Error: connect ETIMEDOUT
         at errnoException (net.js:901:11)
         at Object.afterConnect [as oncomplete] (net.js:892:19)
ok   Installed traceur-runtime as github:jmcriffey/bower-traceur-runtime@0.0.87 (0.0.87)
ok   Loader files downloaded successfully

ok   Install complete.
```

**Comment by djindjic** [comment]
after jspm bundle command I have incorrect build file (pushed to production in my case :smiley_cat: )

**Comment by guybedford** [comment]
@djindjic note that in the above the install has completed correctly. It's only after 3 retries that you get a false completion.

I've added some changes in https://github.com/jspm/jspm-cli/commit/a6a556f749ba93d880da694137525f62783b11c5 which should avoid the first issue though.

**Comment by guybedford** [comment]
This should work better now in 0.15.1.
