### ISSUE TITLE
Cannot find module core-js/es6/string

### ISSUE THREAD

**Issue by sochka** [jspm/jspm-cli#636]
Hi, I get the following when I run jspm both locally and globally
```
[18:24:28] ~/Projects/wdc> node ./node_modules/jspm/cli.js install
module.js:324
    throw err;
          ^
Error: Cannot find module 'core-js/es6/string'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/oleksandr/Projects/wdc/node_modules/jspm/cli.js:16:2)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Function.Module.runMain (module.js:487:10)
[18:25:01] ~/Projects/wdc> jspm install
module.js:324
    throw err;
          ^
Error: Cannot find module 'core-js/es6/string'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/oleksandr/Projects/wdc/node_modules/jspm/cli.js:16:2)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
```

**Comment by guybedford** [comment]
Perhaps try reinstalling jspm (or even npm). It sounds like the core-js dependency wasn't installed properly into `node_modules/jspm/node_modules/core-js`.

**Comment by sochka** [comment]
Thanks, that helped.

**Comment by OClement** [comment]
For the record as it might help some googlers:

I experienced this issue when installing my dependencies using an older version of node/npm (Node 4.x) while I initially built my project to use 5.1. In that kind of scenario, deleting the node_modules folder and reinstalling using the correct node/npm version should fix this
