### ISSUE TITLE
GitHub: bad response code 406

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#690]
I have configured the GitHub registry/endpoint with my credentials.

```
warn Error on locate for github:socket.io-client, retrying (2).
     Error: Invalid status code 406
{
  "server": "GitHub.com",
  "date": "Fri, 17 Apr 2015 09:31:19 GMT",
  "content-type": "text/html; charset=utf-8",
  "transfer-encoding": "chunked",
  "connection": "close",
  "status": "406 Not Acceptable",
  "content-security-policy": "default-src *; script-src assets-cdn.github.com collector-cdn.github.com; object-src assets-cdn.github.com; style-src 'self' 'unsafe-inline' 'unsafe-eval' assets-cdn.github.com; img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com; media-src 'none'; frame-src 'self' render.githubusercontent.com gist.github.com www.youtube.com player.vimeo.com checkout.paypal.com; font-src assets-cdn.github.com; connect-src 'self' live.github.com wss://live.github.com uploads.github.com status.github.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com",
  "cache-control": "no-cache",
  "vary": "X-PJAX",
  "x-ua-compatible": "IE=Edge,chrome=1",
  "set-cookie": [
    "logged_in=no; domain=.github.com; path=/; expires=Tue, 17-Apr-2035 09:31:19 GMT; secure; HttpOnly"
  ],
  "x-request-id": "a891b475b21ba4c59cc041dd21e3d251",
  "x-runtime": "0.004082",
  "x-github-request-id": "50FE9E5C:4D85:50BB286:5530D2E7",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "x-frame-options": "deny"
}
         at Request.<anonymous> (/Users/oash/Development/frontend/node_modules/jspm/node_modules/jspm-github/github.js:271:16)
         at Request.emit (events.js:107:17)
         at Request.onRequestResponse (/Users/oash/Development/frontend/node_modules/jspm/node_modules/jspm-github/node_modules/request/request.js:1176:10)
         at ClientRequest.emit (events.js:107:17)
         at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
         at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
         at TLSSocket.socketOnData (_http_client.js:310:20)
         at TLSSocket.emit (events.js:107:17)
         at readableAddChunk (_stream_readable.js:163:16)
         at TLSSocket.Readable.push (_stream_readable.js:126:10)
         at TCP.onread (net.js:529:20)
     Looking up npm:through
```

**Comment by guybedford** [comment]
Is this a GitHub private repo by any chance?

**Comment by guybedford** [comment]
Oh wait, `github:socket.io-client` is not a valid GitHub name.

**Comment by OliverJAsh** [comment]
I was trying to install `github:socket.io-client`. Obviously I was missing the username part of the package ID. Oops!
