### ISSUE TITLE
JSPM init SSL errors

### ISSUE THREAD

**Issue by svantreeck** [jspm/jspm-cli#721]
Hi, I'm trying to setup a project to use jspm, and I'm getting some certificate errors due to our corporate proxy.  I've been able to manually turn off SSL for things like npm to get around this, and to edit my git install's config to trust our certs, but using JSPM, I'm not sure where to begin to be able to work around this.  Any ideas?

```
c:\jspmtester>jspm init
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]
:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [.\jspm_packages]:
Enter config file path [.\config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Which ES6 transpiler would you like to use, Traceur or Babel? [traceur]:
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...

warn Error on download for github:systemjs/systemjs, retrying (1).
     Error: certificate not trusted
         at Error (native)
         at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
         at TLSSocket.emit (events.js:104:17)
         at TLSSocket._finishInit (_tls_wrap.js:458:8)

warn Error on download for github:ModuleLoader/es6-module-loader, retrying (1).
     Error: certificate not trusted
         at Error (native)
         at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
         at TLSSocket.emit (events.js:104:17)
         at TLSSocket._finishInit (_tls_wrap.js:458:8)
```

**Comment by guybedford** [comment]
You can try and configure the proxy to work via the standard environment proxy variables.

Otherwise, we are looking at adding support for disabling strictSSL checking. I've created https://github.com/jspm/jspm-cli/issues/725 to track it.
