### ISSUE TITLE
Error migrating to new jspm folder

### ISSUE THREAD

**Issue by ejsmith** [jspm/jspm-cli#739]
Getting an error trying to config my github token on the new 0.15.5 release.

jspm config registries.github.auth $env:GITHUB_TOKEN

     Migrating global jspm folder from C:\Users\appveyor\.jspm to C:\Users\appveyor\AppData\Local\.jspm...
     Copying configuration...
 
err  Error migrating to new jspm folder
     Error: ENOENT, no such file or directory 'C:\Users\appveyor\.jspm\config'
         at Object.fs.openSync (evalmachine.<anonymous>:439:18)
         at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
         at Object.<anonymous> (C:\Users\appveyor\AppData\Roaming\npm\node_modules\jspm\lib\global-config.js:36:24)
         at Module._compile (module.js:456:26)
         at Object.Module._extensions..js (module.js:474:10)
         at Module.load (module.js:356:32)
         at Function.Module._load (module.js:312:12)
         at Module.require (module.js:364:17)
         at require (module.js:380:17)
         at Object.<anonymous> (C:\Users\appveyor\AppData\Roaming\npm\node_modules\jspm\lib\registry.js:19:20)
         at Module._compile (module.js:456:26)

**Comment by guybedford** [comment]
Thanks so much for reporting this, I've included a fix above. Will release shortly.

**Comment by guybedford** [comment]
Released in 0.15.6.

**Comment by ejsmith** [comment]
Awesome, thanks.
