### ISSUE TITLE
Error for bundled node-forge package

### ISSUE THREAD

**Issue by lewisl9029** [jspm/jspm-cli#750]
I'm trying to use npm:node-forge in an app. It works perfectly when unbundled, but the bundled package gives the following error:

```
Potentially unhandled rejection [2] TypeError: Error loading "app" at http://localhost:8080/app.js
Cannot read property 'map' of undefined
    at Object.module.exports (http://localhost:8080/app.js:15674:22)
    at defineFunc (http://localhost:8080/app.js:15689:12)
    at http://localhost:8080/app.js:15703:18
    at http://localhost:8080/app.js:15704:8
    at linkDynamicModule (http://localhost:8080/jspm_packages/system.src.js:669:32)
    at linkDynamicModule (http://localhost:8080/jspm_packages/system.src.js:663:11)
    at link (http://localhost:8080/jspm_packages/system.src.js:528:11)
    at Object.$__global.upgradeSystemLoader.loader.instantiate.Promise.all.then.execute (http://localhost:8080/jspm_packages/system.src.js:852:11)
    at doDynamicExecute (http://localhost:8080/jspm_packages/es6-module-loader.src.js:1938:25)
    at link (http://localhost:8080/jspm_packages/es6-module-loader.src.js:1986:24)(anonymous function) @ es6-module-loader.src.js:140report @ es6-module-loader.src.js:167flush @ es6-module-loader.src.js:189
```

Quick demo of the issue is available here (bundle is under /build): https://github.com/lewisl9029/jspm-test

**Comment by guybedford** [comment]
Thanks for posting - I've added this to issue https://github.com/systemjs/builder/issues/167, and will track there.
