### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by timbur** [jspm/jspm-cli#763]
Getting this error when calling `jspm install json` but I have a feeling it applies to others as well:

```
err  ReferenceError: window is not defined
         at Config.eval (eval at <anonymous> (jspm/lib/config/loader.js:92:15), <anonymous>:16:23)
         at Config.read (jspm/lib/config/loader.js:92:3)
         at jspm/lib/config.js:94:26
         at tryCatchReject (jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at Pending.run (jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
         at Scheduler._drain (jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
         at Scheduler.drain (jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:62:9)
         at process._tickCallback (node.js:355:11)
```

**Comment by timbur** [comment]
Never mind.  I didn't realize `jspm-cli` would try to evaluate my `config.js` file.
