### ISSUE TITLE
jspm 0.15.7 is not compatible with babel 5.5

### ISSUE THREAD

**Issue by mikz** [jspm/jspm-cli#809]
When I installed jspm yesterday it worked, but today it failed.

Babel released 5.5 which fails bundling with following error message:

```
     Building the bundle tree for main...

       greeter.js
       main
       npm:babel-runtime@5.5.3/core-js/object/define-property
       npm:babel-runtime@5.5.3/helpers/class-call-check
       npm:babel-runtime@5.5.3/helpers/create-class
       npm:core-js@0.9.14/library/fn/object/define-property
       npm:core-js@0.9.14/library/modules/$
       npm:core-js@0.9.14/library/modules/$.fw


err  Error: Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default
         at File.normalizeOptions (file:/Users/mikz/Developer/3scale/jspm/vendor/assets/javascripts/jspm_packages/npm/babel-core@5.5.3/browser.js:8271:15)
         at new File (file:/Users/mikz/Developer/3scale/jspm/vendor/assets/javascripts/jspm_packages/npm/babel-core@5.5.3/browser.js:8237:22)
         at TransformerPipeline.transform (file:/Users/mikz/Developer/3scale/jspm/vendor/assets/javascripts/jspm_packages/npm/babel-core@5.5.3/browser.js:12099:16)
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/compilers/es6.js:125:31
         at tryCatchReject (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at Pending.run (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
         at Scheduler._drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
         at Scheduler.drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:62:9)

```

traced it to https://github.com/babel/babel/commit/32f19aff99559e36c3d4fbb946af378a8126b8bf

Works by locking it to babel 5.4.7.

**Comment by egor-smirnov** [comment]
Same here. Downgrading babel to 5.4.7 helped.

Looks like problematic place is in system.js builder - https://github.com/systemjs/builder/blob/master/compilers/esm.js#L136

Going to check if it is so later.

**Comment by curran** [comment]
+1 I am also getting this error. Will try downgrading Babel.

**Comment by guybedford** [comment]
Thanks I've posted an issue to Babel, otherwise will post out a builder patch first thing tomorrow.

**Comment by curran** [comment]
Thanks!

**Comment by ChrisPiechowicz** [comment]
I get another error probably related to this problem:

TypeError: Cannot read property 'suppressDeprecationMessages' of undefined

babel-core 5.5.4
jspm 0.15.7

**Comment by sebmck** [comment]
There's no reason that error should ever be appearing.

**Comment by haruair** [comment]
I've got a same issue.

    err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
             at Logger.deprecate (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:8889:24)
             at File.normalizeOptions (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:8271:18)
             at new File (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:8237:22)
             at TransformerPipeline.transform (helloworld/jspm_packages/npm/babel-core@5.5.4/browser.js:12107:16)
             at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/compilers/esm.js:143:31
             at runMicrotasksCallback (node.js:337:7)
             at process._tickCallback (node.js:355:11)

Env is here:

    "babel": "npm:babel-core@^5.4.3"
    "babel-runtime": "npm:babel-runtime@^5.4.3"
    "core-js": "npm:core-js@^0.9.10"
    jspm -v # 0.16.0-beta

**Comment by danthareja** [comment]
+1 to @ChrisPiechowicz's error

![screen shot 2015-06-07 at 7 32 43 pm](https://cloud.githubusercontent.com/assets/6980359/8027377/041dcf74-0d4c-11e5-903a-9c0eb9f73690.png)

babel-core 5.5.4
jspm 0.15.7

it worked if I downgrade babel to 5.4.7

**Comment by sebmck** [comment]
Try Babel 5.5.5

**Comment by danthareja** [comment]
it works beautifully, thanks!

**Comment by guybedford** [comment]
Great, thanks @sebmck for following up here.

**Comment by helios1138** [comment]
babel 5.5.8
jspm 0.15.7

issue still present

**Comment by Quirksmode** [comment]
I still get this with the following:

Installed versions of npm:babel-core

       babel 5.8.29 (^5.8.24)
