### ISSUE TITLE
jspm install throws an error on Windows 7

### ISSUE THREAD

**Issue by helarqjsc** [jspm/jspm-cli#818]
Here is the error:
```
$ jspm install jquery

err  TypeError: Object #<Object> has no method 'import'
         at Config.eval (eval at <anonymous> (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\lib\config\loader.js:94:15), <anonymous>:17:14)
         at Config.read (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\lib\config\loader.js:94:3)
         at Promise.resolve.then.then.then.then.then.config.loaded (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\lib\config.js:94:26)
         at tryCatchReject (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\when\es6-shim\Promise.js:1183:30)
         at runContinuation1 (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\when\es6-shim\Promise.js:1142:4)
         at Fulfilled.when (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\when\es6-shim\Promise.js:930:4)
         at Pending.run (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\when\es6-shim\Promise.js:821:13)
         at Scheduler._drain (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\when\es6-shim\Promise.js:97:19)
         at Scheduler.drain (C:\Users\shi\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\when\es6-shim\Promise.js:62:9)
         at process._tickCallback (node.js:442:13)

warn Installation changes not saved.
```

I feel like I'm missing something obvious

**Comment by guybedford** [comment]
@helarqjsc it sounds like you have put code inside of your config.js file?

**Comment by helarqjsc** [comment]
Oops, you are right. I've added 
```
  System.import('js/application');
```
to `config.js`, removing it solved the problem.
