### ISSUE TITLE
Error alongside npm dependencies

### ISSUE THREAD

**Issue by OliverJAsh** [jspm/jspm-cli#839]
Given `package.json` of:

``` json
{
  "name": "foo",
  "version": "0.0.1",
  "dependencies": {
    "jspm": "^0.16.0-beta"
  },
  "jspm": {
    "directories": {},
    "devDependencies": {
      "babel": "npm:babel-core@^5.4.3",
      "babel-runtime": "npm:babel-runtime@^5.4.3",
      "core-js": "npm:core-js@^0.9.10"
    }
  }
}
```

`jspm bundle foo build.js` creates error:

```
err  TypeError: Install of jspm to ^0.16.0-beta has no registry property provided.
         at /Users/OliverJAsh/Development/ab-tests-chrome/node_modules/jspm/lib/package.js:311:13
         at Array.forEach (native)
         at processDeps (/Users/OliverJAsh/Development/ab-tests-chrome/node_modules/jspm/lib/package.js:294:21)
         at setDefaults (/Users/OliverJAsh/Development/ab-tests-chrome/node_modules/jspm/lib/config/package.js:124:25)
         at PackageJSON.read (/Users/OliverJAsh/Development/ab-tests-chrome/node_modules/jspm/lib/config/package.js:112:3)
         at /Users/OliverJAsh/Development/ab-tests-chrome/node_modules/jspm/lib/config.js:74:25
         at runMicrotasksCallback (node.js:337:7)
         at process._tickCallback (node.js:355:11)
         at Function.Module.runMain (module.js:503:11)
         at startup (node.js:129:16)
```

It seems to be looking at the `dependencies` object, when it should only be looking inside of the `jspm` object.

**Comment by guybedford** [comment]
The jspm object acts as an override not the source of truth. I know this can be confusing, though.

**Comment by OliverJAsh** [comment]
Ahh, OK. Just added `"registry": "npm"`.

**Comment by OliverJAsh** [comment]
Hmm that seems to convert my `package.json` to

``` json
{
  "name": "foo",
  "registry": "npm",
  "version": "0.0.1",
  "dependencies": {
    "jspm": "^0.16.0-beta"
  },
  "jspm": true,
  "devDependencies": {
    "babel": "babel-core@^5.4.3",
    "babel-runtime": "^5.4.3",
    "core-js": "^0.9.10"
  }
}
```

**Comment by guybedford** [comment]
```json
{
  "name": "foo",
  "version": "0.0.1",
  "dependencies": {
    "jspm": "^0.16.0-beta"
  },
  "jspm": {
    "directories": {},
    "dependencies": {},
    "devDependencies": {
      "babel": "npm:babel-core@^5.4.3",
      "babel-runtime": "npm:babel-runtime@^5.4.3",
      "core-js": "npm:core-js@^0.9.10"
    }
  }
}
```

Is the suggested way to handle this case.

**Comment by EmergentBehavior** [comment]
I encountered this issue as well. I found that, as @OliverJAsh indicated, it was an override problem. I had an empty `"jspm": {}` I had expected to be filled. When I removed this entry and re-ran `jspm init` all was well.
