### ISSUE TITLE
Failure when attempting bundle-sfx (0.16.beta3)

### ISSUE THREAD

**Issue by patrickmichalina** [jspm/jspm-cli#889]
Since moving to version 16.beta3 I am getting this error when trying to bundle-sfx (this appeared after adding css and text plugins):

```err  AssertionError: missing path
         at Module.require (module.js:363:3)
         at require (module.js:384:17)
         at /Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:157:16
         at Array.forEach (native)
         at wrapSFXOutputs (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:156:26)
         at /Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:136:14
         at lib$rsvp$$internal$$tryCatch (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/Users/Patrick/Desktop/jspm-test/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at process._tickCallback (node.js:355:11)```

**Comment by guybedford** [comment]
If you update the beta version (`npm install -f jspm@beta` perhaps? I never know how to force upgrade sub-dependencies in npm) you will get a more informative error message here that should then solve your issue. Just let me know if you have any further questions.

**Comment by patrickmichalina** [comment]
I ran the command and reinstalled the css plugin. It is still failing with an identical message (which isn't very informative). This wasn't happening in 0.15.7 but the reason I upgraded was because of issue related to importing packages that were failing because of .js (file extensions) not being processed properly. Version 0.16.beta3 fixed this, but now bundle-sfx fails with plugins (at least that is my first suspicion). Unfamiliar with how to debug Node apps, let alone this monster :8ball:

**Comment by guybedford** [comment]
I'm so sorry - that would be because I haven't released the updated error message from https://github.com/systemjs/builder/issues/212.

If you watch that issue I'll post there when it's released.

**Comment by topheman** [comment]
Thanks for all the answers @guybedford , I'll be waiting for the release :+1:

**Comment by patrickmichalina** [comment]
Yes! Thanks for the prompt responses :+1:
