### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by peteruithoven** [jspm/jspm-cli#932]
Using `jspm@0.16.0-beta.3` I suddenly get an error when using `jspm init`. 
```
$ mkdir demo
$ cd demo
$ jspm init
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use an ES6 transpiler? [yes]:
Which ES6 transpiler would you like to use, Traceur, Babel or TypeScript?
(TypeScript does not yet have bundling support in jspm) [babel]:
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...
       system.js
       system.src.js
       system.js.map
       system-csp-production.js
       system-csp-production.src.js
       system-polyfills.js
       system-csp-production.js.map
       system-polyfills.src.js
       system-polyfills.js.map
     
     Using loader versions:
       systemjs@0.18.4

err  URIError: URI malformed
         at decodeURIComponent (native)
         at Object.decodeCredentials (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/auth.js:14:15)
         at Npmrc.getAuth (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/npmrc.js:62:17)
         at Object.NPMLocation (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/npm.js:56:23)
         at Object.exports.load (/usr/local/lib/node_modules/jspm/lib/registry.js:72:56)
         at Object.exports.locate (/usr/local/lib/node_modules/jspm/lib/package.js:65:27)
         at Promise.resolve.then.then.target (/usr/local/lib/node_modules/jspm/lib/install.js:180:16)
         at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at /usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1095:13

err  URIError: URI malformed
         at decodeURIComponent (native)
         at Object.decodeCredentials (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/auth.js:14:15)
         at Npmrc.getAuth (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/npmrc.js:62:17)
         at Object.NPMLocation (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/npm.js:56:23)
         at Object.exports.load (/usr/local/lib/node_modules/jspm/lib/registry.js:72:56)
         at Object.exports.locate (/usr/local/lib/node_modules/jspm/lib/package.js:65:27)
         at Promise.resolve.then.then.target (/usr/local/lib/node_modules/jspm/lib/install.js:180:16)
         at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at /usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1095:13

err  URIError: URI malformed
         at decodeURIComponent (native)
         at Object.decodeCredentials (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/auth.js:14:15)
         at Npmrc.getAuth (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/npmrc.js:62:17)
         at Object.NPMLocation (/usr/local/lib/node_modules/jspm/node_modules/jspm-npm/lib/npm.js:56:23)
         at Object.exports.load (/usr/local/lib/node_modules/jspm/lib/registry.js:72:56)
         at Object.exports.locate (/usr/local/lib/node_modules/jspm/lib/package.js:65:27)
         at Promise.resolve.then.then.target (/usr/local/lib/node_modules/jspm/lib/install.js:180:16)
         at lib$rsvp$$internal$$tryCatch (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at /usr/local/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1095:13

err  Error downloading loader files.

err  Unable to load registry npm
```

I tried 
- uninstalling and reinstalling jspm. 
- Using npm (`npm init` and `npm install express`), this worked fine. 

When installing jspm locally first (see below) there was no issue?
```
$ mkdir demo
$ cd demo
$ npm init
$ npm install jspm
$ jspm init
```

**Comment by peteruithoven** [comment]
I think it's a jspm version issue. 
When I'm locally install jspm it install's `jspm@0.15.7`, while I globally use `jspm@0.16.0-beta.3`. I assumed uninstalling (`npm uninstall jspm -g`) and then reinstalling it (`npm install jspm -g`) would get me the non beta version. 
So the main difference is the jspm version.

**Comment by peteruithoven** [comment]
After properly uninstalling jspm globally and reinstalling it again (using the non beta `jspm@0.15.7` version) there is no issue. 
Maybe I was doing something wrong with the beta version.

**Comment by guybedford** [comment]
@peteruithoven thanks for posting, yes this was an issue in the beta. I've pushed a fix - can you try installing the beta again and let me know if it works for you now? Would be much appreciated.

**Comment by peteruithoven** [comment]
Nice, I installed the beta again and it seems fixed. 
I do get some warnings though, not sure it they are relevant. 
```
$ jspm init
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Do you wish to use an ES6 transpiler? [yes]:
Which ES6 transpiler would you like to use, Traceur, Babel or TypeScript?
(TypeScript does not yet have bundling support in jspm) [babel]:
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...

       system.js
       system.src.js
       system-csp-production.js
       system.js.map
       system-polyfills.js
       system-csp-production.js.map
       system-csp-production.src.js
       system-polyfills.js.map
       system-polyfills.src.js
     
     Using loader versions:
       systemjs@0.18.4
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Updating registry cache...
     Downloading npm:core-js@0.9.18
     Downloading npm:babel-runtime@5.6.20
     Downloading npm:babel-core@5.6.20
     Looking up github:jspm/nodelibs-process
     Downloading github:jspm/nodelibs-process@0.1.1
     Looking up npm:process

warn Error on lookup for npm:process
     Error: connect EMFILE
         at errnoException (net.js:904:11)
         at connect (net.js:766:19)
         at net.js:845:9
         at asyncCallback (dns.js:68:16)
         at Object.onanswer [as oncomplete] (dns.js:121:9)

warn Error looking up npm:process.

warn Error looking up npm:process.
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-fs
     Downloading github:jspm/nodelibs-fs@0.1.2
     Downloading github:systemjs/plugin-json@0.1.0
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.1)

err  Error downloading loader files.

err  Error looking up npm:process.
ok   Installed babel as npm:babel-core@^5.6.4 (5.6.20)
ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)
ok   Installed github:systemjs/plugin-json@^0.1.0 (0.1.0)
```

**Comment by guybedford** [comment]
Great, thanks for the update. It could be worth increasing your ulimit. See for example http://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os.

**Comment by peteruithoven** [comment]
I think you're right. I increased the limit using: 
```
launchctl limit maxfiles 1024 1024 
```
Now I get zero errors.
