### ISSUE TITLE
TypeError: Cannot read property 'suppressDeprecationMessages' of undefined

### ISSUE THREAD

**Issue by nvivo** [jspm/jspm-cli#933]
Following the getting started instructions, I'm not able to bundle a simple app. On linux, I can reproduce this with this commands:

```
jspm init
echo 'export var foo = {};' > app.js
jspm bundle app
```

Gives me:

```
TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
```

Seems to the same as #809, and reported in https://github.com/babel/babel/issues/1992, but I'm still getting this right now with the current stable versions.

Here is the full log of what happens here:
```
$ jspm --version
0.15.7
Running against global jspm install.

$ jspm init
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]:
Enter server baseURL (public folder path) [./]:
Enter jspm packages folder [./jspm_packages]:
Enter config file path [./config.js]:
Configuration file config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Which ES6 transpiler would you like to use, Traceur or Babel? [babel]:
ok   Verified package.json at package.json
     Verified config file at config.js
     Looking up loader files...
       es6-module-loader.js
       es6-module-loader.src.js
       es6-module-loader.js.map
       system.js
       system.src.js
       system.js.map
     
     Using loader versions:
       es6-module-loader@0.16.6
       systemjs@0.16.11
     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:core-js
     Updating registry cache...
ok   Installed babel as npm:babel-core@^5.1.13 (5.6.20)
     Looking up github:jspm/nodelibs-fs
     Looking up github:systemjs/plugin-json
     Looking up github:jspm/nodelibs-process
ok   Installed github:jspm/nodelibs-fs@^0.1.0 (0.1.2)
ok   Installed github:systemjs/plugin-json@^0.1.0 (0.1.0)
ok   Installed github:jspm/nodelibs-process@^0.1.0 (0.1.1)
     Looking up npm:process
ok   Installed npm:process@^0.10.0 (0.10.1)
ok   Installed babel-runtime as npm:babel-runtime@^5.1.13 (5.6.20)
ok   Installed core-js as npm:core-js@^0.9.4 (0.9.18)
ok   Loader files downloaded successfully

$ jspm inspect
     Installed Versions

            github:jspm/nodelibs-fs 0.1.2
       github:jspm/nodelibs-process 0.1.1
        github:systemjs/plugin-json 0.1.0
                     npm:babel-core 5.6.20
                  npm:babel-runtime 5.6.20
                        npm:core-js 0.9.18
                        npm:process 0.10.1
     
     To inspect individual package constraints, use jspm inspect registry:name.

$ echo 'export var foo = {};' > app.js

$ jspm bundle app
     Building the bundle tree for app...
     
       app
     

err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
         at Logger.deprecate (file:/home/nvivo/test/jspm_packages/npm/babel-core@5.6.20/browser.js:10446:23)
         at OptionManager.normaliseOptions (file:/home/nvivo/test/jspm_packages/npm/babel-core@5.6.20/browser.js:10982:18)
         at OptionManager.init (file:/home/nvivo/test/jspm_packages/npm/babel-core@5.6.20/browser.js:11025:10)
         at File.initOptions (file:/home/nvivo/test/jspm_packages/npm/babel-core@5.6.20/browser.js:9705:75)
         at new File (file:/home/nvivo/test/jspm_packages/npm/babel-core@5.6.20/browser.js:9692:22)
         at Pipeline.transform (file:/home/nvivo/test/jspm_packages/npm/babel-core@5.6.20/browser.js:15057:16)
         at /usr/lib/node_modules/jspm/node_modules/systemjs-builder/compilers/es6.js:125:31
         at tryCatchReject (/usr/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/usr/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/usr/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
```

**Comment by simonewebdesign** [comment]
Exactly the same issue I'm struggling with at the moment.

**Comment by aaronsgithub** [comment]
I had this issue as well.

I downgraded babel-core and babel-runtime from version 5.6.20 to version 5.5.5 after seeing this issue issue #809 and it works.

**Comment by nvivo** [comment]
@aaronsgithub I agree it's simple to create workarounds, but it since this keeps reappearing, maybe jspm should add a check to see if the property is there.

But I don't have enough knowledge of the sources to know if that is the correct path to take.

**Comment by nvivo** [comment]
I'm closing this issue, as it seems this was fixed on Babel: https://github.com/babel/babel/commit/4656801673812159fa5f688dea536332156f536b
