### ISSUE TITLE
jspm init fails in empty asp.net 5.0 project (visual studio 2015 RTM)

### ISSUE THREAD

**Issue by apDyn** [jspm/jspm-cli#955]
Hi, guys.
Following your getting started wiki at: https://github.com/jspm/jspm-cli/wiki/Getting-Started
I got to jspm init but it failed with the following printout:

```
C:\Dev\test-git\WebApplication3\src\WebApplication3>jspm init
Package.json file does not exist, create it? [yes]:
Would you like jspm to prefix the jspm package.json properties under jspm? [yes]
:
Enter server baseURL (public folder path) [./]:./wwwroot
Enter jspm packages folder [wwwroot\jspm_packages]:
Enter config file path [wwwroot\config.js]:
Configuration file wwwroot\config.js doesn't exist, create it? [yes]:
Enter client baseURL (public folder URL) [/]:
Which ES6 transpiler would you like to use, Traceur or Babel? [traceur]:
ok   Verified package.json at package.json
     Verified config file at wwwroot\config.js
     Looking up loader files...
       system.js.map
       system.src.js
       system.js
       es6-module-loader.js.map
       es6-module-loader.js
       es6-module-loader.src.js

     Using loader versions:
       es6-module-loader@0.16.6
       systemjs@0.16.11
     Looking up github:jmcriffey/bower-traceur
     Looking up github:jmcriffey/bower-traceur-runtime
     Updating registry cache...

warn Error on getOverride for jspm:github, retrying (1).
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

warn Error on getOverride for jspm:github, retrying (1).
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

warn Error on getOverride for jspm:github, retrying (2).
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

warn Error on getOverride for jspm:github, retrying (2).
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

warn Error on getOverride for jspm:github, retrying (3).
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

warn Error on getOverride for jspm:github, retrying (3).
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

warn Error on getOverride for jspm:github
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

warn Error on getOverride for jspm:github
     Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git fetch --all &
& git reset --hard origin/master"
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read c844d6e9846d16de721ccd148535c9245216fb49
     error: Could not read 71e140765fe258dee3dc3fcaf3a2d0770f80175c
     error: Could not read 5b2fac719faf2b57f48e1282ec673281b1d9d0f8
     error: Could not read 10b982b70fead5e7e8436571a77c72df38c0694e
     fatal: pack has 85 unresolved deltas
     fatal: index-pack failed
     error: Could not fetch origin

         at ChildProcess.exithandler (child_process.js:751:12)
         at ChildProcess.emit (events.js:110:17)
         at maybeClose (child_process.js:1015:16)
         at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

err  Error downloading loader files.

err  undefined
```

**Comment by kudos** [comment]
Please try again, looks like Github connectivity issues and not a jspm bug.

**Comment by apDyn** [comment]
I tried several times over the past 2 days, and still same errors appear.

**Comment by guybedford** [comment]
@apDyn perhaps try clearing your cache - `jspm cc`, and see if that helps?

**Comment by apDyn** [comment]
That did the trick. Thanks!

**Comment by apDyn** [comment]
That did the trick. Thanks!

**Comment by apDyn** [comment]
That did the trick. Thanks!

**Comment by apDyn** [comment]
That did the trick. Thanks!
